// apps/docs/content/docs/_snippets/popover/controlled.tsx
/* eslint-disable no-unused-vars, no-unused-expressions */
//#region demo

import { Button, Popover } from '@moduix/react';
import { useState } from 'react';

export function ControlledPopoverDemo() {
  const [open, setOpen] = useState(false);
  return (
    <div className="stack">
      <span>Popover is {open ? 'open' : 'closed'}</span>
      <Popover open={open} onOpenChange={(details) => setOpen(details.open)}>
        <Popover.Trigger asChild>
          <Button>Open controlled popover</Button>
        </Popover.Trigger>
        <Popover.Positioner>
          <Popover.Content>
            <Popover.Header>
              <Popover.Title>Publish changes?</Popover.Title>
              <Popover.Description>
                This action will make your latest updates visible to all users.
              </Popover.Description>
            </Popover.Header>
            <Popover.Footer>
              <Popover.CloseTrigger>Close</Popover.CloseTrigger>
            </Popover.Footer>
          </Popover.Content>
        </Popover.Positioner>
      </Popover>
    </div>
  );
}

//#endregion

// website/snippets/dialog/solid/controlled.tsx
import { Button } from '@moduix/solid/button';
import { Dialog } from '@moduix/solid/dialog';
import { createSignal } from 'solid-js';

export default function ControlledDialogDemo() {
  const [open, setOpen] = createSignal(false);

  return (
    <Dialog open={open()} onOpenChange={(details) => setOpen(details.open)}>
      <Dialog.Trigger asChild={(props) => <Button {...props()}>Open controlled dialog</Button>} />
      <Dialog.Backdrop />
      <Dialog.Positioner>
        <Dialog.Content>
          <Dialog.Title>Publish changes?</Dialog.Title>
          <Dialog.CloseIcon />
        </Dialog.Content>
      </Dialog.Positioner>
    </Dialog>
  );
}
