// apps/docs/docs/en/docs/_snippets/dialog/controlled.tsx
import { Button } from '@moduix/react/button';
import { Dialog } from '@moduix/react/dialog';
import { useState } from 'react';

export default function ControlledDialogDemo() {
  const [open, setOpen] = useState(false);
  return (
    <Dialog open={open} onOpenChange={(details) => setOpen(details.open)}>
      <Dialog.Trigger asChild>
        <Button>Open controlled dialog</Button>
      </Dialog.Trigger>
      <Dialog.Backdrop />
      <Dialog.Positioner>
        <Dialog.Content>
          <Dialog.Title>Publish changes?</Dialog.Title>
          <Dialog.CloseIcon />
        </Dialog.Content>
      </Dialog.Positioner>
    </Dialog>
  );
}

// website/snippets/dialog/solid/controlled.tsx
import { Button } from '@moduix/solid/button';
import { Dialog } from '@moduix/solid/dialog';
import { createSignal } from 'solid-js';

export default function ControlledDialogDemo() {
  const [open, setOpen] = createSignal(false);

  return (
    <Dialog open={open()} onOpenChange={(details) => setOpen(details.open)}>
      <Dialog.Trigger asChild={(props) => <Button {...props()}>Open controlled dialog</Button>} />
      <Dialog.Backdrop />
      <Dialog.Positioner>
        <Dialog.Content>
          <Dialog.Title>Publish changes?</Dialog.Title>
          <Dialog.CloseIcon />
        </Dialog.Content>
      </Dialog.Positioner>
    </Dialog>
  );
}
