// apps/docs/docs/en/docs/_snippets/number-input/scrubbing.tsx
import { NumberInput } from '@moduix/react/number-input';
import { useState } from 'react';
import { PreviewMeta } from '@/components/mdx/Components';

export default function NumberInputScrubberDemo() {
  const [value, setValue] = useState('250');

  return (
    <div>
      <NumberInput defaultValue="250" onValueChange={(details) => setValue(details.value)}>
        <NumberInput.Label>Adjust value</NumberInput.Label>
        <NumberInput.Scrubber>Drag left or right to adjust</NumberInput.Scrubber>
        <NumberInput.Field />
      </NumberInput>
      <PreviewMeta style={{ marginInline: 'auto' }}>
        <output>Value: {value}</output>
      </PreviewMeta>
    </div>
  );
}

// website/snippets/number-input/solid/scrubbing.tsx
import { NumberInput } from '@moduix/solid/number-input';
import { createSignal } from 'solid-js';
import styles from '@/components/examples/number-input/number-input-scrubbing.module.css';

export default function NumberInputScrubberDemo() {
  const [value, setValue] = createSignal('250');

  return (
    <div class={styles.root}>
      <NumberInput defaultValue="250" onValueChange={(details) => setValue(details.value)}>
        <NumberInput.Label>Adjust value</NumberInput.Label>
        <NumberInput.Scrubber>Drag left or right to adjust</NumberInput.Scrubber>
        <NumberInput.Field />
      </NumberInput>
      <output>Value: {value()}</output>
    </div>
  );
}
