// packages/solid/src/components/radio-group/RadioGroup.tsx
import {
  RadioGroup as RadioGroupPrimitive,
  useRadioGroup,
  useRadioGroupContext,
  useRadioGroupItemContext,
} from '@ark-ui/solid/radio-group';
import { clsx } from 'clsx';
import type { ComponentProps, JSX } from 'solid-js';
import { splitProps } from 'solid-js';
import styles from './RadioGroup.module.css';

type RadioGroupItemControlSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
type RadioGroupItemControlProps = ComponentProps<typeof RadioGroupPrimitive.ItemControl> & {
  size?: RadioGroupItemControlSize;
};
type RadioGroupOptionProps = Omit<
  ComponentProps<typeof RadioGroupPrimitive.Item>,
  'asChild' | 'children'
> & {
  children: JSX.Element;
  size?: RadioGroupItemControlSize;
};

function RadioGroupRoot(props: ComponentProps<typeof RadioGroupPrimitive.Root>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <RadioGroupPrimitive.Root
      asChild={local.asChild}
      {...others}
      data-slot="radio-group-root"
      class={clsx(styles.root, local.class)}
    />
  );
}

function RadioGroupRootProvider(props: ComponentProps<typeof RadioGroupPrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <RadioGroupPrimitive.RootProvider
      asChild={local.asChild}
      {...others}
      data-slot="radio-group-root-provider"
      class={clsx(styles.root, local.class)}
    />
  );
}

function RadioGroupLabel(props: ComponentProps<typeof RadioGroupPrimitive.Label>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <RadioGroupPrimitive.Label
      {...others}
      data-slot="radio-group-label"
      class={clsx(styles.label, local.class)}
    />
  );
}

function RadioGroupItem(props: ComponentProps<typeof RadioGroupPrimitive.Item>) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);

  return (
    <RadioGroupPrimitive.Item
      asChild={local.asChild}
      {...others}
      data-slot="radio-group-item"
      class={clsx(styles.item, local.class)}
    >
      {local.children}
    </RadioGroupPrimitive.Item>
  );
}

function RadioGroupOption(props: RadioGroupOptionProps) {
  const [local, others] = splitProps(props, ['children', 'size']);

  return (
    <RadioGroupItem {...others}>
      <RadioGroupPrimitive.ItemHiddenInput />
      <RadioGroupItemControl size={local.size} />
      <RadioGroupItemText>{local.children}</RadioGroupItemText>
    </RadioGroupItem>
  );
}

function RadioGroupItemControl(props: RadioGroupItemControlProps) {
  const [local, others] = splitProps(props, ['class', 'size']);

  return (
    <RadioGroupPrimitive.ItemControl
      {...others}
      data-slot="radio-group-item-control"
      data-size={local.size ?? 'md'}
      class={clsx(styles.itemControl, local.class)}
    />
  );
}

function RadioGroupItemText(props: ComponentProps<typeof RadioGroupPrimitive.ItemText>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <RadioGroupPrimitive.ItemText
      {...others}
      data-slot="radio-group-item-text"
      class={clsx(styles.itemText, local.class)}
    />
  );
}

function RadioGroupIndicator(props: ComponentProps<typeof RadioGroupPrimitive.Indicator>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <RadioGroupPrimitive.Indicator
      {...others}
      data-slot="radio-group-indicator"
      class={clsx(styles.indicator, local.class)}
    />
  );
}

const RadioGroup = Object.assign(RadioGroupRoot, {
  Root: RadioGroupRoot,
  RootProvider: RadioGroupRootProvider,
  Context: RadioGroupPrimitive.Context,
  ItemContext: RadioGroupPrimitive.ItemContext,
  Label: RadioGroupLabel,
  Item: RadioGroupItem,
  ItemHiddenInput: RadioGroupPrimitive.ItemHiddenInput,
  Option: RadioGroupOption,
  ItemControl: RadioGroupItemControl,
  ItemText: RadioGroupItemText,
  Indicator: RadioGroupIndicator,
});

export { RadioGroup, useRadioGroup, useRadioGroupContext, useRadioGroupItemContext };
export type { RadioGroupItemControlProps, RadioGroupItemControlSize, RadioGroupOptionProps };

// packages/react/src/components/radio-group/RadioGroup.tsx
'use client';

import {
  RadioGroup as RadioGroupPrimitive,
  useRadioGroup,
  useRadioGroupContext,
  useRadioGroupItemContext,
} from '@ark-ui/react/radio-group';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef, ReactNode } from 'react';
import { forwardRef } from 'react';
import styles from './RadioGroup.module.css';

type RadioGroupItemControlSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
type RadioGroupItemControlProps = ComponentProps<typeof RadioGroupPrimitive.ItemControl> & {
  size?: RadioGroupItemControlSize;
};
type RadioGroupOptionProps = Omit<
  ComponentProps<typeof RadioGroupPrimitive.Item>,
  'asChild' | 'children'
> & {
  children: ReactNode;
  size?: RadioGroupItemControlSize;
};

const RadioGroupRoot = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.Root>,
  ComponentProps<typeof RadioGroupPrimitive.Root>
>(function RadioGroupRoot({ className, ...props }, ref) {
  return (
    <RadioGroupPrimitive.Root
      ref={ref}
      className={clsx(styles.root, className)}
      {...props}
      data-slot="radio-group-root"
    />
  );
});

const RadioGroupRootProvider = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.RootProvider>,
  ComponentProps<typeof RadioGroupPrimitive.RootProvider>
>(function RadioGroupRootProvider({ className, ...props }, ref) {
  return (
    <RadioGroupPrimitive.RootProvider
      ref={ref}
      className={clsx(styles.root, className)}
      {...props}
      data-slot="radio-group-root-provider"
    />
  );
});

const RadioGroupLabel = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.Label>,
  ComponentProps<typeof RadioGroupPrimitive.Label>
>(function RadioGroupLabel({ className, ...props }, ref) {
  return (
    <RadioGroupPrimitive.Label
      ref={ref}
      className={clsx(styles.label, className)}
      {...props}
      data-slot="radio-group-label"
    />
  );
});

const RadioGroupItem = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.Item>,
  ComponentProps<typeof RadioGroupPrimitive.Item>
>(function RadioGroupItem({ className, ...props }, ref) {
  return (
    <RadioGroupPrimitive.Item
      ref={ref}
      className={clsx(styles.item, className)}
      {...props}
      data-slot="radio-group-item"
    />
  );
});

const RadioGroupOption = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.Item>,
  RadioGroupOptionProps
>(function RadioGroupOption({ children, size, ...props }, ref) {
  return (
    <RadioGroupItem ref={ref} {...props}>
      <RadioGroupPrimitive.ItemHiddenInput />
      <RadioGroupItemControl size={size} />
      <RadioGroupItemText>{children}</RadioGroupItemText>
    </RadioGroupItem>
  );
});

const RadioGroupItemControl = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.ItemControl>,
  RadioGroupItemControlProps
>(function RadioGroupItemControl({ className, size = 'md', ...props }, ref) {
  return (
    <RadioGroupPrimitive.ItemControl
      ref={ref}
      className={clsx(styles.itemControl, className)}
      {...props}
      data-size={size}
      data-slot="radio-group-item-control"
    />
  );
});

const RadioGroupItemText = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.ItemText>,
  ComponentProps<typeof RadioGroupPrimitive.ItemText>
>(function RadioGroupItemText({ className, ...props }, ref) {
  return (
    <RadioGroupPrimitive.ItemText
      ref={ref}
      className={clsx(styles.itemText, className)}
      {...props}
      data-slot="radio-group-item-text"
    />
  );
});

const RadioGroupIndicator = forwardRef<
  ComponentRef<typeof RadioGroupPrimitive.Indicator>,
  ComponentProps<typeof RadioGroupPrimitive.Indicator>
>(function RadioGroupIndicator({ className, ...props }, ref) {
  return (
    <RadioGroupPrimitive.Indicator
      ref={ref}
      className={clsx(styles.indicator, className)}
      {...props}
      data-slot="radio-group-indicator"
    />
  );
});

const RadioGroup = Object.assign(RadioGroupRoot, {
  Root: RadioGroupRoot,
  RootProvider: RadioGroupRootProvider,
  Context: RadioGroupPrimitive.Context,
  ItemContext: RadioGroupPrimitive.ItemContext,
  Label: RadioGroupLabel,
  Item: RadioGroupItem,
  ItemHiddenInput: RadioGroupPrimitive.ItemHiddenInput,
  Option: RadioGroupOption,
  ItemControl: RadioGroupItemControl,
  ItemText: RadioGroupItemText,
  Indicator: RadioGroupIndicator,
});

export { RadioGroup, useRadioGroup, useRadioGroupContext, useRadioGroupItemContext };
export type { RadioGroupItemControlProps, RadioGroupItemControlSize, RadioGroupOptionProps };
