// apps/docs/docs/en/docs/_snippets/field/select.tsx
import { createListCollection } from '@ark-ui/react/collection';
import { Field } from '@moduix/react/field';
import { Select } from '@moduix/react/select';

const priorities = createListCollection({
  items: [
    { label: 'Low', value: 'low' },
    { label: 'Normal', value: 'normal' },
    { label: 'High', value: 'high' },
  ],
});

export default function SelectFieldDemo() {
  return (
    <Field required>
      <Select collection={priorities} name="priority">
        <Select.Label>Priority</Select.Label>
        <Select.Control>
          <Select.Trigger>
            <Select.ValueText placeholder="Select priority" />
            <Select.Indicator />
          </Select.Trigger>
        </Select.Control>
        <Select.Positioner>
          <Select.Content>
            {priorities.items.map((item) => (
              <Select.Item key={item.value} item={item}>
                <Select.ItemText>{item.label}</Select.ItemText>
                <Select.ItemIndicator />
              </Select.Item>
            ))}
          </Select.Content>
        </Select.Positioner>
      </Select>
      <Field.HelperText>Used for triage queues.</Field.HelperText>
    </Field>
  );
}

// website/snippets/field/vue/select.vue
<script setup lang="ts">
import { createListCollection } from '@ark-ui/vue/collection';
import {
  SelectContent,
  SelectControl,
  SelectHiddenSelect,
  SelectIndicator,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectPositioner,
  SelectRoot,
  SelectTrigger,
  SelectValueText,
} from '@ark-ui/vue/select';
import { Field, FieldHelperText } from '@moduix/vue/field';
import styles from '@/components/examples/field/field-select.module.css';

type Priority = { label: string; value: string };

const priorities = createListCollection<Priority>({
  items: [
    { label: 'Low', value: 'low' },
    { label: 'Normal', value: 'normal' },
    { label: 'High', value: 'high' },
  ],
});
</script>

<template>
  <Field :class="styles.root">
    <SelectRoot :collection="priorities" required name="priority">
      <SelectLabel>Priority</SelectLabel>
      <SelectControl>
        <SelectTrigger><SelectValueText placeholder="Select priority" /></SelectTrigger>
        <SelectIndicator />
      </SelectControl>
      <SelectPositioner>
        <SelectContent>
          <SelectItem v-for="item in priorities.items" :key="item.value" :item="item">
            <SelectItemText>{{ item.label }}</SelectItemText>
            <SelectItemIndicator />
          </SelectItem>
        </SelectContent>
      </SelectPositioner>
      <SelectHiddenSelect />
    </SelectRoot>
    <FieldHelperText>Used for triage queues.</FieldHelperText>
  </Field>
</template>
