// website/snippets/carousel/solid/pause-on-hover.tsx
import {
  Carousel,
  CarouselAutoplayIndicator,
  CarouselAutoplayTrigger,
  CarouselContext,
  CarouselControl,
  CarouselIndicators,
  CarouselItem,
  CarouselItemGroup,
} from '@moduix/solid/carousel';
import { For } from 'solid-js';
import styles from '@/components/examples/carousel/carousel-pause-on-hover.module.css';

const slides = [
  {
    id: 'fjord',
    src: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1280&q=80',
    alt: 'A lakeside landscape with mountains and warm sunset light.',
  },
  {
    id: 'coast',
    src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1280&q=80',
    alt: 'Ocean waves rolling onto a sandy beach.',
  },
  {
    id: 'village',
    src: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1280&q=80',
    alt: 'A colorful hillside town on the coast.',
  },
  {
    id: 'forest',
    src: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=1280&q=80',
    alt: 'A misty green forest with tall trees.',
  },
  {
    id: 'desert',
    src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1280&q=80',
    alt: 'Golden sand dunes under a bright sky.',
  },
];

export default function PauseOnHoverCarousel() {
  return (
    <Carousel
      class={styles.root}
      aria-label="Pause on hover gallery"
      autoplay
      loop
      slideCount={slides.length}
    >
      <CarouselContext>
        {(api) => (
          <>
            <CarouselItemGroup
              class={styles.itemGroup}
              onFocus={() => api().pause()}
              onPointerEnter={() => api().pause()}
              onPointerLeave={() => api().play()}
            >
              <For each={slides}>
                {(slide, index) => (
                  <CarouselItem index={index()}>
                    <img class={styles.image} src={slide.src} alt={slide.alt} />
                  </CarouselItem>
                )}
              </For>
            </CarouselItemGroup>
            <CarouselControl
              class={styles.control}
              onFocus={() => api().pause()}
              onPointerEnter={() => api().pause()}
              onPointerLeave={() => api().play()}
            >
              <CarouselAutoplayTrigger>
                <CarouselAutoplayIndicator fallback="Play">Pause</CarouselAutoplayIndicator>
              </CarouselAutoplayTrigger>
              <CarouselIndicators />
            </CarouselControl>
            <output>Autoplay: {api().isPlaying ? 'playing' : 'paused'}</output>
          </>
        )}
      </CarouselContext>
    </Carousel>
  );
}

// website/src/components/examples/carousel/pause-on-hover.tsx
import {
  Carousel,
  CarouselAutoplayIndicator,
  CarouselAutoplayTrigger,
  CarouselContext,
  CarouselControl,
  CarouselIndicators,
  CarouselItem,
  CarouselItemGroup,
} from '@moduix/react/carousel';
import { PreviewMeta } from '@/components/mdx/Components';
import styles from '@/components/examples/carousel/carousel-pause-on-hover.module.css';

const slides = [
  {
    id: 'fjord',
    src: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1280&q=80',
    alt: 'A lakeside landscape with mountains and warm sunset light.',
  },
  {
    id: 'coast',
    src: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1280&q=80',
    alt: 'Ocean waves rolling onto a sandy beach.',
  },
  {
    id: 'village',
    src: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1280&q=80',
    alt: 'A colorful hillside town on the coast.',
  },
  {
    id: 'forest',
    src: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=1280&q=80',
    alt: 'A misty green forest with tall trees.',
  },
  {
    id: 'desert',
    src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1280&q=80',
    alt: 'Golden sand dunes under a bright sky.',
  },
];

export default function PauseOnHoverCarousel() {
  return (
    <Carousel
      className={styles.root}
      aria-label="Pause on hover gallery"
      autoplay
      loop
      slideCount={slides.length}
    >
      <CarouselContext>
        {(api) => (
          <>
            <CarouselItemGroup
              className={styles.itemGroup}
              onFocus={() => api.pause()}
              onPointerEnter={() => api.pause()}
              onPointerLeave={() => api.play()}
            >
              {slides.map((slide, index) => (
                <CarouselItem key={slide.id} index={index}>
                  <img className={styles.image} src={slide.src} alt={slide.alt} />
                </CarouselItem>
              ))}
            </CarouselItemGroup>
            <CarouselControl
              className={styles.control}
              onFocus={() => api.pause()}
              onPointerEnter={() => api.pause()}
              onPointerLeave={() => api.play()}
            >
              <CarouselAutoplayTrigger>
                <CarouselAutoplayIndicator fallback="Play">Pause</CarouselAutoplayIndicator>
              </CarouselAutoplayTrigger>
              <CarouselIndicators />
            </CarouselControl>
            <PreviewMeta style={{ marginInline: 'auto' }}>
              <output>Autoplay: {api.isPlaying ? 'playing' : 'paused'}</output>
            </PreviewMeta>
          </>
        )}
      </CarouselContext>
    </Carousel>
  );
}
