// apps/docs/docs/en/docs/_snippets/floating-panel/boundary.tsx
import { Button, FloatingPanel } from '@moduix/react';
import { useRef } from 'react';

export default function BoundaryFloatingPanelDemo() {
  const boundaryRef = useRef<HTMLDivElement>(null);

  return (
    <div
      ref={boundaryRef}
      style={{
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        inlineSize: '100%',
        minHeight: 320,
        border: '1px dashed var(--moduix-color-border)',
        borderRadius: 'var(--moduix-radius-md)',
        padding: 'var(--moduix-spacing-3)',
      }}
    >
      <FloatingPanel
        allowOverflow={false}
        defaultSize={{ width: 300, height: 220 }}
        getBoundaryEl={() => boundaryRef.current}
        getAnchorPosition={({ boundaryRect }) => ({
          x: (boundaryRect?.x ?? 0) + 16,
          y: (boundaryRect?.y ?? 0) + 16,
        })}
      >
        <FloatingPanel.Trigger asChild>
          <Button>Open constrained panel</Button>
        </FloatingPanel.Trigger>
        <FloatingPanel.Positioner>
          <FloatingPanel.Content>
            <FloatingPanel.DragTrigger>
              <FloatingPanel.Header>
                <FloatingPanel.Title>
                  <FloatingPanel.DragIndicator />
                  Boundary
                </FloatingPanel.Title>
                <FloatingPanel.Control>
                  <FloatingPanel.CloseIcon />
                </FloatingPanel.Control>
              </FloatingPanel.Header>
            </FloatingPanel.DragTrigger>
            <FloatingPanel.Body>
              This panel stays inside the dashed boundary while you drag it.
            </FloatingPanel.Body>
            <FloatingPanel.ResizeTriggerGroup />
          </FloatingPanel.Content>
        </FloatingPanel.Positioner>
      </FloatingPanel>
    </div>
  );
}

// website/snippets/floating-panel/vue/boundary.vue
<script setup lang="ts">
import { Button } from '@moduix/vue/button';
import {
  FloatingPanel,
  FloatingPanelBody,
  FloatingPanelCloseIcon,
  FloatingPanelContent,
  FloatingPanelControl,
  FloatingPanelDragIndicator,
  FloatingPanelDragTrigger,
  FloatingPanelHeader,
  FloatingPanelPositioner,
  FloatingPanelResizeTriggerGroup,
  FloatingPanelTitle,
  FloatingPanelTrigger,
} from '@moduix/vue/floating-panel';
import { ref } from 'vue';
import styles from '@/components/examples/floating-panel/floating-panel-boundary.module.css';

const boundaryRef = ref<HTMLDivElement>();
const getBoundaryEl = () => boundaryRef.value ?? null;
const getAnchorPosition = ({ boundaryRect }: { boundaryRect: DOMRect | null }) => ({
  x: (boundaryRect?.x ?? 0) + 16,
  y: (boundaryRect?.y ?? 0) + 16,
});
</script>

<template>
  <div ref="boundaryRef" :class="styles.root">
    <FloatingPanel
      :allow-overflow="false"
      :default-size="{ width: 300, height: 220 }"
      :get-boundary-el="getBoundaryEl"
      :get-anchor-position="getAnchorPosition"
    >
      <FloatingPanelTrigger as-child><Button>Open constrained panel</Button></FloatingPanelTrigger>
      <FloatingPanelPositioner
        ><FloatingPanelContent
          ><FloatingPanelDragTrigger
            ><FloatingPanelHeader
              ><FloatingPanelTitle><FloatingPanelDragIndicator />Boundary</FloatingPanelTitle
              ><FloatingPanelControl
                ><FloatingPanelCloseIcon /></FloatingPanelControl></FloatingPanelHeader></FloatingPanelDragTrigger
          ><FloatingPanelBody
            >This panel stays inside the dashed boundary while you drag it.</FloatingPanelBody
          ><FloatingPanelResizeTriggerGroup /></FloatingPanelContent
      ></FloatingPanelPositioner>
    </FloatingPanel>
  </div>
</template>
