// packages/solid/src/components/editable/Editable.tsx
import {
  Editable as EditablePrimitive,
  useEditable,
  useEditableContext,
} from '@ark-ui/solid/editable';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { children, Show, splitProps } from 'solid-js';
import { CheckIcon, CloseIcon, PencilIcon } from '@/lib/moduix/icons/ui/Icons';
import styles from './Editable.module.css';

function EditableRoot(props: ComponentProps<typeof EditablePrimitive.Root>) {
  const [local, others] = splitProps(props, ['activationMode', 'class']);

  return (
    <EditablePrimitive.Root
      data-slot="editable-root"
      activationMode={local.activationMode ?? 'dblclick'}
      class={clsx(styles.root, local.class)}
      {...others}
    />
  );
}

function EditableRootProvider(props: ComponentProps<typeof EditablePrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditablePrimitive.RootProvider
      data-slot="editable-root-provider"
      class={clsx(styles.root, local.class)}
      {...others}
    />
  );
}

function EditableLabel(props: ComponentProps<typeof EditablePrimitive.Label>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditablePrimitive.Label
      data-slot="editable-label"
      class={clsx(styles.label, local.class)}
      {...others}
    />
  );
}

function EditableArea(props: ComponentProps<typeof EditablePrimitive.Area>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditablePrimitive.Area
      data-slot="editable-area"
      class={clsx(styles.area, local.class)}
      {...others}
    />
  );
}

function EditableInput(props: ComponentProps<typeof EditablePrimitive.Input>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditablePrimitive.Input
      data-slot="editable-input"
      class={clsx(styles.input, local.class)}
      {...others}
    />
  );
}

function EditablePreview(props: ComponentProps<typeof EditablePrimitive.Preview>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditablePrimitive.Preview
      data-slot="editable-preview"
      class={clsx(styles.preview, local.class)}
      {...others}
    />
  );
}

function EditableControl(props: ComponentProps<typeof EditablePrimitive.Control>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditablePrimitive.Control
      data-slot="editable-control"
      class={clsx(styles.control, local.class)}
      {...others}
    />
  );
}

function EditableEditTrigger(props: ComponentProps<typeof EditablePrimitive.EditTrigger>) {
  const [local, others] = splitProps(props, ['children', 'class']);
  const resolvedChildren = children(() => local.children);

  return (
    <EditablePrimitive.EditTrigger
      data-slot="editable-edit-trigger"
      class={clsx(styles.trigger, local.class)}
      {...others}
    >
      {resolvedChildren() ?? <PencilIcon />}
    </EditablePrimitive.EditTrigger>
  );
}

function EditableSubmitTrigger(props: ComponentProps<typeof EditablePrimitive.SubmitTrigger>) {
  const [local, others] = splitProps(props, ['children', 'class']);
  const resolvedChildren = children(() => local.children);

  return (
    <EditablePrimitive.SubmitTrigger
      data-slot="editable-submit-trigger"
      class={clsx(styles.trigger, local.class)}
      {...others}
    >
      {resolvedChildren() ?? <CheckIcon />}
    </EditablePrimitive.SubmitTrigger>
  );
}

function EditableCancelTrigger(props: ComponentProps<typeof EditablePrimitive.CancelTrigger>) {
  const [local, others] = splitProps(props, ['children', 'class']);
  const resolvedChildren = children(() => local.children);

  return (
    <EditablePrimitive.CancelTrigger
      data-slot="editable-cancel-trigger"
      class={clsx(styles.trigger, local.class)}
      {...others}
    >
      {resolvedChildren() ?? <CloseIcon />}
    </EditablePrimitive.CancelTrigger>
  );
}

type EditableControlsProps = Omit<
  ComponentProps<typeof EditablePrimitive.Control>,
  'asChild' | 'children'
>;

function EditableControls(props: EditableControlsProps) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <EditableControl class={local.class} {...others}>
      <EditablePrimitive.Context>
        {(editable) => (
          <Show when={editable().editing} fallback={<EditableEditTrigger />}>
            <EditableSubmitTrigger />
            <EditableCancelTrigger />
          </Show>
        )}
      </EditablePrimitive.Context>
    </EditableControl>
  );
}

const Editable = Object.assign(EditableRoot, {
  Root: EditableRoot,
  RootProvider: EditableRootProvider,
  Label: EditableLabel,
  Area: EditableArea,
  Input: EditableInput,
  Preview: EditablePreview,
  Control: EditableControl,
  EditTrigger: EditableEditTrigger,
  SubmitTrigger: EditableSubmitTrigger,
  CancelTrigger: EditableCancelTrigger,
  Controls: EditableControls,
  Context: EditablePrimitive.Context,
});

export { Editable, useEditable, useEditableContext };

// packages/react/src/components/editable/Editable.tsx
import {
  Editable as EditablePrimitive,
  useEditable,
  useEditableContext,
} from '@ark-ui/react/editable';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef } from 'react';
import { forwardRef } from 'react';
import { CheckIcon, CloseIcon, PencilIcon } from '@/lib/moduix/icons/ui';
import { normalizeClassName } from '@/lib/moduix/normalizeClassName';
import styles from './Editable.module.css';

const EditableRoot = forwardRef<
  ComponentRef<typeof EditablePrimitive.Root>,
  ComponentProps<typeof EditablePrimitive.Root>
>(function EditableRoot({ activationMode = 'dblclick', className, ...props }, ref) {
  return (
    <EditablePrimitive.Root
      ref={ref}
      data-slot="editable-root"
      activationMode={activationMode}
      className={clsx(styles.root, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditableRootProvider = forwardRef<
  ComponentRef<typeof EditablePrimitive.RootProvider>,
  ComponentProps<typeof EditablePrimitive.RootProvider>
>(function EditableRootProvider({ className, ...props }, ref) {
  return (
    <EditablePrimitive.RootProvider
      ref={ref}
      data-slot="editable-root-provider"
      className={clsx(styles.root, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditableLabel = forwardRef<
  ComponentRef<typeof EditablePrimitive.Label>,
  ComponentProps<typeof EditablePrimitive.Label>
>(function EditableLabel({ className, ...props }, ref) {
  return (
    <EditablePrimitive.Label
      ref={ref}
      data-slot="editable-label"
      className={clsx(styles.label, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditableArea = forwardRef<
  ComponentRef<typeof EditablePrimitive.Area>,
  ComponentProps<typeof EditablePrimitive.Area>
>(function EditableArea({ className, ...props }, ref) {
  return (
    <EditablePrimitive.Area
      ref={ref}
      data-slot="editable-area"
      className={clsx(styles.area, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditableInput = forwardRef<
  ComponentRef<typeof EditablePrimitive.Input>,
  ComponentProps<typeof EditablePrimitive.Input>
>(function EditableInput({ className, ...props }, ref) {
  return (
    <EditablePrimitive.Input
      ref={ref}
      data-slot="editable-input"
      className={clsx(styles.input, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditablePreview = forwardRef<
  ComponentRef<typeof EditablePrimitive.Preview>,
  ComponentProps<typeof EditablePrimitive.Preview>
>(function EditablePreview({ className, ...props }, ref) {
  return (
    <EditablePrimitive.Preview
      ref={ref}
      data-slot="editable-preview"
      className={clsx(styles.preview, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditableControl = forwardRef<
  ComponentRef<typeof EditablePrimitive.Control>,
  ComponentProps<typeof EditablePrimitive.Control>
>(function EditableControl({ className, ...props }, ref) {
  return (
    <EditablePrimitive.Control
      ref={ref}
      data-slot="editable-control"
      className={clsx(styles.control, normalizeClassName(className))}
      {...props}
    />
  );
});

const EditableEditTrigger = forwardRef<
  ComponentRef<typeof EditablePrimitive.EditTrigger>,
  ComponentProps<typeof EditablePrimitive.EditTrigger>
>(function EditableEditTrigger({ className, children, ...props }, ref) {
  return (
    <EditablePrimitive.EditTrigger
      ref={ref}
      data-slot="editable-edit-trigger"
      className={clsx(styles.trigger, normalizeClassName(className))}
      {...props}
    >
      {children ?? <PencilIcon />}
    </EditablePrimitive.EditTrigger>
  );
});

const EditableSubmitTrigger = forwardRef<
  ComponentRef<typeof EditablePrimitive.SubmitTrigger>,
  ComponentProps<typeof EditablePrimitive.SubmitTrigger>
>(function EditableSubmitTrigger({ className, children, ...props }, ref) {
  return (
    <EditablePrimitive.SubmitTrigger
      ref={ref}
      data-slot="editable-submit-trigger"
      className={clsx(styles.trigger, normalizeClassName(className))}
      {...props}
    >
      {children ?? <CheckIcon />}
    </EditablePrimitive.SubmitTrigger>
  );
});

const EditableCancelTrigger = forwardRef<
  ComponentRef<typeof EditablePrimitive.CancelTrigger>,
  ComponentProps<typeof EditablePrimitive.CancelTrigger>
>(function EditableCancelTrigger({ className, children, ...props }, ref) {
  return (
    <EditablePrimitive.CancelTrigger
      ref={ref}
      data-slot="editable-cancel-trigger"
      className={clsx(styles.trigger, normalizeClassName(className))}
      {...props}
    >
      {children ?? <CloseIcon />}
    </EditablePrimitive.CancelTrigger>
  );
});

function EditableControls({
  className,
  ...props
}: Omit<ComponentProps<typeof EditablePrimitive.Control>, 'asChild' | 'children'>) {
  return (
    <EditableControl className={className} {...props}>
      <EditablePrimitive.Context>
        {(editable) =>
          editable.editing ? (
            <>
              <EditableSubmitTrigger />
              <EditableCancelTrigger />
            </>
          ) : (
            <EditableEditTrigger />
          )
        }
      </EditablePrimitive.Context>
    </EditableControl>
  );
}

const Editable = Object.assign(EditableRoot, {
  Root: EditableRoot,
  RootProvider: EditableRootProvider,
  Label: EditableLabel,
  Area: EditableArea,
  Input: EditableInput,
  Preview: EditablePreview,
  Control: EditableControl,
  EditTrigger: EditableEditTrigger,
  SubmitTrigger: EditableSubmitTrigger,
  CancelTrigger: EditableCancelTrigger,
  Controls: EditableControls,
  Context: EditablePrimitive.Context,
});

export { Editable, useEditable, useEditableContext };
