// packages/ui/src/components/container/Container.tsx
import type { HTMLArkProps } from '@ark-ui/react/factory';
import { ark } from '@ark-ui/react/factory';
import { clsx } from 'clsx';
import { forwardRef } from 'react';
import { normalizeClassName } from '@/lib/moduix/normalizeClassName';
import styles from './Container.module.css';

export type ContainerSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
export type ContainerGutter = 'none' | 'sm' | 'md' | 'lg';

export type ContainerRootProps = HTMLArkProps<'div'> & {
  size?: ContainerSize;
  gutter?: ContainerGutter;
};

const ContainerRoot = forwardRef<HTMLDivElement, ContainerRootProps>(function ContainerRoot(
  { size = 'lg', gutter = 'md', className, ...props },
  ref,
) {
  return (
    <ark.div
      ref={ref}
      data-scope="container"
      data-part="root"
      data-slot="container-root"
      data-size={size}
      data-gutter={gutter}
      className={clsx(styles.root, normalizeClassName(className))}
      {...props}
    />
  );
});

const Container = Object.assign(ContainerRoot, {
  Root: ContainerRoot,
});

export { Container };

// packages/solid/src/components/container/Container.tsx
import type { HTMLArkProps } from '@ark-ui/solid/factory';
import { ark } from '@ark-ui/solid/factory';
import { clsx } from 'clsx';
import { splitProps } from 'solid-js';
import styles from './Container.module.css';

type ContainerSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
type ContainerGutter = 'none' | 'sm' | 'md' | 'lg';

type ContainerRootProps = HTMLArkProps<'div'> & {
  size?: ContainerSize;
  gutter?: ContainerGutter;
  'data-scope'?: string;
  'data-part'?: string;
  'data-slot'?: string;
  'data-size'?: string;
  'data-gutter'?: string;
};

function ContainerRoot(props: ContainerRootProps) {
  const [local, others] = splitProps(props, [
    'asChild',
    'class',
    'gutter',
    'size',
    'data-scope',
    'data-part',
    'data-slot',
    'data-size',
    'data-gutter',
  ]);

  return (
    <ark.div
      asChild={local.asChild}
      {...others}
      data-scope="container"
      data-part="root"
      data-slot="container-root"
      data-size={local.size ?? 'lg'}
      data-gutter={local.gutter ?? 'md'}
      class={clsx(styles.root, local.class)}
    />
  );
}

const Container = Object.assign(ContainerRoot, {
  Root: ContainerRoot,
});

export { Container };
