// packages/solid/src/components/chart/Chart.tsx
import { ark, type HTMLArkProps } from '@ark-ui/solid/factory';
import type {
  ChartRenderer,
  ChartRendererHostOptions,
  ChartTooltipBodyContext,
  ChartTooltipBodyTarget,
  ChartValue,
} from '@tanstack/charts';
import { createChartRendererAdapter } from '@tanstack/charts/adapter/renderer';
import { motion as createMotionRenderer } from '@tanstack/charts/motion';
import { svgChartRenderer } from '@tanstack/charts/svg/renderer';
import { clsx } from 'clsx';
import {
  For,
  Show,
  createEffect,
  createMemo,
  createSignal,
  createUniqueId,
  onCleanup,
  onMount,
  splitProps,
  type Accessor,
  type JSX,
} from 'solid-js';
import { Portal } from 'solid-js/web';
import styles from './Chart.module.css';

const defaultChartRenderer = createMotionRenderer<unknown, ChartValue, ChartValue>({
  transition: {
    type: 'spring',
    stiffness: 260,
    damping: 30,
    mass: 0.8,
  },
});

type ChartTooltipContent = ChartTooltipBodyContext['content'];
type ChartTooltipObjectContent = Exclude<ChartTooltipContent, string>;

type ChartTooltipBodyRenderContext<
  TDatum = unknown,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
> = ChartTooltipBodyContext<TDatum, TXValue, TYValue> & {
  defaultBody: JSX.Element;
};

type ChartTooltipBodyRenderProps<
  TDatum = unknown,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
> = {
  renderTooltipBody?: (
    context: ChartTooltipBodyRenderContext<TDatum, TXValue, TYValue>,
  ) => JSX.Element;
};

type ChartPlotProps<
  TDatum,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
> = Omit<ChartRendererHostOptions<TDatum, TXValue, TYValue>, 'onTooltipBodyChange' | 'renderer'> &
  ChartTooltipBodyRenderProps<TDatum, TXValue, TYValue> & {
    class?: string;
    style?: JSX.CSSProperties;
    motion?: boolean;
    renderer?: ChartRenderer<NoInfer<TDatum>, NoInfer<TXValue>, NoInfer<TYValue>>;
  };

function Chart(props: HTMLArkProps<'figure'>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <ark.figure
      asChild={local.asChild}
      {...others}
      data-scope="chart"
      data-part="root"
      data-slot="chart-root"
      class={clsx(styles.root, local.class)}
    />
  );
}

function ModuixTooltipObjectContent(props: { content: Accessor<ChartTooltipObjectContent> }) {
  return (
    <div data-slot="chart-tooltip-body" class={styles.defaultTooltipContent}>
      <Show when={props.content().title}>
        <div data-slot="chart-tooltip-title" class={styles.tooltipTitle}>
          <Show when={props.content().color}>
            <span
              aria-hidden="true"
              data-slot="chart-tooltip-swatch"
              class={styles.tooltipSwatch}
              style={{ 'background-color': props.content().color }}
            />
          </Show>
          {props.content().title}
        </div>
      </Show>
      <Show when={props.content().rows.length}>
        <div data-slot="chart-tooltip-rows" class={styles.tooltipRows}>
          <For each={props.content().rows}>
            {(row) => (
              <div
                data-has-swatch={row.color ? '' : undefined}
                data-slot="chart-tooltip-row"
                class={styles.tooltipRow}
              >
                <Show when={row.color}>
                  <span
                    aria-hidden="true"
                    data-slot="chart-tooltip-swatch"
                    class={styles.tooltipSwatch}
                    style={{ 'background-color': row.color }}
                  />
                </Show>
                <span data-slot="chart-tooltip-label" class={styles.tooltipLabel}>
                  {row.label}
                </span>
                <span data-slot="chart-tooltip-value" class={styles.tooltipValue}>
                  {row.value}
                </span>
              </div>
            )}
          </For>
        </div>
      </Show>
    </div>
  );
}

function ModuixTooltipBody(props: { content: Accessor<ChartTooltipContent> }) {
  return (
    <>
      <Show when={typeof props.content() === 'string'}>
        <span data-slot="chart-tooltip-text">{props.content() as string}</span>
      </Show>
      <Show when={typeof props.content() !== 'string'}>
        <ModuixTooltipObjectContent content={() => props.content() as ChartTooltipObjectContent} />
      </Show>
    </>
  );
}

function ChartTooltipBody<TDatum, TXValue extends ChartValue, TYValue extends ChartValue>(props: {
  render: (context: ChartTooltipBodyRenderContext<TDatum, TXValue, TYValue>) => JSX.Element;
  target: Accessor<ChartTooltipBodyTarget<TDatum, TXValue, TYValue>>;
}) {
  const context: ChartTooltipBodyRenderContext<TDatum, TXValue, TYValue> = {
    get points() {
      return props.target().points;
    },
    get content() {
      return props.target().content;
    },
    defaultBody: <ModuixTooltipBody content={() => props.target().content} />,
    get pinned() {
      return props.target().pinned;
    },
    get dismiss() {
      return props.target().dismiss;
    },
  };

  return <Portal mount={props.target().element}>{props.render(context)}</Portal>;
}

const renderDefaultTooltipBody = <
  TDatum,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
>(
  context: ChartTooltipBodyRenderContext<TDatum, TXValue, TYValue>,
) => <ModuixTooltipBody content={() => context.content} />;

function ChartPrimitive<
  TDatum,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
>(props: ChartPlotProps<TDatum, TXValue, TYValue>) {
  const generatedId = `ts-chart-${createUniqueId().replaceAll(/[^a-zA-Z0-9_-]/g, '')}`;
  const resolvedRenderer = createMemo(
    () =>
      (props.renderer ??
        (props.motion === false ? svgChartRenderer : defaultChartRenderer)) as ChartRenderer<
        TDatum,
        TXValue,
        TYValue
      >,
  );
  const [tooltipTarget, setTooltipTarget] = createSignal<ChartTooltipBodyTarget<
    TDatum,
    TXValue,
    TYValue
  > | null>(null);

  const getOptions = () => {
    const [local, others] = splitProps(props, [
      'class',
      'motion',
      'renderTooltipBody',
      'renderer',
      'style',
    ]);

    return {
      ...others,
      idPrefix: props.idPrefix ?? generatedId,
      renderer: resolvedRenderer(),
      onTooltipBodyChange: local.renderTooltipBody ? setTooltipTarget : undefined,
    };
  };

  const adapter = createChartRendererAdapter(getOptions());
  const initialMarkup = adapter.prerender();
  let surface!: HTMLDivElement;

  createEffect(() => adapter.update(getOptions()));
  onMount(() => adapter.mount(surface));
  onCleanup(() => adapter.destroy());

  return (
    <>
      <div
        class={clsx('ts-chart-host', props.class)}
        style={{
          position: 'relative',
          width: props.width === undefined ? '100%' : `${props.width}px`,
          height:
            props.height === undefined
              ? typeof props.aspectRatio === 'number' &&
                Number.isFinite(props.aspectRatio) &&
                props.aspectRatio > 0
                ? undefined
                : '320px'
              : `${props.height}px`,
          'aspect-ratio':
            props.height === undefined &&
            typeof props.aspectRatio === 'number' &&
            Number.isFinite(props.aspectRatio) &&
            props.aspectRatio > 0
              ? props.aspectRatio.toString()
              : undefined,
          ...props.style,
        }}
      >
        <div
          ref={(element) => (surface = element)}
          class="ts-chart-surface"
          style={{ width: '100%', height: '100%' }}
          innerHTML={initialMarkup}
        />
      </div>
      <Show when={props.renderTooltipBody} keyed>
        {(render) => (
          <Show when={tooltipTarget()} keyed>
            {(target) => <ChartTooltipBody render={render} target={() => target} />}
          </Show>
        )}
      </Show>
    </>
  );
}

function ChartPlot<
  TDatum,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
>(props: ChartPlotProps<TDatum, TXValue, TYValue>) {
  const [local, others] = splitProps(props, [
    'class',
    'motion',
    'renderTooltipBody',
    'renderer',
    'style',
  ]);

  return (
    <ChartPrimitive
      {...others}
      class={clsx(styles.plot, local.class)}
      motion={local.motion}
      renderTooltipBody={local.renderTooltipBody ?? renderDefaultTooltipBody}
      renderer={local.renderer}
      style={local.style}
    />
  );
}

function ChartHeader(props: HTMLArkProps<'figcaption'>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <ark.figcaption
      asChild={local.asChild}
      {...others}
      data-scope="chart"
      data-part="header"
      data-slot="chart-header"
      class={clsx(styles.header, local.class)}
    />
  );
}

function ChartTitle(props: HTMLArkProps<'h3'>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <ark.h3
      asChild={local.asChild}
      {...others}
      data-scope="chart"
      data-part="title"
      data-slot="chart-title"
      class={clsx(styles.title, local.class)}
    />
  );
}

function ChartDescription(props: HTMLArkProps<'p'>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <ark.p
      asChild={local.asChild}
      {...others}
      data-scope="chart"
      data-part="description"
      data-slot="chart-description"
      class={clsx(styles.description, local.class)}
    />
  );
}

function ChartLegend(props: HTMLArkProps<'ul'>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <ark.ul
      asChild={local.asChild}
      {...others}
      data-scope="chart"
      data-part="legend"
      data-slot="chart-legend"
      class={clsx(styles.legend, local.class)}
    />
  );
}

function ChartLegendItem(props: HTMLArkProps<'li'> & { color?: string }) {
  const [local, others] = splitProps(props, ['asChild', 'class', 'color', 'style']);

  return (
    <ark.li
      asChild={local.asChild}
      {...others}
      data-scope="chart"
      data-part="legend-item"
      data-slot="chart-legend-item"
      class={clsx(styles.legendItem, local.class)}
      style={
        local.color
          ? ({
              '--moduix-chart-legend-indicator-color': local.color,
              ...(typeof local.style === 'object' && local.style ? local.style : {}),
            } as JSX.CSSProperties)
          : local.style
      }
    />
  );
}

export {
  Chart,
  ChartDescription,
  ChartHeader,
  ChartLegend,
  ChartLegendItem,
  ChartPlot,
  ChartTitle,
};

// packages/react/src/components/chart/Chart.tsx
'use client';

import { ark, type HTMLArkProps } from '@ark-ui/react/factory';
import type { ChartValue } from '@tanstack/charts';
import { motion as createMotionRenderer } from '@tanstack/charts/motion';
import { RendererChart as ChartPrimitive } from '@tanstack/charts/react/tooltip';
import type {
  ChartTooltipBodyRenderContext,
  RendererChartProps,
} from '@tanstack/charts/react/tooltip';
import { svgChartRenderer } from '@tanstack/charts/svg/renderer';
import { clsx } from 'clsx';
import type { CSSProperties } from 'react';
import { forwardRef } from 'react';
import styles from './Chart.module.css';

const defaultChartRenderer = createMotionRenderer({
  transition: {
    type: 'spring',
    stiffness: 260,
    damping: 30,
    mass: 0.8,
  },
});

const ChartRoot = forwardRef<HTMLElement, HTMLArkProps<'figure'>>(function ChartRoot(
  { className, ...props },
  ref,
) {
  return (
    <ark.figure
      ref={ref}
      data-scope="chart"
      data-part="root"
      className={clsx(styles.root, className)}
      {...props}
      data-slot="chart-root"
    />
  );
});

const renderDefaultTooltipBody = ({ content }: ChartTooltipBodyRenderContext) => {
  if (typeof content === 'string') {
    return <span data-slot="chart-tooltip-text">{content}</span>;
  }

  return (
    <div data-slot="chart-tooltip-body" className={styles.defaultTooltipContent}>
      {content.title ? (
        <div data-slot="chart-tooltip-title" className={styles.tooltipTitle}>
          {content.color ? (
            <span
              aria-hidden="true"
              data-slot="chart-tooltip-swatch"
              className={styles.tooltipSwatch}
              style={{ backgroundColor: content.color }}
            />
          ) : null}
          {content.title}
        </div>
      ) : null}
      {content.rows.length ? (
        <div data-slot="chart-tooltip-rows" className={styles.tooltipRows}>
          {content.rows.map((row, index) => (
            <div
              key={`${row.label}-${index}`}
              data-has-swatch={row.color ? '' : undefined}
              data-slot="chart-tooltip-row"
              className={styles.tooltipRow}
            >
              {row.color ? (
                <span
                  aria-hidden="true"
                  data-slot="chart-tooltip-swatch"
                  className={styles.tooltipSwatch}
                  style={{ backgroundColor: row.color }}
                />
              ) : null}
              <span data-slot="chart-tooltip-label" className={styles.tooltipLabel}>
                {row.label}
              </span>
              <span data-slot="chart-tooltip-value" className={styles.tooltipValue}>
                {row.value}
              </span>
            </div>
          ))}
        </div>
      ) : null}
    </div>
  );
};

const ChartPlot = function ChartPlot<
  TDatum,
  TXValue extends ChartValue = ChartValue,
  TYValue extends ChartValue = ChartValue,
>({
  className,
  motion = true,
  renderTooltipBody,
  renderer,
  ...props
}: Omit<RendererChartProps<TDatum, TXValue, TYValue>, 'renderer'> & {
  motion?: boolean;
  renderer?: RendererChartProps<TDatum, TXValue, TYValue>['renderer'];
}) {
  return (
    <ChartPrimitive
      {...props}
      renderer={renderer ?? (motion ? defaultChartRenderer : svgChartRenderer)}
      renderTooltipBody={renderTooltipBody ?? renderDefaultTooltipBody}
      className={clsx(styles.plot, className)}
    />
  );
};

const ChartHeader = forwardRef<HTMLElement, HTMLArkProps<'figcaption'>>(function ChartHeader(
  { className, ...props },
  ref,
) {
  return (
    <ark.figcaption
      ref={ref}
      data-scope="chart"
      data-part="header"
      className={clsx(styles.header, className)}
      {...props}
      data-slot="chart-header"
    />
  );
});

const ChartTitle = forwardRef<HTMLHeadingElement, HTMLArkProps<'h3'>>(function ChartTitle(
  { className, ...props },
  ref,
) {
  return (
    <ark.h3
      ref={ref}
      data-scope="chart"
      data-part="title"
      className={clsx(styles.title, className)}
      {...props}
      data-slot="chart-title"
    />
  );
});

const ChartDescription = forwardRef<HTMLParagraphElement, HTMLArkProps<'p'>>(
  function ChartDescription({ className, ...props }, ref) {
    return (
      <ark.p
        ref={ref}
        data-scope="chart"
        data-part="description"
        className={clsx(styles.description, className)}
        {...props}
        data-slot="chart-description"
      />
    );
  },
);

const ChartLegend = forwardRef<HTMLUListElement, HTMLArkProps<'ul'>>(function ChartLegend(
  { className, ...props },
  ref,
) {
  return (
    <ark.ul
      ref={ref}
      data-scope="chart"
      data-part="legend"
      className={clsx(styles.legend, className)}
      {...props}
      data-slot="chart-legend"
    />
  );
});

const ChartLegendItem = forwardRef<
  HTMLLIElement,
  HTMLArkProps<'li'> & {
    color?: string;
  }
>(function ChartLegendItem({ className, color, style, ...props }, ref) {
  return (
    <ark.li
      ref={ref}
      data-scope="chart"
      data-part="legend-item"
      className={clsx(styles.legendItem, className)}
      style={
        color
          ? ({ '--moduix-chart-legend-indicator-color': color, ...style } as CSSProperties)
          : style
      }
      {...props}
      data-slot="chart-legend-item"
    />
  );
});

const Chart = Object.assign(ChartRoot, {
  Root: ChartRoot,
  Plot: ChartPlot,
  Header: ChartHeader,
  Title: ChartTitle,
  Description: ChartDescription,
  Legend: ChartLegend,
  LegendItem: ChartLegendItem,
});

export { Chart };
