// apps/docs/docs/en/docs/_snippets/spinner/custom-indicator.tsx
import { Spinner } from '@moduix/react';

export default function SpinnerCustomIndicatorDemo() {
  return (
    <Spinner size="lg" aria-label="Syncing">
      <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path
          d="M12 3v4M12 17v4M3 12h4M17 12h4M5.64 5.64l2.83 2.83M15.53 15.53l2.83 2.83M18.36 5.64l-2.83 2.83M8.47 15.53l-2.83 2.83"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
        />
      </svg>
    </Spinner>
  );
}

// website/snippets/spinner/vue/custom-indicator.vue
<script setup lang="ts">
import { Spinner } from '@moduix/vue/spinner';
</script>

<template>
  <Spinner size="lg" aria-label="Syncing">
    <svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M12 3v4M12 17v4M3 12h4M17 12h4M5.64 5.64l2.83 2.83M15.53 15.53l2.83 2.83M18.36 5.64l-2.83 2.83M8.47 15.53l-2.83 2.83"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
      />
    </svg>
  </Spinner>
</template>
