// packages/solid-tailwind/src/components/image/Image.tsx
import type { UnpicImageProps, UnpicSourceProps } from '@unpic/core';
import { transformProps, transformSourceProps } from '@unpic/core';
import { createMemo, splitProps } from 'solid-js';
import type { JSX } from 'solid-js';
import { cn } from '@/lib/moduix/cn';

type ImageProps = Omit<
  UnpicImageProps<JSX.ImgHTMLAttributes<HTMLImageElement>>,
  'fetchpriority'
> & {
  fetchpriority?: JSX.ImgHTMLAttributes<HTMLImageElement>['fetchpriority'];
  style?: JSX.ImgHTMLAttributes<HTMLImageElement>['style'];
};

type ImageTransformProps = UnpicImageProps<JSX.ImgHTMLAttributes<HTMLImageElement>> & {
  style?: JSX.ImgHTMLAttributes<HTMLImageElement>['style'];
};

type ImageSourceProps = UnpicSourceProps &
  Omit<
    JSX.SourceHTMLAttributes<HTMLSourceElement>,
    'height' | 'media' | 'sizes' | 'src' | 'srcset' | 'type' | 'width'
  >;

function Image(props: ImageProps) {
  const [local, others] = splitProps(props, ['class', 'fetchpriority']);
  const imageProps = createMemo(() => {
    return transformProps<JSX.ImgHTMLAttributes<HTMLImageElement>>({
      ...others,
      loading: others.loading ?? (others.priority ? 'eager' : 'lazy'),
      decoding: others.decoding ?? (others.priority ? undefined : 'async'),
      fetchpriority: local.fetchpriority ?? (others.priority ? 'high' : undefined),
    } as ImageTransformProps);
  });

  return <img {...imageProps()} data-slot="image-root" class={cn('rounded-md', local.class)} />;
}

function ImageSource(props: ImageSourceProps) {
  const [local, others] = splitProps(props, ['class']);
  const sourceProps = createMemo(() =>
    transformSourceProps<JSX.SourceHTMLAttributes<HTMLSourceElement>>({ ...others }),
  );

  return <source {...sourceProps()} data-slot="image-source" class={local.class} />;
}

export { Image, ImageSource };

// packages/vue-tailwind/src/components/image/Image.vue
<script setup lang="ts">
import type { UnpicImageProps } from '@unpic/core';
import { transformProps } from '@unpic/core';
import { ref, useAttrs } from 'vue';
import type { HTMLAttributes, ImgHTMLAttributes } from 'vue';
import { cn } from '@/lib/moduix/cn';

type ImageTransformProps = UnpicImageProps<ImgHTMLAttributes> & {
  style?: ImgHTMLAttributes['style'];
};

export interface Props
  extends /* @vue-ignore */ Omit<UnpicImageProps<ImgHTMLAttributes>, 'fetchpriority'> {
  class?: HTMLAttributes['class'];
  fetchpriority?: ImgHTMLAttributes['fetchpriority'];
  style?: ImgHTMLAttributes['style'];
}

defineOptions({ inheritAttrs: false });

const props = defineProps<Props>();
const attrs = useAttrs();
const imageElement = ref<HTMLImageElement>();

defineExpose({ $el: imageElement });

const getImageProps = () => {
  const { class: _class, ...inputProps } = { ...attrs, ...props };
  const input = inputProps as ImageTransformProps;
  return transformProps<ImgHTMLAttributes>({
    ...input,
    loading: input.loading ?? (input.priority ? 'eager' : 'lazy'),
    decoding: input.decoding ?? (input.priority ? undefined : 'async'),
    fetchpriority: input.fetchpriority ?? (input.priority ? 'high' : undefined),
  });
};
</script>

<template>
  <img
    ref="imageElement"
    v-bind="getImageProps()"
    :class="cn('rounded-md', props.class)"
    data-slot="image-root"
  />
</template>
