// packages/solid/src/components/lightbox/Lightbox.tsx
import { Dialog as DialogPrimitive, useDialog, useDialogContext } from '@ark-ui/solid/dialog';
import type { HTMLArkProps } from '@ark-ui/solid/factory';
import { ark } from '@ark-ui/solid/factory';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { children, createEffect, onCleanup, splitProps } from 'solid-js';
import {
  OverlayPortal,
  OverlayPortalProvider,
  type OverlayPortalProps,
} from '@/lib/moduix/overlayPortal';
import { CloseButton } from '../close-button';
import styles from './Lightbox.module.css';

const DEFAULT_CLOSE_LABEL = 'Close image';

type LightboxImageSelectDetails = {
  alt?: string;
  element: HTMLImageElement;
  src: string;
};

type LightboxImageProps = ComponentProps<'img'> & {
  closeOnClick?: boolean;
};

type LightboxRootProps = ComponentProps<typeof DialogPrimitive.Root> & OverlayPortalProps;
type LightboxRootProviderProps = ComponentProps<typeof DialogPrimitive.RootProvider> &
  OverlayPortalProps;

type LightboxBindProps = {
  onImageSelect: (details: LightboxImageSelectDetails) => void;
  selector: string;
  rootRef?: HTMLElement | (() => HTMLElement | null | undefined);
  rootSelector?: string;
};

function preloadImage(src?: string) {
  if (!src || typeof Image === 'undefined') {
    return;
  }

  const image = new Image();
  image.src = src;
}

function resolveImage(
  target: EventTarget | null,
  selector: string,
  rootNode: HTMLElement,
): LightboxImageSelectDetails | null {
  if (!(target instanceof Element)) {
    return null;
  }

  const matchedNode = target.closest(selector);
  if (!matchedNode || !rootNode.contains(matchedNode)) {
    return null;
  }

  const imageNode =
    matchedNode instanceof HTMLImageElement ? matchedNode : matchedNode.querySelector('img');
  if (!(imageNode instanceof HTMLImageElement)) {
    return null;
  }

  const src = imageNode.dataset.lightboxSrc ?? imageNode.currentSrc ?? imageNode.src;
  if (!src) {
    return null;
  }

  return {
    src,
    alt: imageNode.alt || undefined,
    element: imageNode,
  };
}

function resolveRootNode(
  rootRef: LightboxBindProps['rootRef'],
  rootSelector: string | undefined,
): HTMLElement | null {
  const rootNode = typeof rootRef === 'function' ? rootRef() : rootRef;
  return rootNode ?? (rootSelector ? document.querySelector<HTMLElement>(rootSelector) : null);
}

function LightboxRoot(props: LightboxRootProps) {
  const [local, others] = splitProps(props, [
    'children',
    'lazyMount',
    'portalled',
    'portalRef',
    'unmountOnExit',
  ]);

  return (
    <OverlayPortalProvider portalled={local.portalled} portalRef={local.portalRef}>
      <DialogPrimitive.Root
        lazyMount={local.lazyMount ?? true}
        unmountOnExit={local.unmountOnExit ?? true}
        {...others}
      >
        {local.children}
      </DialogPrimitive.Root>
    </OverlayPortalProvider>
  );
}

function LightboxRootProvider(props: LightboxRootProviderProps) {
  const [local, others] = splitProps(props, [
    'children',
    'lazyMount',
    'portalled',
    'portalRef',
    'unmountOnExit',
  ]);

  return (
    <OverlayPortalProvider portalled={local.portalled} portalRef={local.portalRef}>
      <DialogPrimitive.RootProvider
        lazyMount={local.lazyMount ?? true}
        unmountOnExit={local.unmountOnExit ?? true}
        {...others}
      >
        {local.children}
      </DialogPrimitive.RootProvider>
    </OverlayPortalProvider>
  );
}

function LightboxTrigger(props: ComponentProps<typeof DialogPrimitive.Trigger>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <DialogPrimitive.Trigger
      asChild={local.asChild}
      data-slot="lightbox-trigger"
      class={clsx(styles.trigger, local.class)}
      {...others}
    />
  );
}

function LightboxBackdrop(props: ComponentProps<typeof DialogPrimitive.Backdrop>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <OverlayPortal>
      <DialogPrimitive.Backdrop
        data-slot="lightbox-backdrop"
        class={clsx(styles.backdrop, local.class)}
        {...others}
      />
    </OverlayPortal>
  );
}

function LightboxPositioner(props: ComponentProps<typeof DialogPrimitive.Positioner>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <OverlayPortal>
      <DialogPrimitive.Positioner
        data-slot="lightbox-positioner"
        class={clsx(styles.positioner, local.class)}
        {...others}
      />
    </OverlayPortal>
  );
}

function LightboxContent(props: ComponentProps<typeof DialogPrimitive.Content>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DialogPrimitive.Content
      data-slot="lightbox-content"
      class={clsx(styles.content, local.class)}
      {...others}
    />
  );
}

function LightboxTitle(props: ComponentProps<typeof DialogPrimitive.Title>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DialogPrimitive.Title
      data-slot="lightbox-title"
      class={clsx(styles.title, local.class)}
      {...others}
    />
  );
}

function LightboxDescription(props: ComponentProps<typeof DialogPrimitive.Description>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DialogPrimitive.Description
      data-slot="lightbox-description"
      class={clsx(styles.description, local.class)}
      {...others}
    />
  );
}

function LightboxCloseTrigger(props: ComponentProps<typeof DialogPrimitive.CloseTrigger>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <DialogPrimitive.CloseTrigger
      asChild={local.asChild}
      data-slot="lightbox-close-trigger"
      class={local.class}
      {...others}
    />
  );
}

type LightboxCloseIconProps = Omit<ComponentProps<typeof DialogPrimitive.CloseTrigger>, 'asChild'>;

function LightboxCloseIcon(props: LightboxCloseIconProps) {
  const [local, others] = splitProps(props, ['aria-label', 'aria-labelledby', 'children', 'class']);
  const dialog = useDialogContext();
  const resolvedChildren = children(() => local.children);

  return (
    <DialogPrimitive.CloseTrigger
      asChild={(triggerProps) => (
        <CloseButton.Root
          {...triggerProps()}
          data-slot="lightbox-close-icon"
          data-state={dialog().open ? 'open' : 'closed'}
          aria-label={local['aria-label'] ?? DEFAULT_CLOSE_LABEL}
          aria-labelledby={local['aria-labelledby']}
          class={clsx(styles.closeIcon, local.class)}
        >
          {resolvedChildren()}
        </CloseButton.Root>
      )}
      {...others}
    />
  );
}

function LightboxImage(props: LightboxImageProps) {
  const [local, others] = splitProps(props, ['class', 'closeOnClick', 'onClick']);
  const dialog = useDialogContext();

  const handleClick = (event: MouseEvent) => {
    (local.onClick as ((event: MouseEvent) => void) | undefined)?.(event);

    if (local.closeOnClick && !event.defaultPrevented) {
      dialog().setOpen(false);
    }
  };

  return (
    <img
      data-slot="lightbox-image"
      data-close-on-click={local.closeOnClick ? '' : undefined}
      class={clsx(styles.image, local.class)}
      onClick={handleClick}
      {...others}
    />
  );
}

function LightboxGallery(props: HTMLArkProps<'div'>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <ark.div data-slot="lightbox-gallery" class={clsx(styles.gallery, local.class)} {...others} />
  );
}

function LightboxHeader(props: HTMLArkProps<'div'>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <ark.div data-slot="lightbox-header" class={clsx(styles.header, local.class)} {...others} />
  );
}

function LightboxBody(props: HTMLArkProps<'div'>) {
  const [local, others] = splitProps(props, ['class']);

  return <ark.div data-slot="lightbox-body" class={clsx(styles.body, local.class)} {...others} />;
}

function LightboxFooter(props: HTMLArkProps<'div'>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <ark.div data-slot="lightbox-footer" class={clsx(styles.footer, local.class)} {...others} />
  );
}

function LightboxBind(props: LightboxBindProps) {
  const [local] = splitProps(props, ['onImageSelect', 'rootRef', 'rootSelector', 'selector']);
  const dialog = useDialogContext();

  createEffect(() => {
    const rootNode = resolveRootNode(local.rootRef, local.rootSelector);
    const selector = local.selector;
    const onImageSelect = local.onImageSelect;

    if (!rootNode) {
      return;
    }

    const handleClick = (event: MouseEvent) => {
      const nextImage = resolveImage(event.target, selector, rootNode);
      if (!nextImage) {
        return;
      }

      onImageSelect(nextImage);
      dialog().setOpen(true);
    };

    const preloadFromTarget = (target: EventTarget | null) => {
      const nextImage = resolveImage(target, selector, rootNode);
      if (!nextImage) {
        return;
      }

      preloadImage(nextImage.src);
    };

    const handlePointerEnter = (event: PointerEvent) => {
      preloadFromTarget(event.target);
    };

    const handleFocusIn = (event: FocusEvent) => {
      preloadFromTarget(event.target);
    };

    rootNode.addEventListener('click', handleClick);
    rootNode.addEventListener('pointerenter', handlePointerEnter, true);
    rootNode.addEventListener('focusin', handleFocusIn);

    onCleanup(() => {
      rootNode.removeEventListener('click', handleClick);
      rootNode.removeEventListener('pointerenter', handlePointerEnter, true);
      rootNode.removeEventListener('focusin', handleFocusIn);
    });
  });

  return <></>;
}

type LightboxComponent = typeof LightboxRoot & {
  Root: typeof LightboxRoot;
  RootProvider: typeof LightboxRootProvider;
  Trigger: typeof LightboxTrigger;
  Backdrop: typeof LightboxBackdrop;
  Positioner: typeof LightboxPositioner;
  Content: typeof LightboxContent;
  Title: typeof LightboxTitle;
  Description: typeof LightboxDescription;
  CloseTrigger: typeof LightboxCloseTrigger;
  CloseIcon: typeof LightboxCloseIcon;
  Header: typeof LightboxHeader;
  Body: typeof LightboxBody;
  Footer: typeof LightboxFooter;
  Image: typeof LightboxImage;
  Gallery: typeof LightboxGallery;
  Bind: typeof LightboxBind;
  useLightbox: typeof useDialog;
  useLightboxContext: typeof useDialogContext;
};

const Lightbox: LightboxComponent = Object.assign(LightboxRoot, {
  Root: LightboxRoot,
  RootProvider: LightboxRootProvider,
  Trigger: LightboxTrigger,
  Backdrop: LightboxBackdrop,
  Positioner: LightboxPositioner,
  Content: LightboxContent,
  Title: LightboxTitle,
  Description: LightboxDescription,
  CloseTrigger: LightboxCloseTrigger,
  CloseIcon: LightboxCloseIcon,
  Header: LightboxHeader,
  Body: LightboxBody,
  Footer: LightboxFooter,
  Image: LightboxImage,
  Gallery: LightboxGallery,
  Bind: LightboxBind,
  useLightbox: useDialog,
  useLightboxContext: useDialogContext,
});

export {
  Lightbox,
  LightboxBind,
  LightboxGallery,
  LightboxImage,
  useDialog as useLightbox,
  useDialogContext as useLightboxContext,
};
export type { LightboxBindProps, LightboxImageSelectDetails };

// packages/ui/src/components/lightbox/Lightbox.tsx
import type { ComponentProps, ComponentRef, RefObject } from 'react';
import { Dialog as DialogPrimitive, useDialog, useDialogContext } from '@ark-ui/react/dialog';
import { Portal as PortalPrimitive } from '@ark-ui/react/portal';
import { clsx } from 'clsx';
import { forwardRef, useEffect, useState } from 'react';
import { normalizeClassName } from '@/lib/moduix/normalizeClassName';
import { CloseButton } from '../close-button';
import styles from './Lightbox.module.css';

const DEFAULT_CLOSE_LABEL = 'Close image';
const DEFAULT_PREVIEW_LABEL = 'Image preview';

type LightboxImageData = {
  alt?: string;
  src: string;
};

type LightboxFrameProps = ComponentProps<'div'> & {
  closeOnClick?: boolean;
};

type LightboxGalleryProps = {
  selector?: string;
  rootRef?: RefObject<HTMLElement | null>;
  rootSelector?: string;
  closeOnClick?: boolean;
  className?: ComponentProps<typeof DialogPrimitive.Content>['className'];
  closeLabel?: string;
};

const preloadedImageSources = new Set<string>();

function preloadImage(src?: string) {
  if (!src || typeof Image === 'undefined' || preloadedImageSources.has(src)) {
    return;
  }

  preloadedImageSources.add(src);
  const image = new Image();
  image.src = src;
}

function getGalleryImage(target: EventTarget | null, selector: string): LightboxImageData | null {
  if (!(target instanceof Element)) {
    return null;
  }

  const matchedNode = target.closest(selector);
  if (!matchedNode) {
    return null;
  }

  const imageNode =
    matchedNode instanceof HTMLImageElement ? matchedNode : matchedNode.querySelector('img');
  if (!(imageNode instanceof HTMLImageElement)) {
    return null;
  }

  const source = imageNode.dataset.lightboxSrc ?? imageNode.currentSrc ?? imageNode.src;
  if (!source) {
    return null;
  }

  return {
    src: source,
    alt: imageNode.alt || undefined,
  };
}

function LightboxRoot(props: ComponentProps<typeof DialogPrimitive.Root>) {
  return <DialogPrimitive.Root {...props} />;
}

function LightboxRootProvider(props: ComponentProps<typeof DialogPrimitive.RootProvider>) {
  return <DialogPrimitive.RootProvider {...props} />;
}

const LightboxTrigger = forwardRef<
  ComponentRef<typeof DialogPrimitive.Trigger>,
  ComponentProps<typeof DialogPrimitive.Trigger>
>(function LightboxTrigger({ className, ...props }, ref) {
  return (
    <DialogPrimitive.Trigger
      ref={ref}
      data-slot="lightbox-trigger"
      className={clsx(styles.trigger, normalizeClassName(className))}
      {...props}
    />
  );
});

const LightboxBackdrop = forwardRef<
  ComponentRef<typeof DialogPrimitive.Backdrop>,
  ComponentProps<typeof DialogPrimitive.Backdrop>
>(function LightboxBackdrop({ className, ...props }, ref) {
  return (
    <DialogPrimitive.Backdrop
      ref={ref}
      data-slot="lightbox-backdrop"
      className={clsx(styles.backdrop, normalizeClassName(className))}
      {...props}
    />
  );
});

const LightboxPositioner = forwardRef<
  ComponentRef<typeof DialogPrimitive.Positioner>,
  ComponentProps<typeof DialogPrimitive.Positioner>
>(function LightboxPositioner({ className, ...props }, ref) {
  return (
    <DialogPrimitive.Positioner
      ref={ref}
      data-slot="lightbox-positioner"
      className={clsx(styles.positioner, normalizeClassName(className))}
      {...props}
    />
  );
});

const LightboxContent = forwardRef<
  ComponentRef<typeof DialogPrimitive.Content>,
  ComponentProps<typeof DialogPrimitive.Content>
>(function LightboxContent({ className, ...props }, ref) {
  return (
    <DialogPrimitive.Content
      ref={ref}
      data-slot="lightbox-content"
      className={clsx(styles.content, normalizeClassName(className))}
      {...props}
    />
  );
});

const LightboxTitle = forwardRef<
  ComponentRef<typeof DialogPrimitive.Title>,
  ComponentProps<typeof DialogPrimitive.Title>
>(function LightboxTitle({ className, ...props }, ref) {
  return (
    <DialogPrimitive.Title
      ref={ref}
      data-slot="lightbox-title"
      className={normalizeClassName(className)}
      {...props}
    />
  );
});

const LightboxDescription = forwardRef<
  ComponentRef<typeof DialogPrimitive.Description>,
  ComponentProps<typeof DialogPrimitive.Description>
>(function LightboxDescription({ className, ...props }, ref) {
  return (
    <DialogPrimitive.Description
      ref={ref}
      data-slot="lightbox-description"
      className={normalizeClassName(className)}
      {...props}
    />
  );
});

const LightboxCloseTrigger = forwardRef<
  ComponentRef<typeof DialogPrimitive.CloseTrigger>,
  ComponentProps<typeof DialogPrimitive.CloseTrigger>
>(function LightboxCloseTrigger({ className, ...props }, ref) {
  return (
    <DialogPrimitive.CloseTrigger
      ref={ref}
      data-slot="lightbox-close-trigger"
      className={normalizeClassName(className)}
      {...props}
    />
  );
});

const LightboxCloseIcon = forwardRef<
  ComponentRef<typeof CloseButton.Root>,
  Omit<ComponentProps<typeof DialogPrimitive.CloseTrigger>, 'asChild'>
>(function LightboxCloseIcon(
  { className, children, 'aria-label': ariaLabel = DEFAULT_CLOSE_LABEL, ...props },
  ref,
) {
  const dialog = useDialogContext();

  return (
    <DialogPrimitive.CloseTrigger asChild {...props}>
      <CloseButton.Root
        ref={ref}
        data-slot="lightbox-close-icon"
        data-state={dialog.open ? 'open' : 'closed'}
        aria-label={ariaLabel}
        className={clsx(styles.closeIcon, normalizeClassName(className))}
      >
        {children}
      </CloseButton.Root>
    </DialogPrimitive.CloseTrigger>
  );
});

const LightboxFrame = forwardRef<ComponentRef<'div'>, LightboxFrameProps>(function LightboxFrame(
  { className, closeOnClick = false, onClick, ...props },
  ref,
) {
  const frame = (
    <div
      ref={ref}
      data-slot="lightbox-frame"
      data-close-on-click={closeOnClick ? '' : undefined}
      className={clsx(styles.frame, className)}
      onClick={onClick}
      {...props}
    />
  );

  if (!closeOnClick) {
    return frame;
  }

  return <DialogPrimitive.CloseTrigger asChild>{frame}</DialogPrimitive.CloseTrigger>;
});

function LightboxGallery({
  selector = 'img',
  rootRef,
  rootSelector,
  closeOnClick = false,
  className,
  closeLabel = DEFAULT_CLOSE_LABEL,
}: LightboxGalleryProps) {
  const [open, setOpen] = useState(false);
  const [image, setImage] = useState<LightboxImageData | null>(null);

  useEffect(() => {
    const rootNode =
      rootRef?.current ?? (rootSelector ? document.querySelector<HTMLElement>(rootSelector) : null);
    if (!rootNode) {
      return;
    }

    const handleOpen = (target: EventTarget | null) => {
      const nextImage = getGalleryImage(target, selector);
      if (!nextImage) {
        return false;
      }

      setImage(nextImage);
      setOpen(true);
      return true;
    };

    const handlePreload = (target: EventTarget | null) => {
      const nextImage = getGalleryImage(target, selector);
      if (!nextImage) {
        return;
      }

      preloadImage(nextImage.src);
    };

    const handleClick = (event: MouseEvent) => {
      handleOpen(event.target);
    };

    const handlePointerEnter = (event: PointerEvent) => {
      handlePreload(event.target);
    };

    const handleFocusIn = (event: FocusEvent) => {
      handlePreload(event.target);
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (
        event.defaultPrevented ||
        event.altKey ||
        event.ctrlKey ||
        event.metaKey ||
        (event.key !== 'Enter' && event.key !== ' ')
      ) {
        return;
      }

      if (handleOpen(event.target)) {
        event.preventDefault();
      }
    };

    rootNode.addEventListener('click', handleClick);
    rootNode.addEventListener('pointerenter', handlePointerEnter, true);
    rootNode.addEventListener('focusin', handleFocusIn);
    rootNode.addEventListener('keydown', handleKeyDown);

    return () => {
      rootNode.removeEventListener('click', handleClick);
      rootNode.removeEventListener('pointerenter', handlePointerEnter, true);
      rootNode.removeEventListener('focusin', handleFocusIn);
      rootNode.removeEventListener('keydown', handleKeyDown);
    };
  }, [rootRef, rootSelector, selector]);

  return (
    <DialogPrimitive.Root
      open={open}
      onOpenChange={(details) => {
        setOpen(details.open);
      }}
      onExitComplete={() => {
        if (!open) {
          setImage(null);
        }
      }}
      lazyMount
      unmountOnExit
    >
      <PortalPrimitive>
        <LightboxBackdrop />
        <LightboxPositioner>
          <LightboxCloseIcon aria-label={closeLabel} />
          <LightboxContent aria-label={image?.alt ?? DEFAULT_PREVIEW_LABEL} className={className}>
            {image ? (
              <LightboxFrame closeOnClick={closeOnClick}>
                <img src={image.src} alt={image.alt ?? ''} />
              </LightboxFrame>
            ) : null}
          </LightboxContent>
        </LightboxPositioner>
      </PortalPrimitive>
    </DialogPrimitive.Root>
  );
}

const LightboxContext = DialogPrimitive.Context;

const Lightbox = Object.assign(LightboxRoot, {
  Root: LightboxRoot,
  RootProvider: LightboxRootProvider,
  Trigger: LightboxTrigger,
  Backdrop: LightboxBackdrop,
  Positioner: LightboxPositioner,
  Content: LightboxContent,
  Title: LightboxTitle,
  Description: LightboxDescription,
  CloseTrigger: LightboxCloseTrigger,
  CloseIcon: LightboxCloseIcon,
  Frame: LightboxFrame,
  Gallery: LightboxGallery,
  Context: LightboxContext,
});

export {
  Lightbox,
  LightboxGallery,
  useDialog as useLightbox,
  useDialogContext as useLightboxContext,
};
export type { LightboxGalleryProps };
export type {
  DialogFocusOutsideEvent as LightboxFocusOutsideEvent,
  DialogInteractOutsideEvent as LightboxInteractOutsideEvent,
  DialogOpenChangeDetails as LightboxOpenChangeDetails,
  DialogPointerDownOutsideEvent as LightboxPointerDownOutsideEvent,
  DialogTriggerValueChangeDetails as LightboxTriggerValueChangeDetails,
  UseDialogContext as UseLightboxContext,
  UseDialogProps as UseLightboxProps,
  UseDialogReturn as UseLightboxReturn,
} from '@ark-ui/react/dialog';
