// website/snippets/frame/vue/lifecycle.vue
<script setup lang="ts">
import { Frame } from '@ark-ui/vue';
import { ref } from 'vue';
const frame = ref<{ frameRef: HTMLIFrameElement | null } | null>(null);
const handleMount = () => {
  const frameDocument = frame.value?.frameRef?.contentDocument;
  if (!frameDocument) return;
  const script = frameDocument.createElement('script');
  script.textContent = 'document.body.dataset.ready = "true";';
  frameDocument.body.append(script);
};
const handleUnmount = () => {
  // Release application-owned listeners and other resources here.
};
</script>
<template>
  <Frame ref="frame" title="Interactive preview" @mount="handleMount" @unmount="handleUnmount">
    <main>Interactive preview</main>
  </Frame>
</template>

// website/src/components/examples/frame/lifecycle.tsx
import { Frame } from '@ark-ui/react';
import { useRef } from 'react';

export default function FrameLifecycleDemo() {
  const frameRef = useRef<HTMLIFrameElement>(null);

  return (
    <Frame
      ref={frameRef}
      title="Interactive preview"
      onMount={() => {
        const frameDocument = frameRef.current?.contentDocument;
        if (!frameDocument) return;

        const script = frameDocument.createElement('script');
        script.textContent = 'document.body.dataset.ready = "true";';
        frameDocument.body.append(script);
      }}
      onUnmount={() => {
        // Release application-owned listeners and other resources here.
      }}
    >
      <main>Interactive preview</main>
    </Frame>
  );
}
