// website/snippets/hotkeys/solid/sequences.tsx
import { useFormatHotkey, useHotkeys } from '@ark-ui/solid';
import { Card } from '@moduix/solid/card';
import { Kbd } from '@moduix/solid/kbd';
import { Stack } from '@moduix/solid/stack';
import { createSignal } from 'solid-js';

export default function HotkeysSequencesDemo() {
  const [destination, setDestination] = createSignal('Home');
  const formatHotkey = useFormatHotkey();

  useHotkeys({
    commands: [
      {
        action: () => setDestination('Inbox'),
        hotkey: 'g > i',
        id: 'go-to-inbox',
        label: 'Go to inbox',
      },
      {
        action: () => setDestination('Drafts'),
        hotkey: 'g > d',
        id: 'go-to-drafts',
        label: 'Go to drafts',
      },
    ],
  });

  return (
    <Card>
      <Card.Header>
        <Card.Title>Workspace navigation</Card.Title>
        <Card.Description>Press G, then I or D before the sequence times out.</Card.Description>
      </Card.Header>
      <Card.Body>
        <Stack gap="3">
          <Stack align="center" direction="row" justify="space-between">
            <span>Open inbox</span>
            <Kbd>{formatHotkey('g > i')}</Kbd>
          </Stack>
          <Stack align="center" direction="row" justify="space-between">
            <span>Open drafts</span>
            <Kbd>{formatHotkey('g > d')}</Kbd>
          </Stack>
        </Stack>
      </Card.Body>
      <Card.Footer>
        <output aria-live="polite">Current view: {destination()}</output>
      </Card.Footer>
    </Card>
  );
}

// website/src/components/examples/hotkeys/sequences.tsx
import { useFormatHotkey, useHotkeys } from '@ark-ui/react';
import { Card } from '@moduix/react/card';
import { Kbd } from '@moduix/react/kbd';
import { Stack } from '@moduix/react/stack';
import { useState } from 'react';
import styles from './hotkeys-sequences.module.css';

export default function HotkeysSequencesDemo() {
  const [destination, setDestination] = useState('Home');
  const formatHotkey = useFormatHotkey();

  useHotkeys({
    commands: [
      {
        action: () => setDestination('Inbox'),
        hotkey: 'g > i',
        id: 'go-to-inbox',
        label: 'Go to inbox',
      },
      {
        action: () => setDestination('Drafts'),
        hotkey: 'g > d',
        id: 'go-to-drafts',
        label: 'Go to drafts',
      },
    ],
  });

  return (
    <Card className={styles.root}>
      <Card.Header>
        <Card.Title>Workspace navigation</Card.Title>
        <Card.Description>Press G, then I or D before the sequence times out.</Card.Description>
      </Card.Header>
      <Card.Body>
        <Stack className={styles.stack} gap="3">
          <Stack align="center" direction="row" justify="space-between">
            <span>Open inbox</span>
            <Kbd>{formatHotkey('g > i')}</Kbd>
          </Stack>
          <Stack align="center" direction="row" justify="space-between">
            <span>Open drafts</span>
            <Kbd>{formatHotkey('g > d')}</Kbd>
          </Stack>
        </Stack>
      </Card.Body>
      <Card.Footer>
        <output>Current view: {destination}</output>
      </Card.Footer>
    </Card>
  );
}
