// packages/react/src/components/tabs/Tabs.tsx
'use client';

import { Tabs as TabsPrimitive, useTabs, useTabsContext } from '@ark-ui/react/tabs';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef } from 'react';
import { forwardRef } from 'react';
import styles from './Tabs.module.css';

type TabsVariant = 'default' | 'line';

const Tabs = forwardRef<
  ComponentRef<typeof TabsPrimitive.Root>,
  ComponentProps<typeof TabsPrimitive.Root> & { variant?: TabsVariant }
>(function Tabs({ className, orientation, variant = 'default', ...props }, ref) {
  const resolvedVariant = orientation === 'vertical' ? 'default' : variant;

  return (
    <TabsPrimitive.Root
      ref={ref}
      className={clsx(styles.root, className)}
      orientation={orientation}
      {...props}
      data-variant={resolvedVariant}
      data-slot="tabs-root"
    />
  );
});

const TabsRootProvider = forwardRef<
  ComponentRef<typeof TabsPrimitive.RootProvider>,
  ComponentProps<typeof TabsPrimitive.RootProvider> & { variant?: TabsVariant }
>(function TabsRootProvider({ className, value, variant = 'default', ...props }, ref) {
  const orientation = (
    value.getRootProps() as {
      'data-orientation'?: 'horizontal' | 'vertical';
    }
  )['data-orientation'];
  const resolvedVariant = orientation === 'vertical' ? 'default' : variant;

  return (
    <TabsPrimitive.RootProvider
      ref={ref}
      className={clsx(styles.root, className)}
      value={value}
      {...props}
      data-variant={resolvedVariant}
      data-slot="tabs-root-provider"
    />
  );
});

const TabsList = forwardRef<
  ComponentRef<typeof TabsPrimitive.List>,
  ComponentProps<typeof TabsPrimitive.List>
>(function TabsList({ className, ...props }, ref) {
  return (
    <TabsPrimitive.List
      ref={ref}
      className={clsx(styles.list, className)}
      {...props}
      data-slot="tabs-list"
    />
  );
});

const TabsTrigger = forwardRef<
  ComponentRef<typeof TabsPrimitive.Trigger>,
  ComponentProps<typeof TabsPrimitive.Trigger>
>(function TabsTrigger({ className, ...props }, ref) {
  return (
    <TabsPrimitive.Trigger
      ref={ref}
      className={clsx(styles.trigger, className)}
      {...props}
      data-slot="tabs-trigger"
    />
  );
});

const TabsIndicator = forwardRef<
  ComponentRef<typeof TabsPrimitive.Indicator>,
  ComponentProps<typeof TabsPrimitive.Indicator>
>(function TabsIndicator({ className, ...props }, ref) {
  return (
    <TabsPrimitive.Indicator
      ref={ref}
      className={clsx(styles.indicator, className)}
      {...props}
      data-slot="tabs-indicator"
    />
  );
});

const TabsContent = forwardRef<
  ComponentRef<typeof TabsPrimitive.Content>,
  ComponentProps<typeof TabsPrimitive.Content>
>(function TabsContent({ className, ...props }, ref) {
  return (
    <TabsPrimitive.Content
      ref={ref}
      className={clsx(styles.content, className)}
      {...props}
      data-slot="tabs-content"
    />
  );
});

const TabsContext = TabsPrimitive.Context;

export {
  Tabs,
  TabsContext,
  TabsContent,
  TabsIndicator,
  TabsList,
  TabsRootProvider,
  TabsTrigger,
  useTabs,
  useTabsContext,
};

// packages/solid/src/components/tabs/Tabs.tsx
import { Tabs as TabsPrimitive, useTabs, useTabsContext } from '@ark-ui/solid/tabs';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { splitProps } from 'solid-js';
import styles from './Tabs.module.css';

type TabsVariant = 'default' | 'line';

function Tabs(props: ComponentProps<typeof TabsPrimitive.Root> & { variant?: TabsVariant }) {
  const [local, others] = splitProps(props, ['class', 'orientation', 'variant']);

  return (
    <TabsPrimitive.Root
      class={clsx(styles.root, local.class)}
      orientation={local.orientation}
      {...others}
      data-variant={local.orientation === 'vertical' ? 'default' : (local.variant ?? 'default')}
      data-slot="tabs-root"
    />
  );
}

function TabsRootProvider(
  props: ComponentProps<typeof TabsPrimitive.RootProvider> & { variant?: TabsVariant },
) {
  const [local, others] = splitProps(props, ['class', 'value', 'variant']);
  const orientation = () =>
    (
      local.value().getRootProps() as {
        'data-orientation'?: 'horizontal' | 'vertical';
      }
    )['data-orientation'];

  return (
    <TabsPrimitive.RootProvider
      class={clsx(styles.root, local.class)}
      value={local.value}
      {...others}
      data-variant={orientation() === 'vertical' ? 'default' : (local.variant ?? 'default')}
      data-slot="tabs-root-provider"
    />
  );
}

function TabsList(props: ComponentProps<typeof TabsPrimitive.List>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <TabsPrimitive.List class={clsx(styles.list, local.class)} {...others} data-slot="tabs-list" />
  );
}

function TabsTrigger(props: ComponentProps<typeof TabsPrimitive.Trigger>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <TabsPrimitive.Trigger
      class={clsx(styles.trigger, local.class)}
      {...others}
      data-slot="tabs-trigger"
    />
  );
}

function TabsIndicator(props: ComponentProps<typeof TabsPrimitive.Indicator>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <TabsPrimitive.Indicator
      class={clsx(styles.indicator, local.class)}
      {...others}
      data-slot="tabs-indicator"
    />
  );
}

function TabsContent(props: ComponentProps<typeof TabsPrimitive.Content>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <TabsPrimitive.Content
      class={clsx(styles.content, local.class)}
      {...others}
      data-slot="tabs-content"
    />
  );
}

const TabsContext = TabsPrimitive.Context;

export {
  Tabs,
  TabsContext,
  TabsContent,
  TabsIndicator,
  TabsList,
  TabsRootProvider,
  TabsTrigger,
  useTabs,
  useTabsContext,
};
