// packages/react/src/components/close-button/CloseButton.tsx
import type { HTMLArkProps } from '@ark-ui/react/factory';
import { ark } from '@ark-ui/react/factory';
import { clsx } from 'clsx';
import { forwardRef, type ComponentRef } from 'react';
import { CloseIcon } from '@/lib/moduix/icons/ui';
import styles from './CloseButton.module.css';

type CloseButtonProps = HTMLArkProps<'button'> & {
  'data-disabled'?: string;
  'data-part'?: string;
  'data-scope'?: string;
  'data-slot'?: string;
};

const CloseButton = forwardRef<ComponentRef<typeof ark.button>, CloseButtonProps>(
  function CloseButton(
    {
      asChild,
      className,
      children,
      disabled,
      onClick,
      onClickCapture,
      type,
      'aria-disabled': ariaDisabled,
      'aria-label': ariaLabel,
      'aria-labelledby': ariaLabelledBy,
      'data-disabled': dataDisabled,
      'data-part': dataPart,
      'data-scope': dataScope,
      'data-slot': dataSlot,
      ...props
    },
    ref,
  ) {
    const isDisabled =
      disabled || ariaDisabled === true || ariaDisabled === 'true' || dataDisabled !== undefined;
    const nativeDisabled = asChild ? undefined : disabled;
    const resolvedAriaDisabled = asChild && disabled ? true : ariaDisabled;
    const handleClickCapture: CloseButtonProps['onClickCapture'] = (event) => {
      if (isDisabled) {
        event.preventDefault();
        event.stopPropagation();
        return;
      }

      onClickCapture?.(event);
    };
    const handleClick: CloseButtonProps['onClick'] = (event) => {
      if (isDisabled) {
        event.preventDefault();
        event.stopPropagation();
        return;
      }

      onClick?.(event);
    };

    return (
      <ark.button
        ref={ref}
        asChild={asChild}
        {...props}
        type={asChild ? type : (type ?? 'button')}
        disabled={nativeDisabled}
        data-scope={dataScope ?? 'close-button'}
        data-part={dataPart ?? 'root'}
        data-slot={dataSlot ?? 'close-button-root'}
        data-disabled={dataDisabled ?? (isDisabled ? '' : undefined)}
        className={clsx(styles.root, className)}
        aria-disabled={resolvedAriaDisabled}
        aria-label={ariaLabel ?? (ariaLabelledBy == null ? 'Close' : undefined)}
        aria-labelledby={ariaLabelledBy}
        onClickCapture={handleClickCapture}
        onClick={handleClick}
      >
        {children || <CloseIcon />}
      </ark.button>
    );
  },
);

export { CloseButton };

// packages/vue/src/components/close-button/CloseButton.vue
<script setup lang="ts">
import { ark } from '@ark-ui/vue/factory';
import type { HTMLArkProps } from '@ark-ui/vue/factory';
import { clsx } from 'clsx';
import { computed, useAttrs } from 'vue';
import type { HTMLAttributes } from 'vue';
import { CloseIcon } from '@/internal/icons/ui/Icons';
import styles from './CloseButton.module.css';

defineOptions({ inheritAttrs: false });

type Booleanish = boolean | 'false' | 'true';

export interface Props extends /* @vue-ignore */ HTMLArkProps<'button'> {
  asChild?: boolean;
  ariaLabel?: string;
  ariaLabelledby?: string;
  class?: HTMLAttributes['class'];
  dataDisabled?: string;
  dataPart?: string;
  dataScope?: string;
  dataSlot?: string;
  disabled?: boolean;
  onClick?: (event: MouseEvent) => void;
  onClickCapture?: (event: MouseEvent) => void;
  type?: 'button' | 'reset' | 'submit';
}

const {
  asChild = false,
  ariaLabel,
  ariaLabelledby,
  class: className,
  dataDisabled,
  dataPart = 'root',
  dataScope = 'close-button',
  dataSlot = 'close-button-root',
  disabled = false,
  onClick,
  onClickCapture,
  type,
} = defineProps<Props>();

defineSlots<{ default?: () => unknown }>();

const attrs = useAttrs();
const ariaDisabled = computed(() => attrs['aria-disabled'] as Booleanish | undefined);
const isDisabled = computed(
  () =>
    disabled ||
    ariaDisabled.value === true ||
    ariaDisabled.value === 'true' ||
    dataDisabled !== undefined,
);

const handleClickCapture = (event: MouseEvent) => {
  if (isDisabled.value) {
    event.preventDefault();
    event.stopPropagation();
    return;
  }

  onClickCapture?.(event);
};

const handleClick = (event: MouseEvent) => {
  if (isDisabled.value) {
    event.preventDefault();
    event.stopPropagation();
    return;
  }

  onClick?.(event);
};
</script>

<template>
  <ark.button
    v-bind="attrs"
    :as-child="asChild"
    :type="asChild ? type : (type ?? 'button')"
    :disabled="asChild ? undefined : disabled"
    :aria-disabled="asChild && disabled ? true : ariaDisabled"
    :aria-label="ariaLabel ?? (ariaLabelledby == null ? 'Close' : undefined)"
    :aria-labelledby="ariaLabelledby"
    @click.capture="handleClickCapture"
    @click="handleClick"
    :data-scope="dataScope"
    :data-part="dataPart"
    :data-slot="dataSlot"
    :data-disabled="dataDisabled ?? (isDisabled ? '' : undefined)"
    :class="clsx(styles.root, className)"
  >
    <slot><CloseIcon /></slot>
  </ark.button>
</template>
