// packages/solid/src/components/rating-group/RatingGroup.tsx
import {
  RatingGroup as RatingGroupPrimitive,
  useRatingGroup,
  useRatingGroupContext,
  useRatingGroupItemContext,
} from '@ark-ui/solid/rating-group';
import { clsx } from 'clsx';
import type { ComponentProps, JSX } from 'solid-js';
import { children, For, splitProps } from 'solid-js';
import { RatingStarIcon } from '@/lib/moduix/icons/ui/Icons';
import styles from './RatingGroup.module.css';

type RatingGroupSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

type RatingGroupRootProps = ComponentProps<typeof RatingGroupPrimitive.Root> & {
  size?: RatingGroupSize;
};

type RatingGroupRootProviderProps = ComponentProps<typeof RatingGroupPrimitive.RootProvider> & {
  size?: RatingGroupSize;
};

type RatingGroupItemIndicatorProps = ComponentProps<'span'>;

function RatingGroupRoot(props: RatingGroupRootProps) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class', 'size']);

  return (
    <RatingGroupPrimitive.Root
      asChild={local.asChild}
      data-size={local.size ?? 'md'}
      class={clsx(styles.root, local.class)}
      {...others}
      data-slot="rating-group-root"
    >
      {local.children}
    </RatingGroupPrimitive.Root>
  );
}

function RatingGroupRootProvider(props: RatingGroupRootProviderProps) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class', 'size']);

  return (
    <RatingGroupPrimitive.RootProvider
      asChild={local.asChild}
      class={clsx(styles.root, local.class)}
      {...others}
      data-size={local.size ?? 'md'}
      data-slot="rating-group-root-provider"
    >
      {local.children}
    </RatingGroupPrimitive.RootProvider>
  );
}

function RatingGroupLabel(props: ComponentProps<typeof RatingGroupPrimitive.Label>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <RatingGroupPrimitive.Label
      class={clsx(styles.label, local.class)}
      {...others}
      data-slot="rating-group-label"
    />
  );
}

function RatingGroupControl(props: ComponentProps<typeof RatingGroupPrimitive.Control>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <RatingGroupPrimitive.Control
      class={clsx(styles.control, local.class)}
      {...others}
      data-slot="rating-group-control"
    />
  );
}

function RatingGroupItem(props: ComponentProps<typeof RatingGroupPrimitive.Item>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <RatingGroupPrimitive.Item
      class={clsx(styles.item, local.class)}
      {...others}
      data-slot="rating-group-item"
    />
  );
}

function RatingGroupItemIndicator(props: RatingGroupItemIndicatorProps) {
  const [local, others] = splitProps(props, ['children', 'class']);
  const resolvedChildren = children(() => local.children);
  const item = useRatingGroupItemContext();

  return (
    <span
      class={clsx(styles.itemIndicator, local.class)}
      {...others}
      data-half={item().half ? '' : undefined}
      data-highlighted={item().highlighted ? '' : undefined}
      data-slot="rating-group-item-indicator"
    >
      {resolvedChildren() ?? (
        <>
          <RatingStarIcon data-slot="rating-group-item-indicator-bg" class={styles.iconBg} />
          <RatingStarIcon data-slot="rating-group-item-indicator-fg" class={styles.iconFg} />
        </>
      )}
    </span>
  );
}

function RatingGroupItems(props: { children?: JSX.Element }) {
  return (
    <RatingGroupPrimitive.Context>
      {(ratingGroup) => (
        <For each={ratingGroup().items}>
          {(item) => (
            <RatingGroupItem index={item}>
              {props.children ?? <RatingGroupItemIndicator />}
            </RatingGroupItem>
          )}
        </For>
      )}
    </RatingGroupPrimitive.Context>
  );
}

const RatingGroup = Object.assign(RatingGroupRoot, {
  Root: RatingGroupRoot,
  RootProvider: RatingGroupRootProvider,
  Context: RatingGroupPrimitive.Context,
  HiddenInput: RatingGroupPrimitive.HiddenInput,
  Label: RatingGroupLabel,
  Control: RatingGroupControl,
  Item: RatingGroupItem,
  ItemContext: RatingGroupPrimitive.ItemContext,
  ItemIndicator: RatingGroupItemIndicator,
  Items: RatingGroupItems,
});

export { RatingGroup, useRatingGroup, useRatingGroupContext, useRatingGroupItemContext };
export type {
  RatingGroupItemIndicatorProps,
  RatingGroupRootProps,
  RatingGroupRootProviderProps,
  RatingGroupSize,
};

// packages/react/src/components/rating-group/RatingGroup.tsx
'use client';

import {
  RatingGroup as RatingGroupPrimitive,
  useRatingGroup,
  useRatingGroupContext,
  useRatingGroupItemContext,
} from '@ark-ui/react/rating-group';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef, ReactNode } from 'react';
import { forwardRef } from 'react';
import { RatingStarIcon } from '@/lib/moduix/icons/ui';
import styles from './RatingGroup.module.css';

type RatingGroupSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';

type RatingGroupRootProps = ComponentProps<typeof RatingGroupPrimitive.Root> & {
  size?: RatingGroupSize;
};

type RatingGroupRootProviderProps = ComponentProps<typeof RatingGroupPrimitive.RootProvider> & {
  size?: RatingGroupSize;
};

type RatingGroupItemIndicatorProps = ComponentProps<'span'>;

const RatingGroupRoot = forwardRef<
  ComponentRef<typeof RatingGroupPrimitive.Root>,
  RatingGroupRootProps
>(function RatingGroupRoot({ className, size = 'md', ...props }, ref) {
  return (
    <RatingGroupPrimitive.Root
      ref={ref}
      data-size={size}
      className={clsx(styles.root, className)}
      {...props}
      data-slot="rating-group-root"
    />
  );
});

const RatingGroupRootProvider = forwardRef<
  ComponentRef<typeof RatingGroupPrimitive.RootProvider>,
  RatingGroupRootProviderProps
>(function RatingGroupRootProvider({ className, size = 'md', ...props }, ref) {
  return (
    <RatingGroupPrimitive.RootProvider
      ref={ref}
      data-size={size}
      className={clsx(styles.root, className)}
      {...props}
      data-slot="rating-group-root-provider"
    />
  );
});

const RatingGroupLabel = forwardRef<
  ComponentRef<typeof RatingGroupPrimitive.Label>,
  ComponentProps<typeof RatingGroupPrimitive.Label>
>(function RatingGroupLabel({ className, ...props }, ref) {
  return (
    <RatingGroupPrimitive.Label
      ref={ref}
      className={clsx(styles.label, className)}
      {...props}
      data-slot="rating-group-label"
    />
  );
});

const RatingGroupControl = forwardRef<
  ComponentRef<typeof RatingGroupPrimitive.Control>,
  ComponentProps<typeof RatingGroupPrimitive.Control>
>(function RatingGroupControl({ className, ...props }, ref) {
  return (
    <RatingGroupPrimitive.Control
      ref={ref}
      className={clsx(styles.control, className)}
      {...props}
      data-slot="rating-group-control"
    />
  );
});

const RatingGroupItem = forwardRef<
  ComponentRef<typeof RatingGroupPrimitive.Item>,
  ComponentProps<typeof RatingGroupPrimitive.Item>
>(function RatingGroupItem({ className, ...props }, ref) {
  return (
    <RatingGroupPrimitive.Item
      ref={ref}
      className={clsx(styles.item, className)}
      {...props}
      data-slot="rating-group-item"
    />
  );
});

const RatingGroupItemIndicator = forwardRef<HTMLSpanElement, RatingGroupItemIndicatorProps>(
  function RatingGroupItemIndicator({ className, children, ...props }, ref) {
    const { half, highlighted } = useRatingGroupItemContext();

    return (
      <span
        ref={ref}
        data-half={half ? '' : undefined}
        data-highlighted={highlighted ? '' : undefined}
        className={clsx(styles.itemIndicator, className)}
        {...props}
        data-slot="rating-group-item-indicator"
      >
        {children ?? (
          <>
            <RatingStarIcon data-slot="rating-group-item-indicator-bg" className={styles.iconBg} />
            <RatingStarIcon data-slot="rating-group-item-indicator-fg" className={styles.iconFg} />
          </>
        )}
      </span>
    );
  },
);

function RatingGroupItems({ children }: { children?: ReactNode }) {
  return (
    <>
      <RatingGroupPrimitive.Context>
        {({ items }) =>
          items.map((item) => (
            <RatingGroupItem key={item} index={item}>
              {children ?? <RatingGroupItemIndicator />}
            </RatingGroupItem>
          ))
        }
      </RatingGroupPrimitive.Context>
    </>
  );
}

const RatingGroup = Object.assign(RatingGroupRoot, {
  Root: RatingGroupRoot,
  RootProvider: RatingGroupRootProvider,
  Context: RatingGroupPrimitive.Context,
  HiddenInput: RatingGroupPrimitive.HiddenInput,
  Label: RatingGroupLabel,
  Control: RatingGroupControl,
  Item: RatingGroupItem,
  ItemContext: RatingGroupPrimitive.ItemContext,
  ItemIndicator: RatingGroupItemIndicator,
  Items: RatingGroupItems,
});

export { RatingGroup, useRatingGroup, useRatingGroupContext, useRatingGroupItemContext };
export type {
  RatingGroupItemIndicatorProps,
  RatingGroupRootProps,
  RatingGroupRootProviderProps,
  RatingGroupSize,
};
