// website/snippets/select/solid/dynamic-items.tsx
import { createListCollection } from '@ark-ui/solid/collection';
import { Input } from '@moduix/solid/input';
import { Select } from '@moduix/solid/select';
import { createMemo, createSignal, For } from 'solid-js';
import styles from '@/components/examples/select/select-dynamic-items.module.css';

const fruits = [
  { label: 'Apple', value: 'apple' },
  { label: 'Banana', value: 'banana' },
  { label: 'Blueberry', value: 'blueberry' },
  { label: 'Grape', value: 'grape' },
  { label: 'Kiwi', value: 'kiwi' },
  { label: 'Mango', value: 'mango' },
  { label: 'Orange', value: 'orange' },
  { label: 'Pineapple', value: 'pineapple' },
  { label: 'Strawberry', value: 'strawberry' },
  { label: 'Watermelon', value: 'watermelon' },
];

export default function SelectDynamicItemsDemo() {
  const [query, setQuery] = createSignal('');
  const collection = createMemo(() =>
    createListCollection({
      items: fruits.filter((item) => item.label.toLowerCase().includes(query())),
    }),
  );

  return (
    <div class={styles.root}>
      <Input
        aria-label="Filter fruits"
        value={query()}
        onInput={(event) => setQuery(event.currentTarget.value.toLowerCase())}
        placeholder="Filter fruits"
      />
      <Select collection={collection()}>
        <Select.Label>Choose fruit</Select.Label>
        <Select.Field placeholder="Select an option" clearLabel="Clear selection" />
        <Select.Positioner>
          <Select.Content>
            <For each={collection().items}>
              {(item) => (
                <Select.Item item={item}>
                  <Select.ItemText>{item.label}</Select.ItemText>
                  <Select.ItemIndicator />
                </Select.Item>
              )}
            </For>
          </Select.Content>
        </Select.Positioner>
      </Select>
    </div>
  );
}

// apps/docs/docs/en/docs/_snippets/select/dynamic-items.tsx
import { createListCollection } from '@ark-ui/react/collection';
import { Input } from '@moduix/react/input';
import { Select } from '@moduix/react/select';
import { useState } from 'react';

const fruits = createListCollection({
  items: [
    {
      label: 'Apple',
      value: 'apple',
    },
    {
      label: 'Banana',
      value: 'banana',
    },
    {
      label: 'Blueberry',
      value: 'blueberry',
    },
    {
      label: 'Grape',
      value: 'grape',
    },
    {
      label: 'Kiwi',
      value: 'kiwi',
    },
    {
      label: 'Mango',
      value: 'mango',
    },
    {
      label: 'Orange',
      value: 'orange',
    },
    {
      label: 'Pineapple',
      value: 'pineapple',
    },
    {
      label: 'Strawberry',
      value: 'strawberry',
    },
    {
      label: 'Watermelon',
      value: 'watermelon',
    },
  ],
});

export default function SelectDynamicItemsDemo() {
  const [query, setQuery] = useState('');
  const collection = createListCollection({
    items: fruits.items.filter((item) => item.label.toLowerCase().includes(query)),
  });

  return (
    <div className="select-dynamic-items">
      <Input
        aria-label="Filter fruits"
        value={query}
        onChange={(event) => setQuery(event.target.value.toLowerCase())}
        placeholder="Filter fruits"
      />
      <Select collection={collection}>
        <Select.Label>Choose fruit</Select.Label>
        <Select.Field placeholder="Select an option" clearLabel="Clear selection" />
        <Select.Positioner>
          <Select.Content>
            {collection.items.map((item) => (
              <Select.Item key={item.value} item={item}>
                <Select.ItemText>{item.label}</Select.ItemText>
                <Select.ItemIndicator />
              </Select.Item>
            ))}
          </Select.Content>
        </Select.Positioner>
      </Select>
    </div>
  );
}
