// packages/solid/src/components/fieldset/Fieldset.tsx
import {
  Fieldset as FieldsetPrimitive,
  useFieldset,
  useFieldsetContext,
} from '@ark-ui/solid/fieldset';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { splitProps } from 'solid-js';
import styles from './Fieldset.module.css';

function FieldsetRoot(props: ComponentProps<typeof FieldsetPrimitive.Root>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <FieldsetPrimitive.Root
      asChild={local.asChild}
      {...others}
      data-slot="fieldset-root"
      class={clsx(styles.root, local.class)}
    />
  );
}

function FieldsetRootProvider(props: ComponentProps<typeof FieldsetPrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <FieldsetPrimitive.RootProvider
      asChild={local.asChild}
      {...others}
      data-slot="fieldset-root-provider"
      class={clsx(styles.root, local.class)}
    />
  );
}

function FieldsetLegend(props: ComponentProps<typeof FieldsetPrimitive.Legend>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <FieldsetPrimitive.Legend
      asChild={local.asChild}
      {...others}
      data-slot="fieldset-legend"
      class={clsx(styles.legend, local.class)}
    />
  );
}

function FieldsetHelperText(props: ComponentProps<typeof FieldsetPrimitive.HelperText>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <FieldsetPrimitive.HelperText
      asChild={local.asChild}
      {...others}
      data-slot="fieldset-helper-text"
      class={clsx(styles.helperText, local.class)}
    />
  );
}

function FieldsetErrorText(props: ComponentProps<typeof FieldsetPrimitive.ErrorText>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <FieldsetPrimitive.ErrorText
      asChild={local.asChild}
      {...others}
      data-slot="fieldset-error-text"
      class={clsx(styles.errorText, local.class)}
    />
  );
}

const Fieldset = Object.assign(FieldsetRoot, {
  Root: FieldsetRoot,
  RootProvider: FieldsetRootProvider,
  Context: FieldsetPrimitive.Context,
  Legend: FieldsetLegend,
  HelperText: FieldsetHelperText,
  ErrorText: FieldsetErrorText,
});

export { Fieldset, useFieldset, useFieldsetContext };

// packages/react/src/components/fieldset/Fieldset.tsx
'use client';

import {
  Fieldset as FieldsetPrimitive,
  useFieldset,
  useFieldsetContext,
} from '@ark-ui/react/fieldset';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef } from 'react';
import { forwardRef } from 'react';
import styles from './Fieldset.module.css';

const FieldsetRoot = forwardRef<
  ComponentRef<typeof FieldsetPrimitive.Root>,
  ComponentProps<typeof FieldsetPrimitive.Root>
>(function FieldsetRoot({ className, ...props }, ref) {
  return (
    <FieldsetPrimitive.Root
      ref={ref}
      data-slot="fieldset-root"
      className={clsx(styles.root, className)}
      {...props}
    />
  );
});

const FieldsetRootProvider = forwardRef<
  ComponentRef<typeof FieldsetPrimitive.RootProvider>,
  ComponentProps<typeof FieldsetPrimitive.RootProvider>
>(function FieldsetRootProvider({ className, ...props }, ref) {
  return (
    <FieldsetPrimitive.RootProvider
      ref={ref}
      data-slot="fieldset-root-provider"
      className={clsx(styles.root, className)}
      {...props}
    />
  );
});

const FieldsetLegend = forwardRef<
  ComponentRef<typeof FieldsetPrimitive.Legend>,
  ComponentProps<typeof FieldsetPrimitive.Legend>
>(function FieldsetLegend({ className, ...props }, ref) {
  return (
    <FieldsetPrimitive.Legend
      ref={ref}
      data-slot="fieldset-legend"
      className={clsx(styles.legend, className)}
      {...props}
    />
  );
});

const FieldsetHelperText = forwardRef<
  ComponentRef<typeof FieldsetPrimitive.HelperText>,
  ComponentProps<typeof FieldsetPrimitive.HelperText>
>(function FieldsetHelperText({ className, ...props }, ref) {
  return (
    <FieldsetPrimitive.HelperText
      ref={ref}
      data-slot="fieldset-helper-text"
      className={clsx(styles.helperText, className)}
      {...props}
    />
  );
});

const FieldsetErrorText = forwardRef<
  ComponentRef<typeof FieldsetPrimitive.ErrorText>,
  ComponentProps<typeof FieldsetPrimitive.ErrorText>
>(function FieldsetErrorText({ className, ...props }, ref) {
  return (
    <FieldsetPrimitive.ErrorText
      ref={ref}
      data-slot="fieldset-error-text"
      className={clsx(styles.errorText, className)}
      {...props}
    />
  );
});

const Fieldset = Object.assign(FieldsetRoot, {
  Root: FieldsetRoot,
  RootProvider: FieldsetRootProvider,
  Context: FieldsetPrimitive.Context,
  Legend: FieldsetLegend,
  HelperText: FieldsetHelperText,
  ErrorText: FieldsetErrorText,
});

export { Fieldset, useFieldset, useFieldsetContext };
