// website/src/components/examples/list-selection/multiple.tsx
import { createListCollection, useListSelection } from '@ark-ui/react/collection';
import { PreviewMeta } from '@/components/mdx/Components';

const teams = createListCollection({
  items: [
    { label: 'Platform', value: 'platform' },
    { label: 'Product', value: 'product' },
    { label: 'Design', value: 'design' },
  ],
});

export default function ListSelectionMultipleDemo() {
  const selection = useListSelection({
    collection: teams,
    selectionMode: 'multiple',
    initialSelectedValues: ['platform'],
  });

  function toggleAll() {
    if (selection.isAllSelected()) {
      selection.clear();
      return;
    }

    selection.setSelectedValues(teams.getValues());
  }

  return (
    <section aria-labelledby="teams-heading">
      <h3 id="teams-heading">Choose teams</h3>
      <ul>
        {teams.items.map((team) => (
          <li key={team.value}>
            <button
              type="button"
              aria-pressed={selection.isSelected(team.value)}
              onClick={() => selection.select(team.value)}
            >
              {team.label}
            </button>
          </li>
        ))}
      </ul>
      <button type="button" onClick={toggleAll}>
        {selection.isAllSelected() ? 'Clear all' : 'Select all'}
      </button>
      <PreviewMeta>
        <output aria-live="polite">
          {selection.isEmpty
            ? 'No teams selected'
            : `Selected: ${teams.stringifyMany(selection.selectedValues)}`}
        </output>
      </PreviewMeta>
    </section>
  );
}

// website/snippets/list-selection/vue/multiple.vue
<script setup lang="ts">
import { createListCollection, useListSelection } from '@ark-ui/vue/collection';
const teams = createListCollection({
  items: [
    { label: 'Platform', value: 'platform' },
    { label: 'Product', value: 'product' },
    { label: 'Design', value: 'design' },
  ],
});
const selection = useListSelection({
  collection: teams,
  selectionMode: 'multiple',
  initialSelectedValues: ['platform'],
});
const { isEmpty, selectedValues } = selection;
const toggleAll = () => {
  if (selection.isAllSelected()) selection.clear();
  else selection.setSelectedValues(teams.getValues());
};
</script>
<template>
  <section aria-labelledby="teams-heading">
    <h3 id="teams-heading">Choose teams</h3>
    <ul>
      <li v-for="team in teams.items" :key="team.value">
        <button
          type="button"
          :aria-pressed="selection.isSelected(team.value)"
          @click="selection.select(team.value)"
        >
          {{ team.label }}
        </button>
      </li>
    </ul>
    <button type="button" @click="toggleAll">
      {{ selection.isAllSelected() ? 'Clear all' : 'Select all' }}
    </button>
    <output aria-live="polite">{{
      isEmpty ? 'No teams selected' : `Selected: ${teams.stringifyMany(selectedValues)}`
    }}</output>
  </section>
</template>
