// packages/ui/src/components/Toggle/Toggle.tsx
import { Toggle as TogglePrimitive } from '@base-ui/react/toggle';
import { forwardRef, type ComponentRef } from 'react';
import { mergeClassName } from '@/utils/mergeClassName';
import styles from './Toggle.module.css';

type ToggleVariant = 'default' | 'outline' | 'ghost';
type ToggleSize = 'xs' | 'sm' | 'md' | 'lg' | 'icon-sm' | 'icon-md' | 'icon-lg';

const Toggle = forwardRef<
  ComponentRef<typeof TogglePrimitive>,
  TogglePrimitive.Props & {
    variant?: ToggleVariant;
    size?: ToggleSize;
  }
>(function Toggle({ className, variant = 'default', size = 'md', ...props }, ref) {
  return (
    <TogglePrimitive
      ref={ref}
      data-slot="toggle-root"
      data-variant={variant}
      data-size={size}
      className={mergeClassName(className, styles.root)}
      {...props}
    />
  );
});

export { Toggle };

// packages/solid/src/components/toggle/Toggle.tsx
import { Toggle as TogglePrimitive, ToggleContext, useToggleContext } from '@ark-ui/solid/toggle';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { splitProps } from 'solid-js';
import styles from './Toggle.module.css';

type ToggleVariant = 'default' | 'outline' | 'ghost';
type ToggleSize = 'xs' | 'sm' | 'md' | 'lg' | 'icon-sm' | 'icon-md' | 'icon-lg';
type ToggleRootProps = ComponentProps<typeof TogglePrimitive.Root> & {
  variant?: ToggleVariant;
  size?: ToggleSize;
};

function Toggle(props: ToggleRootProps) {
  const [local, others] = splitProps(props, ['asChild', 'class', 'size', 'variant']);

  return (
    <TogglePrimitive.Root
      asChild={local.asChild}
      {...others}
      data-slot="toggle-root"
      data-variant={local.variant ?? 'default'}
      data-size={local.size ?? 'md'}
      class={clsx(styles.root, local.class)}
    />
  );
}

function ToggleIndicator(props: ComponentProps<typeof TogglePrimitive.Indicator>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <TogglePrimitive.Indicator
      asChild={local.asChild}
      {...others}
      data-slot="toggle-indicator"
      class={clsx(styles.indicator, local.class)}
    />
  );
}

export { Toggle, ToggleContext, ToggleIndicator, useToggleContext };
export type { ToggleRootProps, ToggleSize, ToggleVariant };
