// website/docs/en/docs/_snippets/menu/select-event.tsx
import { Button } from '@moduix/react/button';
import { Menu } from '@moduix/react/menu';
import { useState } from 'react';
import { PreviewMeta } from '@/components/mdx/Components';
import styles from '@/components/examples/menu/menu-select-event.module.css';

export default function SelectEventMenuDemo() {
  const [selected, setSelected] = useState('Nothing selected');
  return (
    <div>
      <div className={styles.triggerRow}>
        <Menu onSelect={(details) => setSelected(details.value)}>
          <Menu.Trigger asChild>
            <Button>
              Actions
              <Menu.Indicator />
            </Button>
          </Menu.Trigger>
          <Menu.Positioner>
            <Menu.Content className={styles.content}>
              <Menu.Item value="edit">Edit</Menu.Item>
              <Menu.Item value="duplicate">Duplicate</Menu.Item>
              <Menu.Item value="archive">Archive</Menu.Item>
              <Menu.Item value="delete" tone="destructive">
                Delete
              </Menu.Item>
            </Menu.Content>
          </Menu.Positioner>
        </Menu>
      </div>
      <PreviewMeta>
        <output>Selected: {selected}</output>
      </PreviewMeta>
    </div>
  );
}

// website/snippets/menu/solid/select-event.tsx
import { Button } from '@moduix/solid/button';
import { Menu } from '@moduix/solid/menu';
import { createSignal } from 'solid-js';
import styles from '@/components/examples/menu/menu-select-event.module.css';

export default function SelectEventMenuDemo() {
  const [selected, setSelected] = createSignal('Nothing selected');

  return (
    <div>
      <div class={styles.triggerRow}>
        <Menu onSelect={(details) => setSelected(details.value)}>
          <Menu.Trigger asChild={(props) => <Button {...props()} />}>
            Actions
            <Menu.Indicator />
          </Menu.Trigger>
          <Menu.Positioner>
            <Menu.Content class={styles.content}>
              <Menu.Item value="edit">Edit</Menu.Item>
              <Menu.Item value="duplicate">Duplicate</Menu.Item>
              <Menu.Item value="archive">Archive</Menu.Item>
              <Menu.Item value="delete" tone="destructive">
                Delete
              </Menu.Item>
            </Menu.Content>
          </Menu.Positioner>
        </Menu>
      </div>
      <output>Selected: {selected()}</output>
    </div>
  );
}
