// packages/react-tailwind/src/components/split-button/SplitButton.tsx
'use client';

import { Menu as MenuPrimitive } from '@ark-ui/react/menu';
import { cva } from 'class-variance-authority';
import type { ComponentProps, ComponentRef, ReactNode } from 'react';
import { createContext, forwardRef, useContext } from 'react';
import { cn } from '@/lib/moduix/cn';
import { ChevronDownIcon } from '@/lib/moduix/icons/ui';
import { OverlayPortal } from '@/lib/moduix/overlayPortal';
import { Button } from '../button';
import { Menu, MenuViewport } from '../menu';
import { menuContentVariants, menuPositionerVariants } from '../menu/Menu.variants';

type ButtonProps = ComponentProps<typeof Button>;
type SplitButtonVariant = Exclude<NonNullable<ButtonProps['variant']>, 'link'>;
type SplitButtonSize = Exclude<NonNullable<ButtonProps['size']>, 'icon-sm' | 'icon-md' | 'icon-lg'>;

type SplitButtonContextValue = {
  size: SplitButtonSize;
  variant: SplitButtonVariant;
};

type SplitButtonProps = Omit<ComponentProps<typeof Menu>, 'children'> & {
  'aria-label'?: string;
  'aria-labelledby'?: string;
  children?: ReactNode;
  className?: string;
  size?: SplitButtonSize;
  variant?: SplitButtonVariant;
};

type SplitButtonActionProps = Omit<ButtonProps, 'size' | 'variant'> & {
  size?: SplitButtonSize;
  variant?: SplitButtonVariant;
};

type SplitButtonTriggerProps = Omit<ComponentProps<typeof MenuPrimitive.Trigger>, 'asChild'> & {
  size?: SplitButtonSize;
  variant?: SplitButtonVariant;
};

type SplitButtonContentProps = ComponentProps<typeof MenuPrimitive.Content>;
type SplitButtonPositionerProps = ComponentProps<typeof MenuPrimitive.Positioner>;

const splitButtonTriggerVariants = cva(
  "relative min-w-0 ms-[calc(var(--moduix-button-border-width,var(--moduix-border-width-sm))*-1)] rounded-s-none motion-safe:[&:not([data-variant='link']):active]:[translate:none] before:pointer-events-none before:absolute before:inset-y-1.5 before:start-0 before:w-px before:bg-current before:opacity-[0.16] before:content-['']",
  {
    variants: {
      size: {
        xs: 'px-2',
        sm: 'px-2.5',
        md: 'px-3',
        lg: 'px-3.5',
        xl: 'px-4',
      },
      variant: {
        default: '',
        outline: 'before:opacity-0',
        secondary: '',
        destructive: '',
        'destructive-outline': 'before:opacity-0',
        ghost: '',
      },
    },
    defaultVariants: {
      size: 'md',
      variant: 'default',
    },
  },
);

const SplitButtonContext = createContext<SplitButtonContextValue | null>(null);

function useSplitButtonContext(componentName: string) {
  const context = useContext(SplitButtonContext);

  if (!context) {
    throw new Error(`${componentName} must be used within SplitButton.`);
  }

  return context;
}

const SplitButton = forwardRef<HTMLDivElement, SplitButtonProps>(function SplitButton(
  {
    children,
    className,
    positioning,
    size = 'md',
    variant = 'default',
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledby,
    ...props
  },
  ref,
) {
  return (
    <SplitButtonContext.Provider value={{ size, variant }}>
      <Menu positioning={{ placement: 'bottom-end', gutter: 4, ...positioning }} {...props}>
        <div
          ref={ref}
          role="group"
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledby}
          data-scope="split-button"
          data-part="root"
          data-slot="split-button-root"
          className={cn('inline-flex items-stretch', className)}
        >
          {children}
        </div>
      </Menu>
    </SplitButtonContext.Provider>
  );
});

const SplitButtonAction = forwardRef<ComponentRef<typeof Button>, SplitButtonActionProps>(
  function SplitButtonAction({ className, size, variant, ...props }, ref) {
    const context = useSplitButtonContext('SplitButtonAction');

    return (
      <Button
        ref={ref}
        size={size ?? context.size}
        variant={variant ?? context.variant}
        className={cn(
          "rounded-e-none motion-safe:[&:not([data-variant='link']):active]:[translate:none]",
          className,
        )}
        {...props}
        data-slot="split-button-action"
      />
    );
  },
);

const SplitButtonTrigger = forwardRef<
  ComponentRef<typeof MenuPrimitive.Trigger>,
  SplitButtonTriggerProps
>(function SplitButtonTrigger(
  { children, className, size, variant, 'aria-label': ariaLabel, ...props },
  ref,
) {
  const context = useSplitButtonContext('SplitButtonTrigger');
  const resolvedSize = size ?? context.size;
  const resolvedVariant = variant ?? context.variant;
  const isIconOnly = children == null;

  return (
    <MenuPrimitive.Trigger
      ref={ref}
      asChild
      aria-label={isIconOnly ? (ariaLabel ?? 'More actions') : ariaLabel}
      className={cn(
        splitButtonTriggerVariants({ size: resolvedSize, variant: resolvedVariant }),
        className,
      )}
      {...props}
      data-slot="split-button-trigger"
    >
      <Button size={resolvedSize} variant={resolvedVariant}>
        {children ?? <ChevronDownIcon />}
      </Button>
    </MenuPrimitive.Trigger>
  );
});

const SplitButtonPositioner = forwardRef<
  ComponentRef<typeof MenuPrimitive.Positioner>,
  SplitButtonPositionerProps
>(function SplitButtonPositioner({ className, ...props }, ref) {
  return (
    <OverlayPortal>
      <MenuPrimitive.Positioner
        ref={ref}
        className={cn(menuPositionerVariants(), className)}
        {...props}
        data-slot="split-button-positioner"
      />
    </OverlayPortal>
  );
});

const SplitButtonContent = forwardRef<
  ComponentRef<typeof MenuPrimitive.Content>,
  SplitButtonContentProps
>(function SplitButtonContent({ asChild, children, className, ...props }, ref) {
  return (
    <MenuPrimitive.Content
      ref={ref}
      asChild={asChild}
      className={cn(menuContentVariants(), className)}
      {...props}
      data-slot="split-button-content"
    >
      {asChild ? children : <MenuViewport>{children}</MenuViewport>}
    </MenuPrimitive.Content>
  );
});

export {
  SplitButton,
  SplitButtonAction,
  SplitButtonContent,
  SplitButtonPositioner,
  SplitButtonTrigger,
};

// packages/solid-tailwind/src/components/split-button/SplitButton.tsx
import { Menu as MenuPrimitive } from '@ark-ui/solid/menu';
import { cva } from 'class-variance-authority';
import type { Accessor, ComponentProps, JSX } from 'solid-js';
import { children, createContext, splitProps, useContext } from 'solid-js';
import { cn } from '@/lib/moduix/cn';
import { ChevronDownIcon } from '@/lib/moduix/icons/ui';
import { OverlayPortal } from '@/lib/moduix/overlayPortal';
import { Button } from '../button';
import { Menu, MenuViewport } from '../menu';
import { menuContentVariants, menuPositionerVariants } from '../menu/Menu.variants';

type ButtonProps = ComponentProps<typeof Button>;
type SplitButtonVariant = Exclude<NonNullable<ButtonProps['variant']>, 'link'>;
type SplitButtonSize = Exclude<NonNullable<ButtonProps['size']>, 'icon-sm' | 'icon-md' | 'icon-lg'>;

type SplitButtonContextValue = {
  size: Accessor<SplitButtonSize>;
  variant: Accessor<SplitButtonVariant>;
};

type SplitButtonProps = Omit<ComponentProps<typeof Menu>, 'children'> & {
  'aria-label'?: string;
  'aria-labelledby'?: string;
  children?: JSX.Element;
  class?: string;
  ref?: HTMLDivElement | ((element: HTMLDivElement) => void);
  size?: SplitButtonSize;
  variant?: SplitButtonVariant;
};

type SplitButtonActionProps = Omit<ButtonProps, 'size' | 'variant'> & {
  size?: SplitButtonSize;
  variant?: SplitButtonVariant;
};

type SplitButtonTriggerProps = Omit<
  ComponentProps<typeof MenuPrimitive.Trigger>,
  'asChild' | 'children' | 'class'
> & {
  children?: JSX.Element;
  class?: string;
  size?: SplitButtonSize;
  variant?: SplitButtonVariant;
};

type SplitButtonContentProps = ComponentProps<typeof MenuPrimitive.Content>;
type SplitButtonPositionerProps = ComponentProps<typeof MenuPrimitive.Positioner>;

const splitButtonTriggerVariants = cva(
  "relative min-w-0 ms-[calc(var(--moduix-button-border-width,var(--moduix-border-width-sm))*-1)] rounded-s-none motion-safe:[&:not([data-variant='link']):active]:[translate:none] before:pointer-events-none before:absolute before:inset-y-1.5 before:start-0 before:w-px before:bg-current before:opacity-[0.16] before:content-['']",
  {
    variants: {
      size: {
        xs: 'px-2',
        sm: 'px-2.5',
        md: 'px-3',
        lg: 'px-3.5',
        xl: 'px-4',
      },
      variant: {
        default: '',
        outline: 'before:opacity-0',
        secondary: '',
        destructive: '',
        'destructive-outline': 'before:opacity-0',
        ghost: '',
      },
    },
    defaultVariants: {
      size: 'md',
      variant: 'default',
    },
  },
);

const SplitButtonContext = createContext<SplitButtonContextValue>();

function useSplitButtonContext(componentName: string) {
  const context = useContext(SplitButtonContext);

  if (!context) {
    throw new Error(`${componentName} must be used within SplitButton.`);
  }

  return context;
}

function SplitButton(props: SplitButtonProps) {
  const [local, others] = splitProps(props, [
    'aria-label',
    'aria-labelledby',
    'children',
    'class',
    'onSelect',
    'positioning',
    'ref',
    'size',
    'variant',
  ]);

  return (
    <SplitButtonContext.Provider
      value={{
        size: () => local.size ?? 'md',
        variant: () => local.variant ?? 'default',
      }}
    >
      <Menu
        onSelect={local.onSelect}
        positioning={{ placement: 'bottom-end', gutter: 4, ...local.positioning }}
        {...others}
      >
        <div
          role="group"
          aria-label={local['aria-label']}
          aria-labelledby={local['aria-labelledby']}
          data-scope="split-button"
          data-part="root"
          data-slot="split-button-root"
          class={cn('inline-flex items-stretch', local.class)}
          ref={local.ref}
        >
          {local.children}
        </div>
      </Menu>
    </SplitButtonContext.Provider>
  );
}

function SplitButtonAction(props: SplitButtonActionProps) {
  const [local, others] = splitProps(props, ['class', 'size', 'variant']);
  const context = useSplitButtonContext('SplitButtonAction');

  return (
    <Button
      {...others}
      data-slot="split-button-action"
      size={local.size ?? context.size()}
      variant={local.variant ?? context.variant()}
      class={cn(
        "rounded-e-none motion-safe:[&:not([data-variant='link']):active]:[translate:none]",
        local.class,
      )}
    />
  );
}

function SplitButtonTrigger(props: SplitButtonTriggerProps) {
  const [local, others] = splitProps(props, [
    'aria-label',
    'children',
    'class',
    'ref',
    'size',
    'variant',
  ]);
  const context = useSplitButtonContext('SplitButtonTrigger');
  const resolvedChildren = children(() => local.children);
  const resolvedSize = () => local.size ?? context.size();
  const resolvedVariant = () => local.variant ?? context.variant();
  const isIconOnly = () => resolvedChildren() == null;
  const ariaLabel = () =>
    isIconOnly() ? (local['aria-label'] ?? 'More actions') : local['aria-label'];
  const triggerClass = () =>
    cn(
      splitButtonTriggerVariants({ size: resolvedSize(), variant: resolvedVariant() }),
      local.class,
    );

  return (
    <MenuPrimitive.Trigger
      {...others}
      asChild={(triggerProps) => (
        <Button
          {...triggerProps()}
          ref={local.ref}
          data-slot="split-button-trigger"
          size={resolvedSize()}
          variant={resolvedVariant()}
          class={triggerClass()}
          aria-label={ariaLabel()}
        >
          {resolvedChildren() ?? <ChevronDownIcon />}
        </Button>
      )}
      data-slot="split-button-trigger"
      aria-label={ariaLabel()}
      class={triggerClass()}
    />
  );
}

function SplitButtonPositioner(props: SplitButtonPositionerProps) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <OverlayPortal>
      <MenuPrimitive.Positioner
        {...others}
        data-slot="split-button-positioner"
        class={cn(menuPositionerVariants(), local.class)}
      />
    </OverlayPortal>
  );
}

function SplitButtonContent(props: SplitButtonContentProps) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);

  return (
    <MenuPrimitive.Content
      {...others}
      asChild={local.asChild}
      data-slot="split-button-content"
      class={cn(menuContentVariants(), local.class)}
    >
      {local.asChild ? local.children : <MenuViewport>{local.children}</MenuViewport>}
    </MenuPrimitive.Content>
  );
}

export {
  SplitButton,
  SplitButtonAction,
  SplitButtonContent,
  SplitButtonPositioner,
  SplitButtonTrigger,
};
