// apps/docs/docs/en/docs/_snippets/stack/growing-child-stack.tsx
import { Skeleton, Stack } from '@moduix/react';

export default function StackFillDemo() {
  return (
    <Stack direction="row" align="center" gap={12} style={{ inlineSize: '100%' }}>
      <Skeleton boxSize={40} borderRadius="var(--moduix-radius-full)" />
      <Stack direction="column" gap={8} fill>
        <Skeleton width="48%" height={16} />
        <Skeleton height={14} />
      </Stack>
    </Stack>
  );
}

// website/snippets/stack/vue/growing-child-stack.vue
<script setup lang="ts">
import { Skeleton } from '@moduix/vue/skeleton';
import { Stack } from '@moduix/vue/stack';
</script>

<template>
  <Stack direction="row" align="center" :gap="12" style="inline-size: 100%">
    <Skeleton :box-size="40" border-radius="var(--moduix-radius-full)" />
    <Stack direction="column" :gap="8" fill>
      <Skeleton width="48%" :height="16" />
      <Skeleton :height="14" />
    </Stack>
  </Stack>
</template>
