// website/src/components/examples/date-input/date-input.tsx
import type { CssProperty } from '../../mdx/reference';
import { CSSPropertiesReferenceTable } from '../../mdx/reference';

const dateInputOverrideCssProperties: CssProperty[] = [
  {
    name: '--moduix-date-input-bg',
    defaultValue: 'var(--moduix-color-background)',
    description: 'Controls the control background.',
  },
  {
    name: '--moduix-date-input-border-color',
    defaultValue: 'var(--moduix-color-border)',
    description: 'Controls the default control border color.',
  },
  {
    name: '--moduix-date-input-border-color-invalid',
    defaultValue: 'var(--moduix-color-destructive)',
    description: 'Controls invalid border and focus ring color.',
  },
  {
    name: '--moduix-date-input-border-style',
    defaultValue: 'solid',
    description: 'Controls the control border style.',
  },
  {
    name: '--moduix-date-input-border-width',
    defaultValue: 'var(--moduix-border-width-sm)',
    description: 'Controls the control border width.',
  },
  {
    name: '--moduix-date-input-color',
    defaultValue: 'var(--moduix-color-foreground)',
    description: 'Controls the control text color.',
  },
  {
    name: '--moduix-date-input-control-height',
    defaultValue: 'var(--moduix-size-md)',
    description: 'Controls the minimum control height.',
  },
  {
    name: '--moduix-date-input-control-width',
    defaultValue: '100%',
    description: 'Controls the visual control width.',
  },
  {
    name: '--moduix-date-input-disabled-opacity',
    defaultValue: 'var(--moduix-opacity-disabled)',
    description: 'Controls disabled root opacity.',
  },
  {
    name: '--moduix-date-input-focus-ring-color',
    defaultValue: 'var(--moduix-color-ring)',
    description: 'Controls the focused control outline color.',
  },
  {
    name: '--moduix-date-input-focus-ring-offset',
    defaultValue: 'var(--moduix-focus-ring-inset-offset)',
    description: 'Controls the focused control outline offset.',
  },
  {
    name: '--moduix-date-input-focus-ring-width',
    defaultValue: 'var(--moduix-date-input-border-width, var(--moduix-border-width-sm))',
    description: 'Controls the focused control outline width.',
  },
  {
    name: '--moduix-date-input-gap',
    defaultValue: 'var(--moduix-spacing-1)',
    description: 'Controls spacing between root children.',
  },
  {
    name: '--moduix-date-input-label-color',
    defaultValue: 'var(--moduix-color-foreground)',
    description: 'Controls label text color.',
  },
  {
    name: '--moduix-date-input-label-font-size',
    defaultValue: 'var(--moduix-text-sm)',
    description: 'Controls label font size.',
  },
  {
    name: '--moduix-date-input-label-font-weight',
    defaultValue: 'var(--moduix-weight-medium)',
    description: 'Controls label font weight.',
  },
  {
    name: '--moduix-date-input-label-line-height',
    defaultValue: 'var(--moduix-line-height-text-sm)',
    description: 'Controls label line height.',
  },
  {
    name: '--moduix-date-input-max-width',
    defaultValue: 'none',
    description: 'Controls root maximum width.',
  },
  {
    name: '--moduix-date-input-padding-x',
    defaultValue: 'var(--moduix-spacing-3)',
    description: 'Controls horizontal control padding.',
  },
  {
    name: '--moduix-date-input-padding-y',
    defaultValue: 'var(--moduix-spacing-1)',
    description: 'Controls vertical control padding.',
  },
  {
    name: '--moduix-date-input-placeholder-color',
    defaultValue: 'var(--moduix-color-muted-foreground)',
    description: 'Controls placeholder segment color.',
  },
  {
    name: '--moduix-date-input-radius',
    defaultValue: 'var(--moduix-radius-md)',
    description: 'Controls the control corner radius.',
  },
  {
    name: '--moduix-date-input-segment-bg-focus',
    defaultValue: 'color-mix(in oklab, var(--moduix-color-ring) 18%, transparent)',
    description: 'Controls focused segment background.',
  },
  {
    name: '--moduix-date-input-segment-color',
    defaultValue: 'currentColor',
    description: 'Controls segment text color.',
  },
  {
    name: '--moduix-date-input-segment-color-focus',
    defaultValue: 'var(--moduix-color-foreground)',
    description: 'Controls focused segment text color.',
  },
  {
    name: '--moduix-date-input-segment-gap',
    defaultValue: 'var(--moduix-border-width-md)',
    description: 'Controls spacing between date segments.',
  },
  {
    name: '--moduix-date-input-segment-line-height',
    defaultValue: 'var(--moduix-line-height-text-md)',
    description: 'Controls segment line height.',
  },
  {
    name: '--moduix-date-input-segment-min-width',
    defaultValue: '2ch',
    description: 'Controls segment minimum width.',
  },
  {
    name: '--moduix-date-input-segment-padding-x',
    defaultValue: 'var(--moduix-spacing-1)',
    description: 'Controls segment horizontal padding.',
  },
  {
    name: '--moduix-date-input-segment-padding-y',
    defaultValue: '0',
    description: 'Controls segment vertical padding.',
  },
  {
    name: '--moduix-date-input-segment-radius',
    defaultValue: 'var(--moduix-radius-sm)',
    description: 'Controls segment corner radius.',
  },
  {
    name: '--moduix-date-input-separator-color',
    defaultValue: 'var(--moduix-color-muted-foreground)',
    description: 'Controls literal and separator text color.',
  },
  {
    name: '--moduix-date-input-transition',
    defaultValue: 'var(--moduix-transition-default)',
    description: 'Controls date input transition timing.',
  },
  {
    name: '--moduix-date-input-width',
    defaultValue: '100%',
    description: 'Controls root width.',
  },
];

export function DateInputCssPropertiesPanel() {
  return <CSSPropertiesReferenceTable properties={dateInputOverrideCssProperties} />;
}

// packages/solid-tailwind/src/components/date-input/DateInput.tsx
import {
  DateInput as DateInputPrimitive,
  type DateInputDateValue,
  useDateInput,
  useDateInputContext,
} from '@ark-ui/solid/date-input';
import type { ComponentProps } from 'solid-js';
import { splitProps } from 'solid-js';
import { cn } from '@/lib/moduix/cn';

function DateInputRoot(props: ComponentProps<typeof DateInputPrimitive.Root>) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);

  return (
    <DateInputPrimitive.Root
      asChild={local.asChild}
      class={cn(
        'inline-flex w-full max-w-none flex-col items-start gap-1 data-disabled:opacity-50',
        local.class,
      )}
      {...others}
      data-slot="date-input-root"
    >
      {local.children}
    </DateInputPrimitive.Root>
  );
}

function DateInputRootProvider(props: ComponentProps<typeof DateInputPrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);

  return (
    <DateInputPrimitive.RootProvider
      asChild={local.asChild}
      class={cn(
        'inline-flex w-full max-w-none flex-col items-start gap-1 data-disabled:opacity-50',
        local.class,
      )}
      {...others}
      data-slot="date-input-root-provider"
    >
      {local.children}
    </DateInputPrimitive.RootProvider>
  );
}

function DateInputLabel(props: ComponentProps<typeof DateInputPrimitive.Label>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DateInputPrimitive.Label
      class={cn('text-sm leading-5 font-medium text-foreground', local.class)}
      {...others}
      data-slot="date-input-label"
    />
  );
}

function DateInputControl(props: ComponentProps<typeof DateInputPrimitive.Control>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DateInputPrimitive.Control
      class={cn(
        'box-border inline-flex min-h-control-md w-full items-center rounded-md border border-border bg-background px-3 py-1 text-foreground outline-1 -outline-offset-1 outline-transparent transition-[border-color,outline-color,opacity] duration-200 ease-in-out focus-within:outline-ring data-disabled:pointer-events-none data-focus:outline-ring data-invalid:border-destructive data-invalid:focus-within:outline-destructive data-invalid:data-focus:outline-destructive motion-reduce:transition-none',
        local.class,
      )}
      {...others}
      data-slot="date-input-control"
    />
  );
}

function DateInputSegmentGroup(props: ComponentProps<typeof DateInputPrimitive.SegmentGroup>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DateInputPrimitive.SegmentGroup
      class={cn('inline-flex items-center gap-0.5 tabular-nums', local.class)}
      {...others}
      data-slot="date-input-segment-group"
    />
  );
}

function DateInputSegment(props: ComponentProps<typeof DateInputPrimitive.Segment>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <DateInputPrimitive.Segment
      class={cn(
        'min-w-[2ch] cursor-text rounded-sm px-1 py-0 text-center leading-6 text-current outline-0 transition-colors duration-200 ease-in-out [font:inherit] focus-visible:bg-ring/18 focus-visible:text-foreground data-disabled:cursor-default data-placeholder-shown:text-muted-foreground data-readonly:cursor-default data-[type=literal]:pointer-events-none data-[type=literal]:min-w-auto data-[type=literal]:bg-transparent data-[type=literal]:px-0 data-[type=literal]:text-muted-foreground motion-reduce:transition-none',
        local.class,
      )}
      {...others}
      data-slot="date-input-segment"
    />
  );
}

type DateInputSegmentsProps = Omit<
  ComponentProps<typeof DateInputPrimitive.SegmentGroup>,
  'asChild' | 'children'
>;

function DateInputSegments(props: DateInputSegmentsProps) {
  return (
    <DateInputSegmentGroup {...props}>
      <DateInputPrimitive.SegmentContext>
        {(segment) => <DateInputSegment segment={segment} />}
      </DateInputPrimitive.SegmentContext>
    </DateInputSegmentGroup>
  );
}

function DateInputSeparator(props: ComponentProps<'span'>) {
  const [local, others] = splitProps(props, ['aria-hidden', 'class', 'role']);

  return (
    <span
      aria-hidden={local['aria-hidden'] ?? true}
      role={local.role ?? 'presentation'}
      class={cn('text-muted-foreground select-none', local.class)}
      {...others}
      data-slot="date-input-separator"
    />
  );
}

const DateInput = Object.assign(DateInputRoot, {
  Root: DateInputRoot,
  RootProvider: DateInputRootProvider,
  HiddenInput: DateInputPrimitive.HiddenInput,
  Label: DateInputLabel,
  Control: DateInputControl,
  SegmentGroup: DateInputSegmentGroup,
  Segment: DateInputSegment,
  Segments: DateInputSegments,
  Separator: DateInputSeparator,
  Context: DateInputPrimitive.Context,
  SegmentContext: DateInputPrimitive.SegmentContext,
});

export { DateInput, type DateInputDateValue, useDateInput, useDateInputContext };
