// website/src/components/examples/qr-code/input.tsx
import { Input } from '@moduix/react/input';
import { QrCode } from '@moduix/react/qr-code';
import { useState } from 'react';
import { PreviewMeta } from '@/components/mdx/Components';
import styles from '@/components/examples/qr-code/component-input.module.css';

export default function InputQrCodeDemo() {
  const [value, setValue] = useState('https://moduix.dev/docs/qr-code');

  return (
    <div className={styles.stack}>
      <Input
        aria-label="QR code content"
        value={value}
        onChange={(event) => setValue(event.currentTarget.value)}
        className={styles.input}
      />
      <QrCode value={value}>
        <QrCode.Frame role="img" aria-label="QR code for the entered content">
          <QrCode.Pattern />
        </QrCode.Frame>
      </QrCode>
      <PreviewMeta>
        <output>Encoded content: {value || 'empty'}</output>
      </PreviewMeta>
    </div>
  );
}

// website/snippets/qr-code/solid/input.tsx
import { QrCode } from '@moduix/solid/qr-code';
import { createSignal } from 'solid-js';

export default function InputQrCodeDemo() {
  const [value, setValue] = createSignal('https://moduix.dev/docs/qr-code');

  return (
    <>
      <input
        aria-label="QR code content"
        value={value()}
        onInput={(event) => setValue(event.currentTarget.value)}
      />
      <QrCode value={value()}>
        <QrCode.Frame role="img" aria-label="QR code for the entered content">
          <QrCode.Pattern />
        </QrCode.Frame>
      </QrCode>
      <output>Encoded content: {value() || 'empty'}</output>
    </>
  );
}
