// apps/docs/content/docs/_snippets/switch/controlled.tsx
/* eslint-disable no-unused-vars, no-unused-expressions */
//#region demo

const initialChecked = true;
const onCheckedChange = (details) => setChecked(details.checked);

import { Switch } from '@moduix/react';
import { useState } from 'react';
import styles from './switch-demo.module.css';

export function ControlledSwitchDemo() {
  const [checked, setChecked] = useState(true);

  return (
    <div className={styles.stack}>
      <Switch checked={checked} onCheckedChange={(details) => setChecked(details.checked)}>
        <Switch.Control />
        <Switch.Label>{checked ? 'On' : 'Off'}</Switch.Label>
        <Switch.HiddenInput />
      </Switch>
      <span className={styles.hint}>Current value: {String(checked)}</span>
    </div>
  );
}

//#endregion

// website/snippets/switch/solid/controlled.tsx
import { Switch } from '@moduix/solid/switch';
import { createSignal } from 'solid-js';
import styles from '@/components/examples/switch/switch-controlled.module.css';

export default function ControlledSwitchDemo() {
  const [checked, setChecked] = createSignal(true);

  return (
    <div class={styles.stack}>
      <Switch checked={checked()} onCheckedChange={(details) => setChecked(details.checked)}>
        <Switch.Control />
        <Switch.Label>{checked() ? 'On' : 'Off'}</Switch.Label>
        <Switch.HiddenInput />
      </Switch>
      <output>Current value: {String(checked())}</output>
    </div>
  );
}
