// packages/react/src/components/slider/Slider.tsx
'use client';

import { Slider as SliderPrimitive, useSlider, useSliderContext } from '@ark-ui/react/slider';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef } from 'react';
import { forwardRef } from 'react';
import styles from './Slider.module.css';

const SliderRoot = forwardRef<
  ComponentRef<typeof SliderPrimitive.Root>,
  ComponentProps<typeof SliderPrimitive.Root>
>(function SliderRoot({ className, readOnly, ...props }, ref) {
  return (
    <SliderPrimitive.Root
      ref={ref}
      data-slot="slider-root"
      data-readonly={readOnly ? '' : undefined}
      className={clsx(styles.root, className)}
      readOnly={readOnly}
      {...props}
    />
  );
});

const SliderRootProvider = forwardRef<
  ComponentRef<typeof SliderPrimitive.RootProvider>,
  ComponentProps<typeof SliderPrimitive.RootProvider>
>(function SliderRootProvider({ className, ...props }, ref) {
  return (
    <SliderPrimitive.RootProvider
      ref={ref}
      data-slot="slider-root-provider"
      className={clsx(styles.root, className)}
      {...props}
    />
  );
});

const SliderLabel = forwardRef<
  ComponentRef<typeof SliderPrimitive.Label>,
  ComponentProps<typeof SliderPrimitive.Label>
>(function SliderLabel({ className, ...props }, ref) {
  return (
    <SliderPrimitive.Label
      ref={ref}
      data-slot="slider-label"
      className={clsx(styles.label, className)}
      {...props}
    />
  );
});

const SliderValueText = forwardRef<
  ComponentRef<typeof SliderPrimitive.ValueText>,
  ComponentProps<typeof SliderPrimitive.ValueText>
>(function SliderValueText({ className, ...props }, ref) {
  return (
    <SliderPrimitive.ValueText
      ref={ref}
      data-slot="slider-value-text"
      className={clsx(styles.valueText, className)}
      {...props}
    />
  );
});

const SliderControl = forwardRef<
  ComponentRef<typeof SliderPrimitive.Control>,
  ComponentProps<typeof SliderPrimitive.Control>
>(function SliderControl({ className, ...props }, ref) {
  return (
    <SliderPrimitive.Control
      ref={ref}
      data-slot="slider-control"
      className={clsx(styles.control, className)}
      {...props}
    />
  );
});

const SliderTrack = forwardRef<
  ComponentRef<typeof SliderPrimitive.Track>,
  ComponentProps<typeof SliderPrimitive.Track>
>(function SliderTrack({ className, ...props }, ref) {
  return (
    <SliderPrimitive.Track
      ref={ref}
      data-slot="slider-track"
      className={clsx(styles.track, className)}
      {...props}
    />
  );
});

const SliderRange = forwardRef<
  ComponentRef<typeof SliderPrimitive.Range>,
  ComponentProps<typeof SliderPrimitive.Range>
>(function SliderRange({ className, ...props }, ref) {
  return (
    <SliderPrimitive.Range
      ref={ref}
      data-slot="slider-range"
      className={clsx(styles.range, className)}
      {...props}
    />
  );
});

const SliderThumb = forwardRef<
  ComponentRef<typeof SliderPrimitive.Thumb>,
  ComponentProps<typeof SliderPrimitive.Thumb>
>(function SliderThumb({ asChild, children, className, ...props }, ref) {
  return (
    <SliderPrimitive.Thumb
      ref={ref}
      asChild={asChild}
      data-slot="slider-thumb"
      className={clsx(styles.thumb, className)}
      {...props}
    >
      {children}
    </SliderPrimitive.Thumb>
  );
});

function SliderThumbs({ className }: { className?: string }) {
  const slider = useSliderContext();

  return slider.value.map((_, index) => (
    <SliderThumb key={index} index={index} className={className}>
      <SliderPrimitive.HiddenInput />
    </SliderThumb>
  ));
}

const SliderMarkerGroup = forwardRef<
  ComponentRef<typeof SliderPrimitive.MarkerGroup>,
  ComponentProps<typeof SliderPrimitive.MarkerGroup>
>(function SliderMarkerGroup({ className, ...props }, ref) {
  return (
    <SliderPrimitive.MarkerGroup
      ref={ref}
      data-slot="slider-marker-group"
      className={clsx(styles.markerGroup, className)}
      {...props}
    />
  );
});

const SliderMarker = forwardRef<
  ComponentRef<typeof SliderPrimitive.Marker>,
  ComponentProps<typeof SliderPrimitive.Marker>
>(function SliderMarker({ className, ...props }, ref) {
  return (
    <SliderPrimitive.Marker
      ref={ref}
      data-slot="slider-marker"
      className={clsx(styles.marker, className)}
      {...props}
    />
  );
});

const SliderDraggingIndicator = forwardRef<
  ComponentRef<typeof SliderPrimitive.DraggingIndicator>,
  ComponentProps<typeof SliderPrimitive.DraggingIndicator>
>(function SliderDraggingIndicator({ className, ...props }, ref) {
  return (
    <SliderPrimitive.DraggingIndicator
      ref={ref}
      data-slot="slider-dragging-indicator"
      className={clsx(styles.draggingIndicator, className)}
      {...props}
    />
  );
});

const Slider = Object.assign(SliderRoot, {
  Root: SliderRoot,
  RootProvider: SliderRootProvider,
  Context: SliderPrimitive.Context,
  useSlider,
  useSliderContext,
  Label: SliderLabel,
  ValueText: SliderValueText,
  Control: SliderControl,
  HiddenInput: SliderPrimitive.HiddenInput,
  Track: SliderTrack,
  Range: SliderRange,
  Thumb: SliderThumb,
  Thumbs: SliderThumbs,
  MarkerGroup: SliderMarkerGroup,
  Marker: SliderMarker,
  DraggingIndicator: SliderDraggingIndicator,
});

export { Slider, useSlider, useSliderContext };

// packages/solid/src/components/slider/Slider.tsx
import { Slider as SliderPrimitive, useSlider, useSliderContext } from '@ark-ui/solid/slider';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { Index, splitProps } from 'solid-js';
import styles from './Slider.module.css';

function SliderRoot(props: ComponentProps<typeof SliderPrimitive.Root>) {
  const [local, others] = splitProps(props, [
    'asChild',
    'children',
    'class',
    'defaultValue',
    'readOnly',
    'value',
  ]);

  return (
    <SliderPrimitive.Root
      asChild={local.asChild}
      defaultValue={local.defaultValue}
      value={local.value}
      class={clsx(styles.root, local.class)}
      readOnly={local.readOnly}
      {...others}
      data-readonly={local.readOnly ? '' : undefined}
      data-slot="slider-root"
    >
      {local.children}
    </SliderPrimitive.Root>
  );
}

function SliderRootProvider(props: ComponentProps<typeof SliderPrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['asChild', 'class', 'value']);

  return (
    <SliderPrimitive.RootProvider
      asChild={local.asChild}
      value={local.value}
      class={clsx(styles.root, local.class)}
      {...others}
      data-slot="slider-root-provider"
    />
  );
}

function SliderLabel(props: ComponentProps<typeof SliderPrimitive.Label>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.Label
      class={clsx(styles.label, local.class)}
      {...others}
      data-slot="slider-label"
    />
  );
}

function SliderValueText(props: ComponentProps<typeof SliderPrimitive.ValueText>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.ValueText
      class={clsx(styles.valueText, local.class)}
      {...others}
      data-slot="slider-value-text"
    />
  );
}

function SliderControl(props: ComponentProps<typeof SliderPrimitive.Control>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.Control
      class={clsx(styles.control, local.class)}
      {...others}
      data-slot="slider-control"
    />
  );
}

function SliderTrack(props: ComponentProps<typeof SliderPrimitive.Track>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.Track
      class={clsx(styles.track, local.class)}
      {...others}
      data-slot="slider-track"
    />
  );
}

function SliderRange(props: ComponentProps<typeof SliderPrimitive.Range>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.Range
      class={clsx(styles.range, local.class)}
      {...others}
      data-slot="slider-range"
    />
  );
}

function SliderThumb(props: ComponentProps<typeof SliderPrimitive.Thumb>) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);

  return (
    <SliderPrimitive.Thumb
      asChild={local.asChild}
      class={clsx(styles.thumb, local.class)}
      {...others}
      data-slot="slider-thumb"
    >
      {local.children}
    </SliderPrimitive.Thumb>
  );
}

function SliderThumbs(props: { class?: string }) {
  const slider = useSliderContext();

  return (
    <Index each={slider().value}>
      {(_, index) => (
        <SliderThumb index={index} class={props.class}>
          <SliderPrimitive.HiddenInput />
        </SliderThumb>
      )}
    </Index>
  );
}

function SliderMarkerGroup(props: ComponentProps<typeof SliderPrimitive.MarkerGroup>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.MarkerGroup
      class={clsx(styles.markerGroup, local.class)}
      {...others}
      data-slot="slider-marker-group"
    />
  );
}

function SliderMarker(props: ComponentProps<typeof SliderPrimitive.Marker>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.Marker
      class={clsx(styles.marker, local.class)}
      {...others}
      data-slot="slider-marker"
    />
  );
}

function SliderDraggingIndicator(props: ComponentProps<typeof SliderPrimitive.DraggingIndicator>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <SliderPrimitive.DraggingIndicator
      class={clsx(styles.draggingIndicator, local.class)}
      {...others}
      data-slot="slider-dragging-indicator"
    />
  );
}

type SliderComponent = typeof SliderRoot & {
  Root: typeof SliderRoot;
  RootProvider: typeof SliderRootProvider;
  Context: typeof SliderPrimitive.Context;
  useSlider: typeof useSlider;
  useSliderContext: typeof useSliderContext;
  Label: typeof SliderLabel;
  ValueText: typeof SliderValueText;
  Control: typeof SliderControl;
  HiddenInput: typeof SliderPrimitive.HiddenInput;
  Track: typeof SliderTrack;
  Range: typeof SliderRange;
  Thumb: typeof SliderThumb;
  Thumbs: typeof SliderThumbs;
  MarkerGroup: typeof SliderMarkerGroup;
  Marker: typeof SliderMarker;
  DraggingIndicator: typeof SliderDraggingIndicator;
};

const Slider: SliderComponent = Object.assign(SliderRoot, {
  Root: SliderRoot,
  RootProvider: SliderRootProvider,
  Context: SliderPrimitive.Context,
  useSlider,
  useSliderContext,
  Label: SliderLabel,
  ValueText: SliderValueText,
  Control: SliderControl,
  HiddenInput: SliderPrimitive.HiddenInput,
  Track: SliderTrack,
  Range: SliderRange,
  Thumb: SliderThumb,
  Thumbs: SliderThumbs,
  MarkerGroup: SliderMarkerGroup,
  Marker: SliderMarker,
  DraggingIndicator: SliderDraggingIndicator,
});

export { Slider, useSlider, useSliderContext };
