// packages/solid/src/components/toggle-group/ToggleGroup.tsx
import {
  ToggleGroup as ToggleGroupPrimitive,
  useToggleGroup,
  useToggleGroupContext,
} from '@ark-ui/solid/toggle-group';
import { clsx } from 'clsx';
import type { Accessor, ComponentProps } from 'solid-js';
import { createContext, splitProps, useContext } from 'solid-js';
import type { ToggleSize, ToggleVariant } from '../toggle/Toggle';
import toggleStyles from '../toggle/Toggle.module.css';
import styles from './ToggleGroup.module.css';

type ToggleGroupStyleContextValue = {
  variant: Accessor<ToggleVariant>;
  size: Accessor<ToggleSize>;
};

const ToggleGroupStyleContext = createContext<ToggleGroupStyleContextValue>({
  variant: (): ToggleVariant => 'default',
  size: (): ToggleSize => 'md',
});

type ToggleGroupRootProps = ComponentProps<typeof ToggleGroupPrimitive.Root> & {
  variant?: ToggleVariant;
  size?: ToggleSize;
};

type ToggleGroupRootProviderProps = ComponentProps<typeof ToggleGroupPrimitive.RootProvider> & {
  variant?: ToggleVariant;
  size?: ToggleSize;
};

type ToggleGroupItemProps = ComponentProps<typeof ToggleGroupPrimitive.Item> & {
  variant?: ToggleVariant;
  size?: ToggleSize;
};

function ToggleGroup(props: ToggleGroupRootProps) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class', 'size', 'variant']);
  const variant = () => local.variant ?? 'default';
  const size = () => local.size ?? 'md';

  return (
    <ToggleGroupStyleContext.Provider value={{ variant, size }}>
      <ToggleGroupPrimitive.Root
        asChild={local.asChild}
        {...others}
        data-slot="toggle-group-root"
        data-variant={variant()}
        data-size={size()}
        class={clsx(styles.root, local.class)}
      >
        {local.children}
      </ToggleGroupPrimitive.Root>
    </ToggleGroupStyleContext.Provider>
  );
}

function ToggleGroupRootProvider(props: ToggleGroupRootProviderProps) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class', 'size', 'variant']);
  const variant = () => local.variant ?? 'default';
  const size = () => local.size ?? 'md';

  return (
    <ToggleGroupStyleContext.Provider value={{ variant, size }}>
      <ToggleGroupPrimitive.RootProvider
        asChild={local.asChild}
        {...others}
        data-slot="toggle-group-root-provider"
        data-variant={variant()}
        data-size={size()}
        class={clsx(styles.root, local.class)}
      >
        {local.children}
      </ToggleGroupPrimitive.RootProvider>
    </ToggleGroupStyleContext.Provider>
  );
}

function ToggleGroupItem(props: ToggleGroupItemProps) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class', 'size', 'variant']);
  const inherited = useContext(ToggleGroupStyleContext);
  const variant = () => local.variant ?? inherited.variant();
  const size = () => local.size ?? inherited.size();

  return (
    <ToggleGroupPrimitive.Item
      asChild={local.asChild}
      {...others}
      data-slot="toggle-group-item"
      data-variant={variant()}
      data-size={size()}
      class={clsx(toggleStyles.root, styles.item, local.class)}
    >
      {local.children}
    </ToggleGroupPrimitive.Item>
  );
}

const ToggleGroupContext = ToggleGroupPrimitive.Context;

export {
  ToggleGroup,
  ToggleGroupContext,
  ToggleGroupItem,
  ToggleGroupRootProvider,
  useToggleGroup,
  useToggleGroupContext,
};
export type {
  ToggleGroupItemProps,
  ToggleGroupRootProps,
  ToggleGroupRootProviderProps,
  ToggleSize,
  ToggleVariant,
};

// packages/ui/src/components/ToggleGroup/ToggleGroup.tsx
import { ToggleGroup as ToggleGroupPrimitive } from '@base-ui/react/toggle-group';
import * as React from 'react';
import { mergeClassName } from '@/utils/mergeClassName';
import { Toggle } from '../Toggle';
import styles from './ToggleGroup.module.css';

type ToggleVariant = React.ComponentProps<typeof Toggle>['variant'];
type ToggleSize = React.ComponentProps<typeof Toggle>['size'];

const ToggleGroupContext = React.createContext<{
  variant: ToggleVariant;
  size: ToggleSize;
}>({
  variant: 'default',
  size: 'md',
});

function ToggleGroup({
  className,
  variant = 'default',
  size = 'md',
  ...props
}: ToggleGroupPrimitive.Props & {
  variant?: ToggleVariant;
  size?: ToggleSize;
}) {
  return (
    <ToggleGroupContext.Provider value={{ variant, size }}>
      <ToggleGroupPrimitive
        data-slot="toggle-group-root"
        data-variant={variant}
        data-size={size}
        className={mergeClassName(className, styles.root)}
        {...props}
      />
    </ToggleGroupContext.Provider>
  );
}

function ToggleGroupItem({
  className,
  variant,
  size,
  ...props
}: React.ComponentProps<typeof Toggle>) {
  const inherited = React.useContext(ToggleGroupContext);

  return (
    <Toggle
      data-slot="toggle-group-item"
      variant={variant ?? inherited.variant}
      size={size ?? inherited.size}
      className={mergeClassName(className, styles.item)}
      {...props}
    />
  );
}

export { ToggleGroup, ToggleGroupItem };
