// website/snippets/color-picker/vue/field-state.vue
<script setup lang="ts">
import {
  ColorPicker,
  parseColor,
  ColorPickerHiddenInput,
  ColorPickerLabel,
  ColorPickerControl,
  ColorPickerTrigger,
  ColorPickerPositioner,
  ColorPickerContent,
  ColorPickerArea,
  ColorPickerChannelInput,
} from '@moduix/vue/color-picker';
import { Field, FieldErrorText, FieldHelperText } from '@moduix/vue/field';
import styles from '@/components/examples/color-picker/color-picker-field-state.module.css';
</script>

<template>
  <Field :class="styles.root">
    <ColorPicker name="accent" required invalid :default-value="parseColor('#eb5e41')">
      <ColorPickerLabel>Accent color</ColorPickerLabel>
      <ColorPickerControl>
        <ColorPickerChannelInput channel="hex" />
        <ColorPickerTrigger aria-label="Open color picker" />
      </ColorPickerControl>
      <ColorPickerPositioner>
        <ColorPickerContent>
          <ColorPickerArea />
        </ColorPickerContent>
      </ColorPickerPositioner>
      <ColorPickerHiddenInput />
    </ColorPicker>
    <FieldHelperText>Used for generated charts and callouts.</FieldHelperText>
    <FieldErrorText>Choose an accent color.</FieldErrorText>
  </Field>
</template>

// apps/docs/docs/ru/docs/_snippets/color-picker/field-state.tsx
import { ColorPicker, parseColor } from '@moduix/react/color-picker';
import { Field } from '@moduix/react/field';

export default function FieldStateColorPickerDemo() {
  return (
    <Field>
      <ColorPicker name="accent" required invalid defaultValue={parseColor('#eb5e41')}>
        <ColorPicker.Label>Accent color</ColorPicker.Label>
        <ColorPicker.Control>
          <ColorPicker.ChannelInput channel="hex" />
          <ColorPicker.Trigger aria-label="Open color picker" />
        </ColorPicker.Control>
      </ColorPicker>
      <Field.HelperText>Used for generated charts and callouts.</Field.HelperText>
      <Field.ErrorText>Choose an accent color.</Field.ErrorText>
    </Field>
  );
}
