// website/snippets/highlight/vue/dynamic-query.vue
<script setup lang="ts">
import { Highlight } from '@moduix/vue/highlight';
import { Input } from '@moduix/vue/input';
import { Text } from '@moduix/vue/text';
import { ref } from 'vue';
import styles from '@/components/examples/highlight/highlight-dynamic-query.module.css';

const query = ref('component');
</script>

<template>
  <div :class="styles.stack">
    <Input v-model="query" aria-label="Search text" placeholder="Search text..." />
    <Text>
      <Highlight
        :query="query"
        text="With Ark UI, you can build accessible, custom components. Each component is fully typed and works seamlessly with React, Solid, Svelte, and Vue."
      />
    </Text>
  </div>
</template>

// website/src/components/examples/highlight/dynamic-query.tsx
import { Highlight } from '@moduix/react/highlight';
import { Input } from '@moduix/react/input';
import { Text } from '@moduix/react/text';
import { useState } from 'react';
import styles from '@/components/examples/highlight/highlight-dynamic-query.module.css';

export default function HighlightDynamicQueryDemo() {
  const [query, setQuery] = useState('component');

  return (
    <div className={styles.stack}>
      <Input
        aria-label="Search text"
        value={query}
        onChange={(event) => setQuery(event.currentTarget.value)}
        placeholder="Search text..."
      />
      <Text>
        <Highlight
          query={query}
          text="With Ark UI, you can build accessible, custom components. Each component is fully typed and works seamlessly with React, Solid, Svelte, and Vue."
        />
      </Text>
    </div>
  );
}
