// packages/ui/src/components/Stack/Stack.tsx
import type { ComponentPropsWithoutRef, CSSProperties, ElementType } from 'react';
import { clsx } from 'clsx';
import styles from './Stack.module.css';

type StackDirection = 'row' | 'column';

function Stack({
  as: Root = 'div',
  className,
  style,
  direction,
  gap,
  align,
  justify,
  wrap,
  fill,
  ...props
}: ComponentPropsWithoutRef<'div'> & {
  as?: ElementType;
  direction?:
    | StackDirection
    | {
        mobile?: StackDirection;
        desktop?: StackDirection;
      };
  gap?: number | string;
  align?: CSSProperties['alignItems'];
  justify?: CSSProperties['justifyContent'];
  wrap?: CSSProperties['flexWrap'];
  fill?: boolean;
}) {
  const responsiveDirection =
    typeof direction === 'string' ? { mobile: direction, desktop: direction } : direction;

  return (
    <Root
      data-slot="stack-root"
      className={clsx(styles.root, className)}
      style={
        {
          '--stack-direction-desktop':
            responsiveDirection?.desktop ?? responsiveDirection?.mobile ?? 'column',
          '--stack-direction-mobile':
            responsiveDirection?.mobile ?? responsiveDirection?.desktop ?? 'column',
          '--stack-flex': fill ? '1 1 0' : 'initial',
          gap,
          alignItems: align,
          justifyContent: justify,
          flexWrap: wrap,
          ...style,
        } as CSSProperties
      }
      {...props}
    />
  );
}

export { Stack };

// packages/vue/src/components/stack/Stack.vue
<script setup lang="ts">
import { ark } from '@ark-ui/vue/factory';
import type { HTMLArkProps } from '@ark-ui/vue/factory';
import { clsx } from 'clsx';
import { computed, useAttrs } from 'vue';
import type { CSSProperties, HTMLAttributes, StyleValue } from 'vue';
import styles from './Stack.module.css';

type StackDirection = 'row' | 'row-reverse' | 'column' | 'column-reverse';

type ResponsiveDirection = {
  mobile?: StackDirection;
  desktop?: StackDirection;
};

defineOptions({ inheritAttrs: false });

export interface Props extends /* @vue-ignore */ HTMLArkProps<'div'> {
  align?: CSSProperties['alignItems'];
  class?: HTMLAttributes['class'];
  direction?: StackDirection | ResponsiveDirection;
  fill?: boolean;
  gap?: number | string;
  justify?: CSSProperties['justifyContent'];
  style?: StyleValue;
  wrap?: CSSProperties['flexWrap'];
}

const {
  align,
  class: className,
  direction,
  fill = undefined,
  gap,
  justify,
  style,
  wrap,
} = defineProps<Props>();
defineSlots<{ default?: () => unknown }>();

const attrs = useAttrs();

const stackStyle = computed<StyleValue>(() => [
  {
    '--moduix-stack-direction-desktop':
      (typeof direction === 'string' ? direction : (direction?.desktop ?? direction?.mobile)) ??
      'column',
    '--moduix-stack-direction-mobile':
      (typeof direction === 'string' ? direction : (direction?.mobile ?? direction?.desktop)) ??
      'column',
    ...(fill == null ? {} : { '--moduix-stack-flex': fill ? '1 1 0%' : 'initial' }),
    gap: typeof gap === 'number' ? `${gap}px` : gap,
    alignItems: align,
    justifyContent: justify,
    flexWrap: wrap,
  },
  style,
]);
</script>

<template>
  <ark.div
    v-bind="attrs"
    :class="clsx(styles.root, className)"
    :style="stackStyle"
    data-scope="stack"
    data-part="root"
    data-slot="stack-root"
  >
    <slot />
  </ark.div>
</template>
