// packages/ui/src/components/collapsible/Collapsible.tsx
import type { ComponentProps, ComponentRef } from 'react';
import {
  Collapsible as CollapsiblePrimitive,
  useCollapsible,
  useCollapsibleContext,
} from '@ark-ui/react/collapsible';
import { clsx } from 'clsx';
import { forwardRef } from 'react';
import { ChevronRightIcon } from '@/lib/moduix/icons/ui';
import { normalizeClassName } from '@/lib/moduix/normalizeClassName';
import styles from './Collapsible.module.css';

const CollapsibleRoot = forwardRef<
  ComponentRef<typeof CollapsiblePrimitive.Root>,
  ComponentProps<typeof CollapsiblePrimitive.Root>
>(function CollapsibleRoot({ className, ...props }, ref) {
  return (
    <CollapsiblePrimitive.Root
      ref={ref}
      data-slot="collapsible-root"
      className={clsx(styles.root, normalizeClassName(className))}
      {...props}
    />
  );
});

const CollapsibleRootProvider = forwardRef<
  ComponentRef<typeof CollapsiblePrimitive.RootProvider>,
  ComponentProps<typeof CollapsiblePrimitive.RootProvider>
>(function CollapsibleRootProvider({ className, ...props }, ref) {
  return (
    <CollapsiblePrimitive.RootProvider
      ref={ref}
      data-slot="collapsible-root-provider"
      className={clsx(styles.root, normalizeClassName(className))}
      {...props}
    />
  );
});

const CollapsibleTrigger = forwardRef<
  ComponentRef<typeof CollapsiblePrimitive.Trigger>,
  ComponentProps<typeof CollapsiblePrimitive.Trigger>
>(function CollapsibleTrigger({ className, ...props }, ref) {
  return (
    <CollapsiblePrimitive.Trigger
      ref={ref}
      data-slot="collapsible-trigger"
      className={clsx(styles.trigger, normalizeClassName(className))}
      {...props}
    />
  );
});

const CollapsibleIndicator = forwardRef<
  ComponentRef<typeof CollapsiblePrimitive.Indicator>,
  ComponentProps<typeof CollapsiblePrimitive.Indicator>
>(function CollapsibleIndicator({ className, children, ...props }, ref) {
  return (
    <CollapsiblePrimitive.Indicator
      ref={ref}
      data-slot="collapsible-indicator"
      className={clsx(styles.indicator, normalizeClassName(className))}
      {...props}
    >
      {children ?? <ChevronRightIcon />}
    </CollapsiblePrimitive.Indicator>
  );
});

const CollapsibleContent = forwardRef<
  ComponentRef<typeof CollapsiblePrimitive.Content>,
  ComponentProps<typeof CollapsiblePrimitive.Content>
>(function CollapsibleContent({ className, ...props }, ref) {
  return (
    <CollapsiblePrimitive.Content
      ref={ref}
      data-slot="collapsible-content"
      className={clsx(styles.content, normalizeClassName(className))}
      {...props}
    />
  );
});

const CollapsibleContext = CollapsiblePrimitive.Context;

const Collapsible = Object.assign(CollapsibleRoot, {
  Root: CollapsibleRoot,
  RootProvider: CollapsibleRootProvider,
  Trigger: CollapsibleTrigger,
  Indicator: CollapsibleIndicator,
  Content: CollapsibleContent,
  Context: CollapsibleContext,
});

export { Collapsible, useCollapsible, useCollapsibleContext };
export type {
  CollapsibleOpenChangeDetails,
  UseCollapsibleContext,
  UseCollapsibleProps,
  UseCollapsibleReturn,
} from '@ark-ui/react/collapsible';

// packages/solid/src/components/collapsible/Collapsible.tsx
import {
  Collapsible as CollapsiblePrimitive,
  useCollapsible,
  useCollapsibleContext,
} from '@ark-ui/solid/collapsible';
import type { HTMLArkProps } from '@ark-ui/solid/factory';
import { ark } from '@ark-ui/solid/factory';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { children, splitProps } from 'solid-js';
import { ChevronDownIcon } from '@/lib/moduix/icons/ui/Icons';
import styles from './Collapsible.module.css';

function CollapsibleRoot(props: ComponentProps<typeof CollapsiblePrimitive.Root>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CollapsiblePrimitive.Root
      class={clsx(styles.root, local.class)}
      {...others}
      data-slot="collapsible-root"
    />
  );
}

function CollapsibleRootProvider(props: ComponentProps<typeof CollapsiblePrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CollapsiblePrimitive.RootProvider
      class={clsx(styles.root, local.class)}
      {...others}
      data-slot="collapsible-root-provider"
    />
  );
}

function CollapsibleTrigger(props: ComponentProps<typeof CollapsiblePrimitive.Trigger>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <CollapsiblePrimitive.Trigger
      asChild={local.asChild}
      class={clsx(!local.asChild && styles.trigger, local.class)}
      {...others}
      data-slot="collapsible-trigger"
    />
  );
}

function CollapsibleIndicator(props: ComponentProps<typeof CollapsiblePrimitive.Indicator>) {
  const [local, others] = splitProps(props, ['children', 'class']);
  const resolvedChildren = children(() => local.children);

  return (
    <CollapsiblePrimitive.Indicator
      class={clsx(styles.indicator, local.class)}
      {...others}
      data-slot="collapsible-indicator"
    >
      {resolvedChildren() ?? <ChevronDownIcon />}
    </CollapsiblePrimitive.Indicator>
  );
}

function CollapsibleContent(props: ComponentProps<typeof CollapsiblePrimitive.Content>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CollapsiblePrimitive.Content
      class={clsx(styles.content, local.class)}
      {...others}
      data-slot="collapsible-content"
    />
  );
}

function CollapsibleBody(props: HTMLArkProps<'div'>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <ark.div class={clsx(styles.body, local.class)} {...others} data-slot="collapsible-body" />
  );
}

const Collapsible = Object.assign(CollapsibleRoot, {
  Root: CollapsibleRoot,
  RootProvider: CollapsibleRootProvider,
  Context: CollapsiblePrimitive.Context,
  Trigger: CollapsibleTrigger,
  Indicator: CollapsibleIndicator,
  Content: CollapsibleContent,
  Body: CollapsibleBody,
});

export { Collapsible, useCollapsible, useCollapsibleContext };
