// website/snippets/swap/solid/custom-animation.tsx
import { Button } from '@moduix/solid/button';
import { Swap } from '@moduix/solid/swap';
import CheckIcon from 'lucide-solid/icons/check';
import DownloadIcon from 'lucide-solid/icons/download';
import { createSignal } from 'solid-js';
import styles from '@/components/examples/swap/swap-custom-animation.module.css';

export default function SwapCustomAnimationDemo() {
  const [downloaded, setDownloaded] = createSignal(false);

  return (
    <Button
      aria-label={downloaded() ? 'Downloaded' : 'Download'}
      onClick={() => setDownloaded((value) => !value)}
    >
      <Swap animation="bounce" class={styles.root} swap={downloaded()}>
        <Swap.Indicator aria-hidden="true" type="off">
          <DownloadIcon />
        </Swap.Indicator>
        <Swap.Indicator aria-hidden="true" type="on">
          <CheckIcon />
        </Swap.Indicator>
      </Swap>
    </Button>
  );
}

// website/src/components/examples/swap/custom-animation.tsx
import { Button } from '@moduix/react/button';
import { Swap } from '@moduix/react/swap';
import { Check as CheckIcon, Download as DownloadIcon } from 'lucide-react';
import { useState } from 'react';
import styles from '@/components/examples/swap/swap-custom-animation.module.css';

export default function SwapCustomAnimationDemo() {
  const [downloaded, setDownloaded] = useState(false);

  return (
    <Button
      aria-label={downloaded ? 'Downloaded' : 'Download'}
      onClick={() => setDownloaded((value) => !value)}
    >
      <Swap animation="bounce" className={styles.root} swap={downloaded}>
        <Swap.Indicator aria-hidden="true" type="off">
          <DownloadIcon />
        </Swap.Indicator>
        <Swap.Indicator aria-hidden="true" type="on">
          <CheckIcon />
        </Swap.Indicator>
      </Swap>
    </Button>
  );
}
