// packages/react/src/components/carousel/Carousel.tsx
'use client';

import {
  Carousel as CarouselPrimitive,
  useCarousel,
  useCarouselContext,
} from '@ark-ui/react/carousel';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef } from 'react';
import { forwardRef } from 'react';
import { ChevronLeftIcon, ChevronRightIcon } from '@/lib/moduix/icons/ui';
import styles from './Carousel.module.css';

const Carousel = forwardRef<
  ComponentRef<typeof CarouselPrimitive.Root>,
  ComponentProps<typeof CarouselPrimitive.Root>
>(function Carousel({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.Root
      ref={ref}
      className={clsx(styles.root, className)}
      {...props}
      data-slot="carousel-root"
    />
  );
});

const CarouselRootProvider = forwardRef<
  ComponentRef<typeof CarouselPrimitive.RootProvider>,
  ComponentProps<typeof CarouselPrimitive.RootProvider>
>(function CarouselRootProvider({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.RootProvider
      ref={ref}
      className={clsx(styles.root, className)}
      {...props}
      data-slot="carousel-root-provider"
    />
  );
});

const CarouselControl = forwardRef<
  ComponentRef<typeof CarouselPrimitive.Control>,
  ComponentProps<typeof CarouselPrimitive.Control>
>(function CarouselControl({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.Control
      ref={ref}
      className={clsx(styles.control, className)}
      {...props}
      data-slot="carousel-control"
    />
  );
});

const CarouselItemGroup = forwardRef<
  ComponentRef<typeof CarouselPrimitive.ItemGroup>,
  ComponentProps<typeof CarouselPrimitive.ItemGroup>
>(function CarouselItemGroup({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.ItemGroup
      ref={ref}
      className={clsx(styles.itemGroup, className)}
      {...props}
      data-slot="carousel-item-group"
    />
  );
});

const CarouselItem = forwardRef<
  ComponentRef<typeof CarouselPrimitive.Item>,
  ComponentProps<typeof CarouselPrimitive.Item>
>(function CarouselItem({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.Item
      ref={ref}
      className={clsx(styles.item, className)}
      {...props}
      data-slot="carousel-item"
    />
  );
});

const CarouselPrevTrigger = forwardRef<
  ComponentRef<typeof CarouselPrimitive.PrevTrigger>,
  ComponentProps<typeof CarouselPrimitive.PrevTrigger>
>(function CarouselPrevTrigger({ className, children, ...props }, ref) {
  return (
    <CarouselPrimitive.PrevTrigger
      ref={ref}
      className={clsx(styles.prevTrigger, className)}
      {...props}
      data-slot="carousel-prev-trigger"
    >
      {children ?? (
        <span className={styles.defaultIcon}>
          <ChevronLeftIcon />
        </span>
      )}
    </CarouselPrimitive.PrevTrigger>
  );
});

const CarouselNextTrigger = forwardRef<
  ComponentRef<typeof CarouselPrimitive.NextTrigger>,
  ComponentProps<typeof CarouselPrimitive.NextTrigger>
>(function CarouselNextTrigger({ className, children, ...props }, ref) {
  return (
    <CarouselPrimitive.NextTrigger
      ref={ref}
      className={clsx(styles.nextTrigger, className)}
      {...props}
      data-slot="carousel-next-trigger"
    >
      {children ?? (
        <span className={styles.defaultIcon}>
          <ChevronRightIcon />
        </span>
      )}
    </CarouselPrimitive.NextTrigger>
  );
});

const CarouselIndicatorGroup = forwardRef<
  ComponentRef<typeof CarouselPrimitive.IndicatorGroup>,
  ComponentProps<typeof CarouselPrimitive.IndicatorGroup>
>(function CarouselIndicatorGroup({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.IndicatorGroup
      ref={ref}
      className={clsx(styles.indicatorGroup, className)}
      {...props}
      data-slot="carousel-indicator-group"
    />
  );
});

const CarouselIndicator = forwardRef<
  ComponentRef<typeof CarouselPrimitive.Indicator>,
  ComponentProps<typeof CarouselPrimitive.Indicator>
>(function CarouselIndicator({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.Indicator
      ref={ref}
      className={clsx(styles.indicator, className)}
      {...props}
      data-slot="carousel-indicator"
    />
  );
});

const CarouselIndicators = forwardRef<
  ComponentRef<typeof CarouselPrimitive.IndicatorGroup>,
  Omit<ComponentProps<typeof CarouselPrimitive.IndicatorGroup>, 'asChild' | 'children'> & {
    indicatorClassName?: string;
  }
>(function CarouselIndicators({ className, indicatorClassName, ...props }, ref) {
  return (
    <CarouselPrimitive.Context>
      {(api) => (
        <CarouselIndicatorGroup ref={ref} className={className} {...props}>
          {api.pageSnapPoints.map((_, index) => (
            <CarouselIndicator key={index} index={index} className={indicatorClassName} />
          ))}
        </CarouselIndicatorGroup>
      )}
    </CarouselPrimitive.Context>
  );
});

const CarouselAutoplayTrigger = forwardRef<
  ComponentRef<typeof CarouselPrimitive.AutoplayTrigger>,
  ComponentProps<typeof CarouselPrimitive.AutoplayTrigger>
>(function CarouselAutoplayTrigger({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.AutoplayTrigger
      ref={ref}
      className={clsx(styles.autoplayTrigger, className)}
      {...props}
      data-slot="carousel-autoplay-trigger"
    />
  );
});

const CarouselAutoplayIndicator = forwardRef<
  ComponentRef<typeof CarouselPrimitive.AutoplayIndicator>,
  ComponentProps<typeof CarouselPrimitive.AutoplayIndicator>
>(function CarouselAutoplayIndicator({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.AutoplayIndicator
      ref={ref}
      className={clsx(styles.autoplayIndicator, className)}
      {...props}
      data-slot="carousel-autoplay-indicator"
    />
  );
});

const CarouselProgressText = forwardRef<
  ComponentRef<typeof CarouselPrimitive.ProgressText>,
  ComponentProps<typeof CarouselPrimitive.ProgressText>
>(function CarouselProgressText({ className, ...props }, ref) {
  return (
    <CarouselPrimitive.ProgressText
      ref={ref}
      className={clsx(styles.progressText, className)}
      {...props}
      data-slot="carousel-progress-text"
    />
  );
});

const CarouselContext = CarouselPrimitive.Context;

export {
  Carousel,
  CarouselAutoplayIndicator,
  CarouselAutoplayTrigger,
  CarouselContext,
  CarouselControl,
  CarouselIndicator,
  CarouselIndicatorGroup,
  CarouselIndicators,
  CarouselItem,
  CarouselItemGroup,
  CarouselNextTrigger,
  CarouselPrevTrigger,
  CarouselProgressText,
  CarouselRootProvider,
  useCarousel,
  useCarouselContext,
};

// packages/solid/src/components/carousel/Carousel.tsx
import {
  Carousel as CarouselPrimitive,
  useCarousel,
  useCarouselContext,
} from '@ark-ui/solid/carousel';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { children, Index, splitProps } from 'solid-js';
import { ChevronLeftIcon, ChevronRightIcon } from '@/lib/moduix/icons/ui/Icons';
import styles from './Carousel.module.css';

function Carousel(props: ComponentProps<typeof CarouselPrimitive.Root>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.Root
      class={clsx(styles.root, local.class)}
      {...others}
      data-slot="carousel-root"
    />
  );
}

function CarouselRootProvider(props: ComponentProps<typeof CarouselPrimitive.RootProvider>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.RootProvider
      class={clsx(styles.root, local.class)}
      {...others}
      data-slot="carousel-root-provider"
    />
  );
}

function CarouselControl(props: ComponentProps<typeof CarouselPrimitive.Control>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.Control
      class={clsx(styles.control, local.class)}
      {...others}
      data-slot="carousel-control"
    />
  );
}

function CarouselItemGroup(props: ComponentProps<typeof CarouselPrimitive.ItemGroup>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.ItemGroup
      class={clsx(styles.itemGroup, local.class)}
      {...others}
      data-slot="carousel-item-group"
    />
  );
}

function CarouselItem(props: ComponentProps<typeof CarouselPrimitive.Item>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.Item
      class={clsx(styles.item, local.class)}
      {...others}
      data-slot="carousel-item"
    />
  );
}

function CarouselPrevTrigger(props: ComponentProps<typeof CarouselPrimitive.PrevTrigger>) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);
  const resolvedChildren = children(() => local.children);

  return (
    <CarouselPrimitive.PrevTrigger
      asChild={local.asChild}
      class={clsx(styles.prevTrigger, local.class)}
      {...others}
      data-slot="carousel-prev-trigger"
    >
      {resolvedChildren() ?? (
        <span class={styles.defaultIcon}>
          <ChevronLeftIcon />
        </span>
      )}
    </CarouselPrimitive.PrevTrigger>
  );
}

function CarouselNextTrigger(props: ComponentProps<typeof CarouselPrimitive.NextTrigger>) {
  const [local, others] = splitProps(props, ['asChild', 'children', 'class']);
  const resolvedChildren = children(() => local.children);

  return (
    <CarouselPrimitive.NextTrigger
      asChild={local.asChild}
      class={clsx(styles.nextTrigger, local.class)}
      {...others}
      data-slot="carousel-next-trigger"
    >
      {resolvedChildren() ?? (
        <span class={styles.defaultIcon}>
          <ChevronRightIcon />
        </span>
      )}
    </CarouselPrimitive.NextTrigger>
  );
}

function CarouselIndicatorGroup(props: ComponentProps<typeof CarouselPrimitive.IndicatorGroup>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.IndicatorGroup
      class={clsx(styles.indicatorGroup, local.class)}
      {...others}
      data-slot="carousel-indicator-group"
    />
  );
}

function CarouselIndicator(props: ComponentProps<typeof CarouselPrimitive.Indicator>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.Indicator
      class={clsx(styles.indicator, local.class)}
      {...others}
      data-slot="carousel-indicator"
    />
  );
}

type CarouselIndicatorsProps = Omit<
  ComponentProps<typeof CarouselPrimitive.IndicatorGroup>,
  'asChild' | 'children'
> & {
  indicatorClassName?: string;
};

function CarouselIndicators(props: CarouselIndicatorsProps) {
  const [local, others] = splitProps(props, ['class', 'indicatorClassName']);

  return (
    <CarouselPrimitive.Context>
      {(api) => (
        <CarouselIndicatorGroup class={local.class} {...others}>
          <Index each={api().pageSnapPoints}>
            {(_, index) => <CarouselIndicator index={index} class={local.indicatorClassName} />}
          </Index>
        </CarouselIndicatorGroup>
      )}
    </CarouselPrimitive.Context>
  );
}

function CarouselAutoplayTrigger(props: ComponentProps<typeof CarouselPrimitive.AutoplayTrigger>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.AutoplayTrigger
      class={clsx(styles.autoplayTrigger, local.class)}
      {...others}
      data-slot="carousel-autoplay-trigger"
    />
  );
}

function CarouselAutoplayIndicator(
  props: ComponentProps<typeof CarouselPrimitive.AutoplayIndicator>,
) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.AutoplayIndicator
      class={clsx(styles.autoplayIndicator, local.class)}
      {...others}
      data-slot="carousel-autoplay-indicator"
    />
  );
}

function CarouselProgressText(props: ComponentProps<typeof CarouselPrimitive.ProgressText>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <CarouselPrimitive.ProgressText
      class={clsx(styles.progressText, local.class)}
      {...others}
      data-slot="carousel-progress-text"
    />
  );
}

const CarouselContext = CarouselPrimitive.Context;

export {
  Carousel,
  CarouselAutoplayIndicator,
  CarouselAutoplayTrigger,
  CarouselContext,
  CarouselControl,
  CarouselIndicator,
  CarouselIndicatorGroup,
  CarouselIndicators,
  CarouselItem,
  CarouselItemGroup,
  CarouselNextTrigger,
  CarouselPrevTrigger,
  CarouselProgressText,
  CarouselRootProvider,
  useCarousel,
  useCarouselContext,
};
