// packages/ui/src/components/badge/Badge.tsx
import type { HTMLArkProps } from '@ark-ui/react/factory';
import { ark } from '@ark-ui/react/factory';
import { clsx } from 'clsx';
import { forwardRef } from 'react';
import { normalizeClassName } from '@/lib/moduix/normalizeClassName';
import styles from './Badge.module.css';

export type BadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost';
export type BadgeRootProps = HTMLArkProps<'span'> & {
  variant?: BadgeVariant;
};
export type BadgeDotProps = HTMLArkProps<'span'>;

const BadgeRoot = forwardRef<HTMLSpanElement, BadgeRootProps>(function BadgeRoot(
  { className, variant = 'default', ...props },
  ref,
) {
  return (
    <ark.span
      ref={ref}
      data-scope="badge"
      data-part="root"
      data-slot="badge-root"
      data-variant={variant}
      className={clsx(styles.root, normalizeClassName(className))}
      {...props}
    />
  );
});

const BadgeDot = forwardRef<HTMLSpanElement, BadgeDotProps>(function BadgeDot(
  { className, ...props },
  ref,
) {
  return (
    <ark.span
      ref={ref}
      data-scope="badge"
      data-part="dot"
      data-slot="badge-dot"
      aria-hidden="true"
      className={clsx(styles.dot, normalizeClassName(className))}
      {...props}
    />
  );
});

const Badge = Object.assign(BadgeRoot, {
  Root: BadgeRoot,
  Dot: BadgeDot,
});

export { Badge };

// packages/solid/src/components/badge/Badge.tsx
import type { HTMLArkProps } from '@ark-ui/solid/factory';
import { ark } from '@ark-ui/solid/factory';
import { clsx } from 'clsx';
import { splitProps } from 'solid-js';
import styles from './Badge.module.css';

type BadgeDataProps = {
  'data-scope'?: string;
  'data-part'?: string;
  'data-slot'?: string;
};

type BadgeRootProps = HTMLArkProps<'span'> &
  BadgeDataProps & {
    variant?: 'default' | 'secondary' | 'destructive' | 'outline' | 'ghost' | 'link';
    'data-variant'?: string;
  };

type BadgeLabelProps = HTMLArkProps<'span'> & BadgeDataProps;

type BadgeDotProps = HTMLArkProps<'span'> &
  BadgeDataProps & {
    'aria-hidden'?: boolean | 'true' | 'false';
  };

function BadgeLabel(props: BadgeLabelProps) {
  const [local, others] = splitProps(props, ['class', 'data-scope', 'data-part', 'data-slot']);

  return (
    <ark.span
      {...others}
      data-scope="badge"
      data-part="label"
      data-slot="badge-label"
      class={clsx(styles.label, local.class)}
    />
  );
}

function BadgeRoot(props: BadgeRootProps) {
  const [local, others] = splitProps(props, [
    'class',
    'data-scope',
    'data-part',
    'data-slot',
    'data-variant',
    'variant',
  ]);

  return (
    <ark.span
      {...others}
      data-scope="badge"
      data-part="root"
      data-slot="badge-root"
      data-variant={local.variant ?? 'default'}
      class={clsx(styles.root, local.class)}
    />
  );
}

function BadgeDot(props: BadgeDotProps) {
  const [local, others] = splitProps(props, [
    'aria-hidden',
    'class',
    'data-scope',
    'data-part',
    'data-slot',
  ]);

  return (
    <ark.span
      {...others}
      data-scope="badge"
      data-part="dot"
      data-slot="badge-dot"
      aria-hidden="true"
      class={clsx(styles.dot, local.class)}
    />
  );
}

const Badge = Object.assign(BadgeRoot, {
  Root: BadgeRoot,
  Label: BadgeLabel,
  Dot: BadgeDot,
});

export { Badge };
