// packages/react/src/components/navigation-menu/NavigationMenu.tsx
'use client';

import {
  NavigationMenu as NavigationMenuPrimitive,
  useNavigationMenu,
  useNavigationMenuContext,
} from '@ark-ui/react/navigation-menu';
import { clsx } from 'clsx';
import type { ComponentProps, ComponentRef } from 'react';
import { forwardRef } from 'react';
import styles from './NavigationMenu.module.css';

const NavigationMenuRoot = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Root>,
  ComponentProps<typeof NavigationMenuPrimitive.Root>
>(function NavigationMenuRoot({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Root
      ref={ref}
      data-slot="navigation-menu-root"
      className={clsx(styles.root, className)}
      {...props}
    />
  );
});

const NavigationMenuRootProvider = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.RootProvider>,
  ComponentProps<typeof NavigationMenuPrimitive.RootProvider>
>(function NavigationMenuRootProvider({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.RootProvider
      ref={ref}
      data-slot="navigation-menu-root-provider"
      className={clsx(styles.root, className)}
      {...props}
    />
  );
});

const NavigationMenuList = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.List>,
  ComponentProps<typeof NavigationMenuPrimitive.List>
>(function NavigationMenuList({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.List
      ref={ref}
      data-slot="navigation-menu-list"
      className={clsx(styles.list, className)}
      {...props}
    />
  );
});

const NavigationMenuItem = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Item>,
  ComponentProps<typeof NavigationMenuPrimitive.Item>
>(function NavigationMenuItem({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Item
      ref={ref}
      data-slot="navigation-menu-item"
      className={clsx(styles.item, className)}
      {...props}
    />
  );
});

const NavigationMenuTrigger = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Trigger>,
  ComponentProps<typeof NavigationMenuPrimitive.Trigger>
>(function NavigationMenuTrigger({ asChild, className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Trigger
      ref={ref}
      asChild={asChild}
      data-slot="navigation-menu-trigger"
      className={clsx(!asChild && styles.trigger, className)}
      {...props}
    />
  );
});

const NavigationMenuContent = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Content>,
  ComponentProps<typeof NavigationMenuPrimitive.Content>
>(function NavigationMenuContent({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Content
      ref={ref}
      data-slot="navigation-menu-content"
      className={clsx(styles.content, className)}
      {...props}
    />
  );
});

const NavigationMenuLink = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Link>,
  ComponentProps<typeof NavigationMenuPrimitive.Link>
>(function NavigationMenuLink({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Link
      ref={ref}
      data-slot="navigation-menu-link"
      className={clsx(styles.link, className)}
      {...props}
    />
  );
});

const NavigationMenuIndicator = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Indicator>,
  ComponentProps<typeof NavigationMenuPrimitive.Indicator>
>(function NavigationMenuIndicator({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Indicator
      ref={ref}
      data-slot="navigation-menu-indicator"
      className={clsx(styles.indicator, className)}
      {...props}
    />
  );
});

const NavigationMenuItemIndicator = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.ItemIndicator>,
  ComponentProps<typeof NavigationMenuPrimitive.ItemIndicator>
>(function NavigationMenuItemIndicator({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.ItemIndicator
      ref={ref}
      data-slot="navigation-menu-item-indicator"
      className={clsx(styles.itemIndicator, className)}
      {...props}
    />
  );
});

const NavigationMenuArrow = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Arrow>,
  ComponentProps<typeof NavigationMenuPrimitive.Arrow>
>(function NavigationMenuArrow({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Arrow
      ref={ref}
      data-slot="navigation-menu-arrow"
      className={clsx(styles.arrow, className)}
      {...props}
    />
  );
});

const NavigationMenuViewportPositioner = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.ViewportPositioner>,
  ComponentProps<typeof NavigationMenuPrimitive.ViewportPositioner>
>(function NavigationMenuViewportPositioner({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.ViewportPositioner
      ref={ref}
      data-slot="navigation-menu-viewport-positioner"
      className={clsx(styles.viewportPositioner, className)}
      {...props}
    />
  );
});

const NavigationMenuViewport = forwardRef<
  ComponentRef<typeof NavigationMenuPrimitive.Viewport>,
  ComponentProps<typeof NavigationMenuPrimitive.Viewport>
>(function NavigationMenuViewport({ className, ...props }, ref) {
  return (
    <NavigationMenuPrimitive.Viewport
      ref={ref}
      data-slot="navigation-menu-viewport"
      className={clsx(styles.viewport, className)}
      {...props}
    />
  );
});

const NavigationMenu = Object.assign(NavigationMenuRoot, {
  Root: NavigationMenuRoot,
  RootProvider: NavigationMenuRootProvider,
  Context: NavigationMenuPrimitive.Context,
  List: NavigationMenuList,
  Item: NavigationMenuItem,
  Trigger: NavigationMenuTrigger,
  Content: NavigationMenuContent,
  Link: NavigationMenuLink,
  Indicator: NavigationMenuIndicator,
  ItemIndicator: NavigationMenuItemIndicator,
  Arrow: NavigationMenuArrow,
  ViewportPositioner: NavigationMenuViewportPositioner,
  Viewport: NavigationMenuViewport,
  useNavigationMenu,
});

export { NavigationMenu, useNavigationMenu, useNavigationMenuContext };

// packages/solid/src/components/navigation-menu/NavigationMenu.tsx
import {
  NavigationMenu as NavigationMenuPrimitive,
  useNavigationMenu,
  useNavigationMenuContext,
} from '@ark-ui/solid/navigation-menu';
import { clsx } from 'clsx';
import type { ComponentProps } from 'solid-js';
import { splitProps } from 'solid-js';
import styles from './NavigationMenu.module.css';

function NavigationMenuRoot(props: ComponentProps<typeof NavigationMenuPrimitive.Root>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.Root
      data-slot="navigation-menu-root"
      class={clsx(styles.root, local.class)}
      {...others}
    />
  );
}

function NavigationMenuRootProvider(
  props: ComponentProps<typeof NavigationMenuPrimitive.RootProvider>,
) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.RootProvider
      data-slot="navigation-menu-root-provider"
      class={clsx(styles.root, local.class)}
      {...others}
    />
  );
}

function NavigationMenuList(props: ComponentProps<typeof NavigationMenuPrimitive.List>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.List
      data-slot="navigation-menu-list"
      class={clsx(styles.list, local.class)}
      {...others}
    />
  );
}

function NavigationMenuItem(props: ComponentProps<typeof NavigationMenuPrimitive.Item>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.Item
      data-slot="navigation-menu-item"
      class={clsx(styles.item, local.class)}
      {...others}
    />
  );
}

function NavigationMenuTrigger(props: ComponentProps<typeof NavigationMenuPrimitive.Trigger>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <NavigationMenuPrimitive.Trigger
      data-slot="navigation-menu-trigger"
      asChild={local.asChild}
      class={clsx(!local.asChild && styles.trigger, local.class)}
      {...others}
    />
  );
}

function NavigationMenuContent(props: ComponentProps<typeof NavigationMenuPrimitive.Content>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.Content
      data-slot="navigation-menu-content"
      class={clsx(styles.content, local.class)}
      {...others}
    />
  );
}

function NavigationMenuLink(props: ComponentProps<typeof NavigationMenuPrimitive.Link>) {
  const [local, others] = splitProps(props, ['asChild', 'class']);

  return (
    <NavigationMenuPrimitive.Link
      data-slot="navigation-menu-link"
      asChild={local.asChild}
      class={clsx(styles.link, local.class)}
      {...others}
    />
  );
}

function NavigationMenuIndicator(props: ComponentProps<typeof NavigationMenuPrimitive.Indicator>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.Indicator
      data-slot="navigation-menu-indicator"
      class={clsx(styles.indicator, local.class)}
      {...others}
    />
  );
}

function NavigationMenuItemIndicator(
  props: ComponentProps<typeof NavigationMenuPrimitive.ItemIndicator>,
) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.ItemIndicator
      data-slot="navigation-menu-item-indicator"
      class={clsx(styles.itemIndicator, local.class)}
      {...others}
    />
  );
}

function NavigationMenuArrow(props: ComponentProps<typeof NavigationMenuPrimitive.Arrow>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.Arrow
      data-slot="navigation-menu-arrow"
      class={clsx(styles.arrow, local.class)}
      {...others}
    />
  );
}

function NavigationMenuViewportPositioner(
  props: ComponentProps<typeof NavigationMenuPrimitive.ViewportPositioner>,
) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.ViewportPositioner
      data-slot="navigation-menu-viewport-positioner"
      class={clsx(styles.viewportPositioner, local.class)}
      {...others}
    />
  );
}

function NavigationMenuViewport(props: ComponentProps<typeof NavigationMenuPrimitive.Viewport>) {
  const [local, others] = splitProps(props, ['class']);

  return (
    <NavigationMenuPrimitive.Viewport
      data-slot="navigation-menu-viewport"
      class={clsx(styles.viewport, local.class)}
      {...others}
    />
  );
}

const NavigationMenu = Object.assign(NavigationMenuRoot, {
  Root: NavigationMenuRoot,
  RootProvider: NavigationMenuRootProvider,
  Context: NavigationMenuPrimitive.Context,
  List: NavigationMenuList,
  Item: NavigationMenuItem,
  Trigger: NavigationMenuTrigger,
  Content: NavigationMenuContent,
  Link: NavigationMenuLink,
  Indicator: NavigationMenuIndicator,
  ItemIndicator: NavigationMenuItemIndicator,
  Arrow: NavigationMenuArrow,
  ViewportPositioner: NavigationMenuViewportPositioner,
  Viewport: NavigationMenuViewport,
});

export { useNavigationMenu, useNavigationMenuContext };
export { NavigationMenu };
