// website/docs/en/docs/_snippets/tanstack-form/complete-form.tsx
import { createListCollection, useListCollection } from '@ark-ui/react/collection';
import { useFilter } from '@ark-ui/react/locale';
import { Button } from '@moduix/react/button';
import { Card } from '@moduix/react/card';
import { Checkbox } from '@moduix/react/checkbox';
import { Combobox } from '@moduix/react/combobox';
import { Field } from '@moduix/react/field';
import { Input } from '@moduix/react/input';
import { Select } from '@moduix/react/select';
import { Textarea } from '@moduix/react/textarea';
import { useForm } from '@tanstack/react-form';

const teams = createListCollection({
  items: [
    { label: 'Platform', value: 'platform' },
    { label: 'Product', value: 'product' },
    { label: 'Design', value: 'design' },
  ],
});

const people = [
  { label: 'Ada Lovelace', value: 'ada' },
  { label: 'Grace Hopper', value: 'grace' },
  { label: 'Margaret Hamilton', value: 'margaret' },
  { label: 'Radia Perlman', value: 'radia' },
];

const formId = 'project-form';

function focusFirstInvalid() {
  requestAnimationFrame(() => {
    const formElement = document.getElementById(formId);
    const control = formElement?.querySelector<HTMLElement>('[aria-invalid="true"]:not([hidden])');
    control?.focus();
  });
}

export default function ProjectForm() {
  const { contains } = useFilter({ sensitivity: 'base' });
  const { collection, filter } = useListCollection({
    initialItems: people,
    filter: contains,
  });
  const form = useForm({
    defaultValues: {
      name: '',
      team: '',
      reviewer: '',
      summary: '',
      notifications: false,
    },
    onSubmit: async ({ value }) => {
      await new Promise((resolve) => setTimeout(resolve, 600));
      console.log(value);
    },
    onSubmitInvalid: focusFirstInvalid,
  });

  return (
    <form
      id={formId}
      className="form"
      noValidate
      onSubmit={(event) => {
        event.preventDefault();
        event.stopPropagation();
        void form.handleSubmit();
      }}
    >
      <Card>
        <Card.Header>
          <Card.Title>Create project</Card.Title>
          <Card.Description>Share the details your team needs to get started.</Card.Description>
        </Card.Header>

        <Card.Body className="fields">
          <form.Field
            name="name"
            validators={{
              onSubmit: ({ value }) => (!value ? 'Enter a project name.' : undefined),
            }}
          >
            {(field) => (
              <Field invalid={!field.state.meta.isValid} required>
                <Field.Label>
                  Project name
                  <Field.RequiredIndicator />
                </Field.Label>
                <Input
                  name={field.name}
                  value={field.state.value}
                  onChange={(event) => field.handleChange(event.currentTarget.value)}
                  onBlur={field.handleBlur}
                />
                <Field.ErrorText>{field.state.meta.errors.join(', ')}</Field.ErrorText>
              </Field>
            )}
          </form.Field>

          <form.Field
            name="team"
            validators={{
              onSubmit: ({ value }) => (!value ? 'Choose a team.' : undefined),
            }}
          >
            {(field) => (
              <Field invalid={!field.state.meta.isValid} required>
                <Field.Label>
                  Team
                  <Field.RequiredIndicator />
                </Field.Label>
                <Select
                  collection={teams}
                  name={field.name}
                  value={field.state.value ? [field.state.value] : []}
                  onValueChange={(details) => field.handleChange(details.value[0] ?? '')}
                  onInteractOutside={field.handleBlur}
                >
                  <Select.Control>
                    <Select.Trigger>
                      <Select.ValueText placeholder="Choose a team" />
                    </Select.Trigger>
                    <Select.Indicator />
                  </Select.Control>
                  <Select.Positioner>
                    <Select.Content>
                      {teams.items.map((item) => (
                        <Select.Item key={item.value} item={item}>
                          <Select.ItemText>{item.label}</Select.ItemText>
                          <Select.ItemIndicator />
                        </Select.Item>
                      ))}
                    </Select.Content>
                  </Select.Positioner>
                </Select>
                <Field.ErrorText>{field.state.meta.errors.join(', ')}</Field.ErrorText>
              </Field>
            )}
          </form.Field>

          <form.Field
            name="reviewer"
            validators={{
              onSubmit: ({ value }) => (!value ? 'Choose a reviewer.' : undefined),
            }}
          >
            {(field) => (
              <Field invalid={!field.state.meta.isValid} required>
                <Field.Label>
                  Reviewer
                  <Field.RequiredIndicator />
                </Field.Label>
                <Combobox
                  collection={collection}
                  name={field.name}
                  value={field.state.value ? [field.state.value] : []}
                  onValueChange={(details) => field.handleChange(details.value[0] ?? '')}
                  onInputValueChange={(details) => filter(details.inputValue)}
                >
                  <Combobox.Control>
                    <Combobox.Input onBlur={field.handleBlur} placeholder="Search people" />
                    <Combobox.ClearTrigger aria-label="Clear reviewer" />
                    <Combobox.Trigger aria-label="Open reviewers" />
                  </Combobox.Control>
                  <Combobox.Positioner>
                    <Combobox.Content>
                      <Combobox.Empty>No reviewers found.</Combobox.Empty>
                      <Combobox.List>
                        {collection.items.map((item) => (
                          <Combobox.Option key={item.value} item={item}>
                            {item.label}
                          </Combobox.Option>
                        ))}
                      </Combobox.List>
                    </Combobox.Content>
                  </Combobox.Positioner>
                </Combobox>
                <Field.ErrorText>{field.state.meta.errors.join(', ')}</Field.ErrorText>
              </Field>
            )}
          </form.Field>

          <form.Field name="summary">
            {(field) => (
              <Field>
                <Field.Label>Summary</Field.Label>
                <Textarea
                  name={field.name}
                  value={field.state.value}
                  onChange={(event) => field.handleChange(event.currentTarget.value)}
                  onBlur={field.handleBlur}
                  placeholder="What are you planning to build?"
                  rows={3}
                />
              </Field>
            )}
          </form.Field>

          <form.Field name="notifications">
            {(field) => (
              <Checkbox
                name={field.name}
                checked={field.state.value}
                onCheckedChange={(details) => field.handleChange(details.checked === true)}
                onBlur={field.handleBlur}
              >
                <Checkbox.Control />
                <Checkbox.Label>Send status notifications</Checkbox.Label>
              </Checkbox>
            )}
          </form.Field>
        </Card.Body>

        <Card.Footer>
          <form.Subscribe selector={(state) => [state.canSubmit, state.isSubmitting] as const}>
            {([canSubmit, isSubmitting]) => (
              <Button className="submit" type="submit" disabled={!canSubmit} loading={isSubmitting}>
                {isSubmitting ? 'Creating…' : 'Create project'}
              </Button>
            )}
          </form.Subscribe>
        </Card.Footer>
      </Card>
    </form>
  );
}

// website/snippets/tanstack-form/solid/complete-form.tsx
import { createListCollection, useListCollection } from '@ark-ui/solid/collection';
import { useFilter } from '@ark-ui/solid/locale';
import { Button } from '@moduix/solid/button';
import { Card } from '@moduix/solid/card';
import { Checkbox } from '@moduix/solid/checkbox';
import { Combobox } from '@moduix/solid/combobox';
import { Field } from '@moduix/solid/field';
import { Input } from '@moduix/solid/input';
import { Select } from '@moduix/solid/select';
import { Textarea } from '@moduix/solid/textarea';
import { createForm } from '@tanstack/solid-form';
import { For } from 'solid-js';
import styles from '@/components/examples/tanstack-form/tanstack-form-complete-form.module.css';

const teams = createListCollection({
  items: [
    { label: 'Platform', value: 'platform' },
    { label: 'Product', value: 'product' },
    { label: 'Design', value: 'design' },
  ],
});

const people = [
  { label: 'Ada Lovelace', value: 'ada' },
  { label: 'Grace Hopper', value: 'grace' },
  { label: 'Margaret Hamilton', value: 'margaret' },
  { label: 'Radia Perlman', value: 'radia' },
];

const formId = 'project-form';

function focusFirstInvalid() {
  requestAnimationFrame(() => {
    const formElement = document.getElementById(formId);
    const control = formElement?.querySelector<HTMLElement>('[aria-invalid="true"]:not([hidden])');
    control?.focus();
  });
}

export default function ProjectForm() {
  const { contains } = useFilter({ sensitivity: 'base' })();
  const { collection, filter } = useListCollection({
    initialItems: people,
    filter: contains,
  });
  const form = createForm(() => ({
    defaultValues: {
      name: '',
      team: '',
      reviewer: '',
      summary: '',
      notifications: false,
    },
    onSubmit: async ({ value }) => {
      await new Promise((resolve) => setTimeout(resolve, 600));
      console.log(value);
    },
    onSubmitInvalid: focusFirstInvalid,
  }));

  return (
    <form
      id={formId}
      class={styles.form}
      noValidate
      onSubmit={(event) => {
        event.preventDefault();
        event.stopPropagation();
        void form.handleSubmit();
      }}
    >
      <Card>
        <Card.Header>
          <Card.Title>Create project</Card.Title>
          <Card.Description>Share the details your team needs to get started.</Card.Description>
        </Card.Header>

        <Card.Body class={styles.fields}>
          <form.Field
            name="name"
            validators={{
              onSubmit: ({ value }) => (!value ? 'Enter a project name.' : undefined),
            }}
          >
            {(field) => (
              <Field invalid={!field().state.meta.isValid} required>
                <Field.Label>
                  Project name
                  <Field.RequiredIndicator />
                </Field.Label>
                <Input
                  name={field().name}
                  value={field().state.value}
                  onInput={(event) => field().handleChange(event.currentTarget.value)}
                  onBlur={field().handleBlur}
                />
                <Field.ErrorText>{field().state.meta.errors.join(', ')}</Field.ErrorText>
              </Field>
            )}
          </form.Field>

          <form.Field
            name="team"
            validators={{
              onSubmit: ({ value }) => (!value ? 'Choose a team.' : undefined),
            }}
          >
            {(field) => (
              <Field invalid={!field().state.meta.isValid} required>
                <Field.Label>
                  Team
                  <Field.RequiredIndicator />
                </Field.Label>
                <Select
                  collection={teams}
                  name={field().name}
                  value={field().state.value ? [field().state.value] : []}
                  onValueChange={(details) => field().handleChange(details.value[0] ?? '')}
                  onInteractOutside={field().handleBlur}
                >
                  <Select.Control>
                    <Select.Trigger>
                      <Select.ValueText placeholder="Choose a team" />
                    </Select.Trigger>
                    <Select.Indicator />
                  </Select.Control>
                  <Select.Positioner>
                    <Select.Content>
                      <For each={teams.items}>
                        {(item) => (
                          <Select.Item item={item}>
                            <Select.ItemText>{item.label}</Select.ItemText>
                            <Select.ItemIndicator />
                          </Select.Item>
                        )}
                      </For>
                    </Select.Content>
                  </Select.Positioner>
                  <Select.HiddenSelect />
                </Select>
                <Field.ErrorText>{field().state.meta.errors.join(', ')}</Field.ErrorText>
              </Field>
            )}
          </form.Field>

          <form.Field
            name="reviewer"
            validators={{
              onSubmit: ({ value }) => (!value ? 'Choose a reviewer.' : undefined),
            }}
          >
            {(field) => (
              <Field invalid={!field().state.meta.isValid} required>
                <Field.Label>
                  Reviewer
                  <Field.RequiredIndicator />
                </Field.Label>
                <Combobox
                  collection={collection()}
                  name={field().name}
                  value={field().state.value ? [field().state.value] : []}
                  onValueChange={(details) => field().handleChange(details.value[0] ?? '')}
                  onInputValueChange={(details) => filter(details.inputValue)}
                >
                  <Combobox.Control>
                    <Combobox.Input onBlur={field().handleBlur} placeholder="Search people" />
                    <Combobox.ClearTrigger aria-label="Clear reviewer" />
                    <Combobox.Trigger aria-label="Open reviewers" />
                  </Combobox.Control>
                  <Combobox.Positioner>
                    <Combobox.Content>
                      <Combobox.Empty>No reviewers found.</Combobox.Empty>
                      <Combobox.List>
                        <For each={collection().items}>
                          {(item) => <Combobox.Option item={item}>{item.label}</Combobox.Option>}
                        </For>
                      </Combobox.List>
                    </Combobox.Content>
                  </Combobox.Positioner>
                </Combobox>
                <Field.ErrorText>{field().state.meta.errors.join(', ')}</Field.ErrorText>
              </Field>
            )}
          </form.Field>

          <form.Field name="summary">
            {(field) => (
              <Field>
                <Field.Label>Summary</Field.Label>
                <Textarea
                  name={field().name}
                  value={field().state.value}
                  onInput={(event) => field().handleChange(event.currentTarget.value)}
                  onBlur={field().handleBlur}
                  placeholder="What are you planning to build?"
                  rows={3}
                />
              </Field>
            )}
          </form.Field>

          <form.Field name="notifications">
            {(field) => (
              <Checkbox
                name={field().name}
                checked={field().state.value}
                onCheckedChange={(details) => field().handleChange(details.checked === true)}
                onBlur={field().handleBlur}
              >
                <Checkbox.Control />
                <Checkbox.Label>Send status notifications</Checkbox.Label>
                <Checkbox.HiddenInput />
              </Checkbox>
            )}
          </form.Field>
        </Card.Body>

        <Card.Footer>
          <form.Subscribe
            selector={(state) => ({
              canSubmit: state.canSubmit,
              isSubmitting: state.isSubmitting,
            })}
          >
            {(state) => (
              <Button
                class={styles.submit}
                type="submit"
                disabled={!state().canSubmit}
                loading={state().isSubmitting}
              >
                {state().isSubmitting ? 'Creating…' : 'Create project'}
              </Button>
            )}
          </form.Subscribe>
        </Card.Footer>
      </Card>
    </form>
  );
}
