// website/snippets/date-picker/vue/year-picker.vue
<script setup lang="ts">
import { parseDate } from '@ark-ui/vue/date-picker';
import {
  DatePicker,
  DatePickerContent,
  DatePickerContext,
  DatePickerField,
  DatePickerLabel,
  DatePickerPositioner,
  DatePickerRangeText,
  DatePickerTable,
  DatePickerTableBody,
  DatePickerTableCell,
  DatePickerTableCellTrigger,
  DatePickerTableRow,
  DatePickerView,
  DatePickerViewControl,
  DatePickerPrevTrigger,
  DatePickerNextTrigger,
} from '@moduix/vue/date-picker';

const format = (value: { year: number }) => String(value.year);
</script>

<template>
  <DatePicker
    :default-value="[parseDate('2026-01-01')]"
    default-view="year"
    min-view="year"
    max-view="year"
    :format="format"
  >
    <DatePickerLabel>Year</DatePickerLabel
    ><DatePickerField placeholder="yyyy" clear-label="Clear year" />
    <DatePickerPositioner
      ><DatePickerContent
        ><DatePickerView view="year">
          <DatePickerViewControl
            ><DatePickerPrevTrigger /><DatePickerRangeText /><DatePickerNextTrigger
          /></DatePickerViewControl>
          <DatePickerContext v-slot="context"
            ><DatePickerTable :columns="4"
              ><DatePickerTableBody>
                <DatePickerTableRow
                  v-for="(years, rowIndex) in context.getYearsGrid({ columns: 4 })"
                  :key="rowIndex"
                >
                  <DatePickerTableCell
                    v-for="year in years"
                    :key="year.value"
                    :value="year.value"
                    :disabled="year.disabled"
                    ><DatePickerTableCellTrigger>{{
                      year.label
                    }}</DatePickerTableCellTrigger></DatePickerTableCell
                  >
                </DatePickerTableRow>
              </DatePickerTableBody></DatePickerTable
            ></DatePickerContext
          >
        </DatePickerView></DatePickerContent
      ></DatePickerPositioner
    >
  </DatePicker>
</template>

// website/src/components/examples/date-picker/year-picker.tsx
import { type DateValue } from '@ark-ui/react/date-picker';
import { CalendarDate } from '@internationalized/date';
import {
  DatePicker,
  DatePickerContext,
  DatePickerLabel,
  DatePickerField,
  DatePickerPositioner,
  DatePickerContent,
  DatePickerView,
  DatePickerViewControl,
  DatePickerPrevTrigger,
  DatePickerNextTrigger,
  DatePickerRangeText,
  DatePickerTable,
  DatePickerTableBody,
  DatePickerTableRow,
  DatePickerTableCell,
  DatePickerTableCellTrigger,
} from '@moduix/react/date-picker';

const format = (date: DateValue) => String(date.year);
export default function YearPickerDemo() {
  return (
    <DatePicker
      defaultValue={[new CalendarDate(2026, 1, 1)]}
      defaultView="year"
      minView="year"
      maxView="year"
      format={format}
    >
      <DatePickerLabel>Year</DatePickerLabel>
      <DatePickerField placeholder="yyyy" clearLabel="Clear year" />
      <DatePickerPositioner>
        <DatePickerContent>
          <DatePickerView view="year">
            <DatePickerViewControl>
              <DatePickerPrevTrigger />
              <DatePickerRangeText />
              <DatePickerNextTrigger />
            </DatePickerViewControl>
            <DatePickerContext>
              {(datePicker) => (
                <DatePickerTable columns={4}>
                  <DatePickerTableBody>
                    {datePicker
                      .getYearsGrid({
                        columns: 4,
                      })
                      .map((years, rowIndex) => (
                        <DatePickerTableRow key={rowIndex}>
                          {years.map((year) => (
                            <DatePickerTableCell
                              key={`${year.label}-${year.value}`}
                              value={year.value}
                              disabled={year.disabled}
                            >
                              <DatePickerTableCellTrigger>{year.label}</DatePickerTableCellTrigger>
                            </DatePickerTableCell>
                          ))}
                        </DatePickerTableRow>
                      ))}
                  </DatePickerTableBody>
                </DatePickerTable>
              )}
            </DatePickerContext>
          </DatePickerView>
        </DatePickerContent>
      </DatePickerPositioner>
    </DatePicker>
  );
}
