// packages/react-tailwind/src/components/aspect-ratio/AspectRatio.tsx
import type { HTMLArkProps } from '@ark-ui/react/factory';
import { ark } from '@ark-ui/react/factory';
import type { ComponentRef, CSSProperties } from 'react';
import { forwardRef } from 'react';
import { cn } from '@/lib/moduix/cn';

type AspectRatioProps = HTMLArkProps<'div'> & {
  ratio: number;
};

const AspectRatio = forwardRef<ComponentRef<typeof ark.div>, AspectRatioProps>(function AspectRatio(
  { ratio, className, style, ...props },
  ref,
) {
  if (!Number.isFinite(ratio) || ratio <= 0) {
    throw new RangeError('AspectRatio `ratio` must be a finite number greater than zero.');
  }

  return (
    <ark.div
      {...props}
      ref={ref}
      data-scope="aspect-ratio"
      data-part="root"
      data-slot="aspect-ratio-root"
      className={cn('relative block aspect-[var(--_aspect-ratio-value)] w-full', className)}
      style={{ ...style, '--_aspect-ratio-value': ratio } as CSSProperties}
    />
  );
});

export { AspectRatio };

// packages/vue-tailwind/src/components/aspect-ratio/AspectRatio.vue
<script setup lang="ts">
import { ark } from '@ark-ui/vue/factory';
import type { HTMLArkProps } from '@ark-ui/vue/factory';
import { computed, useAttrs } from 'vue';
import type { HTMLAttributes, StyleValue } from 'vue';
import { cn } from '@/lib/moduix/cn';

defineOptions({ inheritAttrs: false });

export interface Props extends /* @vue-ignore */ HTMLArkProps<'div'> {
  class?: HTMLAttributes['class'];
  style?: StyleValue;
  ratio: number;
}

const { class: className, style, ratio } = defineProps<Props>();
defineSlots<{ default?: () => unknown }>();

const attrs = useAttrs();

const ratioStyle = computed<StyleValue>(() => {
  if (!Number.isFinite(ratio) || ratio <= 0) {
    throw new RangeError('AspectRatio `ratio` must be a finite number greater than zero.');
  }

  return [style, { '--_aspect-ratio-value': ratio }];
});
</script>

<template>
  <ark.div
    v-bind="attrs"
    :class="cn('relative block aspect-[var(--_aspect-ratio-value)] w-full', className)"
    :style="ratioStyle"
    data-scope="aspect-ratio"
    data-part="root"
    data-slot="aspect-ratio-root"
  >
    <slot />
  </ark.div>
</template>
