// apps/docs/docs/en/docs/_snippets/segment-group/form-submission.tsx
import { Button } from '@moduix/react/button';
import { SegmentGroup } from '@moduix/react/segment-group';
import { useState, type FormEvent } from 'react';
import { PreviewMeta } from '@/components/mdx/Components';

const frameworks = [
  { value: 'React', label: 'React' },
  { value: 'Solid', label: 'Solid' },
  { value: 'Svelte', label: 'Svelte' },
  { value: 'Vue', label: 'Vue' },
];

export default function FormSegmentGroupDemo() {
  const [submitted, setSubmitted] = useState('none');
  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const formData = new FormData(form);
    setSubmitted(String(formData.get('framework') ?? 'none'));
  };
  return (
    <form className="segment-stack" onSubmit={handleSubmit}>
      <SegmentGroup aria-label="Framework" name="framework" defaultValue="React">
        <SegmentGroup.Indicator />
        <SegmentGroup.Items items={frameworks} />
      </SegmentGroup>
      <PreviewMeta>
        <output>Submitted: {submitted}</output>
        <Button type="submit" size="sm">
          Submit
        </Button>
      </PreviewMeta>
    </form>
  );
}

// website/snippets/segment-group/solid/form-submission.tsx
import { Button } from '@moduix/solid/button';
import { SegmentGroup } from '@moduix/solid/segment-group';
import { createSignal } from 'solid-js';
import styles from '@/components/examples/segment-group/segment-group-form-submission.module.css';

const frameworks = [
  { value: 'React', label: 'React' },
  { value: 'Solid', label: 'Solid' },
  { value: 'Svelte', label: 'Svelte' },
  { value: 'Vue', label: 'Vue' },
];

export default function FormSegmentGroupDemo() {
  const [submitted, setSubmitted] = createSignal('none');

  function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    setSubmitted(String(new FormData(form).get('framework') ?? 'none'));
  }

  return (
    <form class={styles.root} onSubmit={handleSubmit}>
      <SegmentGroup aria-label="Framework" name="framework" defaultValue="React">
        <SegmentGroup.Indicator />
        <SegmentGroup.Items items={frameworks} />
      </SegmentGroup>
      <output>Submitted: {submitted()}</output>
      <Button type="submit" size="sm">
        Submit
      </Button>
    </form>
  );
}
