// apps/docs/docs/en/docs/_snippets/dialog/mounting-and-focus-lifecycle.tsx
import { Button, Dialog, Field } from '@moduix/react';
import { useRef } from 'react';

export default function DialogLifecycleDemo() {
  const inputRef = useRef(null as HTMLInputElement | null);
  const finalFocusRef = useRef(null as HTMLButtonElement | null);
  return (
    <>
      <Button ref={finalFocusRef}>Final focus target</Button>
      <Dialog
        lazyMount
        unmountOnExit
        initialFocusEl={() => inputRef.current}
        finalFocusEl={() => finalFocusRef.current}
      >
        <Dialog.Trigger asChild>
          <Button>Edit profile</Button>
        </Dialog.Trigger>
        <Dialog.Backdrop />
        <Dialog.Positioner>
          <Dialog.Content>
            <Dialog.Title>Edit profile</Dialog.Title>
            <Dialog.Body>
              <Field>
                <Field.Label>Name</Field.Label>
                <Field.Input ref={inputRef} />
              </Field>
            </Dialog.Body>
            <Dialog.CloseIcon />
          </Dialog.Content>
        </Dialog.Positioner>
      </Dialog>
    </>
  );
}

// website/snippets/dialog/vue/mounting-and-focus-lifecycle.vue
<script setup lang="ts">
import { Button } from '@moduix/vue/button';
import {
  Dialog,
  DialogBackdrop,
  DialogBody,
  DialogCloseIcon,
  DialogContent,
  DialogPositioner,
  DialogTitle,
  DialogTrigger,
} from '@moduix/vue/dialog';
import { Field, FieldLabel } from '@moduix/vue/field';
import { ref } from 'vue';

const inputRef = ref<HTMLInputElement | null>(null);
const finalFocusRef = ref<HTMLElement | null>(null);
</script>

<template>
  <Button ref="finalFocusRef">Final focus target</Button>
  <Dialog
    lazy-mount
    unmount-on-exit
    :initial-focus-el="() => inputRef"
    :final-focus-el="() => finalFocusRef"
  >
    <DialogTrigger as-child><Button>Edit profile</Button></DialogTrigger>
    <DialogBackdrop />
    <DialogPositioner>
      <DialogContent>
        <DialogTitle>Edit profile</DialogTitle>
        <DialogBody>
          <Field>
            <FieldLabel>Name</FieldLabel>
            <input ref="inputRef" />
          </Field>
        </DialogBody>
        <DialogCloseIcon />
      </DialogContent>
    </DialogPositioner>
  </Dialog>
</template>
